### ISSUE TITLE
(FIX inside)  -  Exit button not working on power menu

### ISSUE THREAD

**Issue by binsadik** [SerpentDrago/skin.auramod#1]
**Describe the bug**
When selecting the Exit button under Power tab, it's not working and doesn't exit KODI.

**To Reproduce**
1. Go to 'Power'
2. Click on 'Exit'
3. Then ' Nothing Happens'

**Expected behavior**
To Exit Kodi and close the application.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung TAB S7
 - OS: [Android]

**Comment by Goldenfreddy0703** [comment]
I had that same issue. Thank you for pointing this out.

**Comment by gwilly7** [comment]
I have this issue as well on a Shield Pro

**Comment by SerpentDrago** [comment]
Currently working on fixing the defaults . 

In the meantime you can easily fix this by editing your power menu . 

Settings > skin settings > Miscellaneous > Customise power menu 

Edit any menus that don't work , for example 

Highlight Exit , then go right to edit its Action 
![image](https://user-images.githubusercontent.com/21133858/111529996-2f37be00-8739-11eb-919e-2ead4daf6c8e.png)

Pick KODI Command > Quit 
![image](https://user-images.githubusercontent.com/21133858/111530051-3bbc1680-8739-11eb-9b21-e00b9eed2601.png)

![image](https://user-images.githubusercontent.com/21133858/111530122-4e365000-8739-11eb-85ec-448a553ac01a.png)

![image](https://user-images.githubusercontent.com/21133858/111530195-64dca700-8739-11eb-948a-b164d8f8b4f6.png)


after your done you should see the action changed . Change anything else that doesn't work to a working action the same basic way . Its just like editing any other menu / widget

**Comment by SerpentDrago** [comment]
This is now fixed in 1.0.2 , If your existing user or have this issue even after updating to latest version , you should go to Settings > skin settings > Miscellaneous > Customise power menu , and click Restore Menu Items  (keep going right or left to get it to highlight/select) Then click reset to skin defaults 

![image](https://user-images.githubusercontent.com/21133858/111532410-01a04400-873c-11eb-9943-c88320735e09.png)
