### ISSUE TITLE
Fixed Focus broken

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#10]
On matrix, when you set a widget type to landscape and enable widget showcase overlay, fixed focus is broken, it's only broken with the showcase overlay setting applied.

**Comment by xyzfre** [comment]
Same issue here noticed a couple days ago.

**Comment by SerpentDrago** [comment]
This may have gotten fixed with https://github.com/SerpentDrago/skin.auramod/pull/21
Which is merged to latest matrix branch. 

@xyzfre @JFG1000  confirm if so ill close this issue

**Comment by SerpentDrago** [comment]
This should be fixed in Latest Matrix version 1.0.4  (now even with testing branch ) 

Closing issue
