### ISSUE TITLE
Studio Logo no longer appearing on widget bar, landscape widget, showcase overlay

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#102]
![20210524_131505](https://user-images.githubusercontent.com/76907836/119346502-32e44580-bc92-11eb-830c-8688e5a679e6.jpg)

Nvidia Shield Pro
Kodi 19.1
Auramod 1.0.7
Fen

Studio logo appears in showcase view, but not on the widget bar with setting enabled, tested on both portrait and landscape widgets, showcase overlay/disabled

**Comment by SerpentDrago** [comment]
Will close when we push fix so ya know :) thanks for the report

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.8

**Comment by xyzfre** [comment]
> Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.8

Looks AMAZING now even the movie studio logos show up on home screen widgets using Aura Home Layout which they never did before thank you for the quick fix ,, you guys have done an amazing job with AuraMod it looks GREAT  to have the network logos and movie studio logos on home screen widgets again using Aura Home Layout THANK YOU 🙌🏼
