### ISSUE TITLE
Question: Auramod 1.0.6

### ISSUE THREAD

**Issue by adamosborne83** [SerpentDrago/skin.auramod#104]
Just a quickie.........

I've done all updates and running off your repo, so on version 1.0.6, but on your main screen it says v1.0.10..... should it not auto update?

I've checked my settings and cache etc..... or just me being silly?

**Comment by SerpentDrago** [comment]
What do you mean by "your main screen" ? my github page for auramod ? 

The  Kodi repo will ALWAYS be a bit behind. Now that we have a Kodi repo , The version on the repo is tested for stability. github version is testing/alpha status .  we need to be sure changes are not breaking before pushing to repo and breaking users systems. Anyone installing from zip on this github directly is considered a tester and your taking your own risk by updating as it may not be fully tested.  I tend to wait 3 days before pushing to repo. If we pushed a bad update to repo we could have users unable to start kodi . Especially if they have auto updates enabled .
