### ISSUE TITLE
TV Shows Network Logos don’t show up on next episodes or progress episodes but they do work on home screen widgets

### ISSUE THREAD

**Issue by xyzfre** [SerpentDrago/skin.auramod#105]
https://user-images.githubusercontent.com/49699869/119732321-0709c100-be46-11eb-89e3-69c51d40c3e6.MOV

This issue is a little hard for me to explain hope I make sense but the TV shows network logos on progress or next up episodes only work on home screen widgets but if I enter progress or next up episodes within the add-on The TV show network logos don’t show up but if I go to context  menu browse series and come back out the TV show network logos show up on next up episodes or progress I made a short video to try to explain a little better not a big deal they work everywhere else like they’re supposed to, seems to only happen on next up or progress,, just trying to figure out if it’s on my end,, using Nvidia shield pro on the latest version of AuraMod 1.0.11 ,, Fen and Venom

**Comment by xyzfre** [comment]
My apologies for the poor video quality

**Comment by SerpentDrago** [comment]
Your using landscape showcase view inside addon?  We have noticed some vews cause a weird bug if default . Try switching views when it doesn't work to poster view For shows and movies and episode view for episodes for now .. About half the views have this odd bug .

It's proving to be a bitch

**Comment by xyzfre** [comment]
Ok it’s not really a big issue just wanted to keep you posted but I’m very happy with the way AuraMod is working so smooth and increasing the size of the network  logos makes it look Real nice and also having the movie studio logos is also a plus🙌🏼

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.12

**Comment by SerpentDrago** [comment]
Once tested and confirmed good will push to repo @xyzfre  please test

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/119969562-ba74d180-bf7c-11eb-930f-599c85cc50ec.MOV
On v1.0.12 The next up episode and progress is fixed but now they don’t show up on home screen widgets both TV show network logos and movie studio logos ,,using Aura Home Layout Nvidia shield pro K19.1 here’s a quick video

**Comment by inb4after** [comment]
@xyzfre Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.13

**Comment by xyzfre** [comment]
Tested v1.0.13 everything is working TV Show Network Logos are showing up correct in next up episodes and in progress and Home Screen Widgets and Movie Studio logos as well GREAT WORK✊🏼 thank you for all the fixes 👌🏼 ,, everything looks AMAZINGLY well ,,Really appreciate it
