### ISSUE TITLE
Spotlight Mobie titles disappeared.

### ISSUE THREAD

**Issue by adamosborne83** [SerpentDrago/skin.auramod#107]
Hey sorry,

See the video below, again all of a sudden the title of the movies or TV shows on spotlight has disappeared.

I've tried clearing cache etc still no good.

http://imgur.com/a/N0EebIa

**Comment by SerpentDrago** [comment]
This is 100 percent related to your other artwork issue post

**Comment by inb4after** [comment]
Closed, probable duplicate of #106 and most likely not an AuraMOD issue as we cannot reproduce.
