### ISSUE TITLE
Slight clipping with ratings and studio logo on home screen

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#109]
Netflix mixed home layout on main menu going down the list of widgets doesn't seem to bug it out, but when I start to go up the list it cuts the bottom off of the ratings and studio logo section a little bit:

Going down > No Problem.
Going up > Seems to not go back to the same spot. 

https://user-images.githubusercontent.com/17692472/120372899-9858b780-c2cc-11eb-9e2e-4d76078a1309.mp4

Sorry for going a little quick, 10mb upload limit is a little small for video. 

widget layout:
`recommended movies` (top widget.. bug doesn't show on this one)(auramod)(poster)
`featured actor` (autowidget)(landscapesmall)
`similiar movie` (skinhelperwidgets)(poster)(widget showcase overlay with autohide)
`featured genre` (autowidget)(landscapepanel)
`top rated movies` (auramod)(landscapepanel)(widget showcase overlay with autohide)
`featured movie set` (autowidget)(landscasmall)
`unwatched movies` (auramod)(landscapepanel)(widget showcase overlay with autohide)

Seems to only happen when going between widgets rather than rows:

https://user-images.githubusercontent.com/17692472/120374522-7fe99c80-c2ce-11eb-9ca4-1bcfcffcd100.mp4

I am on a 1366 x 768 screen though, so I don't know if that's why. Sometimes ui get a little bulky.
I can still see everything and it's only a slight clip, but I just thought I'd share.

**Comment by inb4after** [comment]
It's been a well known bug since Leia. I think it's actually the widget itself that moves to the wrong position.


I'll look into it soon.

**Comment by Dealz-416LS** [comment]
@inb4after I mentioned this issue to you recently, I believe your right from my experience when I navigate through 3 rows of widgets - 1st/top row > 2nd/middle row > 3rd/last row then back up to 2nd/middle row in Netflix Home Style the 2nd/middle row shifts up a bit, enough to clip slightly over the rating and studio logo.

1st/top and 3rd/last row of widgets are fine and don't have the issue in my setup.

![image](https://user-images.githubusercontent.com/54026944/120572735-618db900-c414-11eb-8df6-6c80cdf3b9a1.jpeg)

**Comment by computechnopro** [comment]
I have the same issue but, when you scroll up and down once from this point, it becomes normal🤔

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.19

Needs testing, before this issue can be closed.

**Comment by Dealz-416LS** [comment]
@inb4after tested and fixed for me, Thank you!

**Comment by computechnopro** [comment]
> Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.19
> 
> Needs testing, before this issue can be closed.

How do I update? No updates from repo in kodi🤔

**Comment by xyzfre** [comment]
> > Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.19
> > Needs testing, before this issue can be closed.
> 
> How do I update? No updates from repo in kodi🤔

You have to download the zip from GitHub because it’s not a repo update

**Comment by jojobrogess** [comment]
Looks like it's been fixed, although  when you use 'landscapepanel' as a widget type, the second row is extremely close to the bottom of the screen. (Compare that to 'poster' and you'll see what I mean.) I'm not home atm so I can't provide screen shots. But when I get home I will take them and see if I can show what I mean. But it does look like you fixed the bug. THANK YOU!

**Comment by inb4after** [comment]
> 
> 
> Looks like it's been fixed, although when you use 'landscapepanel' as a widget type, the second row is extremely close to the bottom of the screen. (Compare that to 'poster' and you'll see what I mean.) I'm not home atm so I can't provide screen shots. But when I get home I will take them and see if I can show what I mean. But it does look like you fixed the bug. THANK YOU!

In comparison screenshots the position is exactly the same as before 1.0.19 on down scrolling.

It can be adjusted, but then other widgets would have to be moved up as well. I'll see what I can do.

**Comment by jojobrogess** [comment]
This is with `Poster`
![Inked2021-06-05 18_33_48-Greenshot_LI](https://user-images.githubusercontent.com/17692472/120909803-b5271f00-c62d-11eb-8e44-157de801ff21.jpg)

`LandscapeSmall`
![Inked2021-06-05 18_33_57-Greenshot_LI](https://user-images.githubusercontent.com/17692472/120909806-c708c200-c62d-11eb-9865-010a9a4e5efe.jpg)

`LandscapePanel`

![Inked2021-06-05 18_34_15-Greenshot_LI](https://user-images.githubusercontent.com/17692472/120909809-ce2fd000-c62d-11eb-898b-0ba7033523cb.jpg)

`LandscapePanel`

![Inked2021-06-05 18_34_10-Greenshot_LI](https://user-images.githubusercontent.com/17692472/120909810-d25bed80-c62d-11eb-8dc4-2c45a53194fc.jpg)

As you can see from the bottom two pictures that the area below the widget is considerably close to the bottom of the screen.

**Comment by inb4after** [comment]
@jojobrogess 

Moving up all widgets doesn't look correct for widgets that are not LandscapePanel, and trying to make LandscapePanel only adjustments introduced other weird slide bugs and title misalignment when moving between widgets/menu items etc.

For now, I will leave it as is, but in future it will be considered. Please open a separate feature request for this, as this issue will be closed.

**Comment by jojobrogess** [comment]
Ahh yeah that makes sense okay, well thank you for explaining and thank you for fixing a really old bug!
