### ISSUE TITLE
[BUG] Search history not saving

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#11]
Searches done using the custom search isn't saving the search history.

`Settings > Search Lists > Enable Search History (requies tmdb list)` is checked.

I also have both the default TMDB searches enabled.

`DEFAULTSEARCH-TMDBSHOWS`
`DEFAULTSEARCH-TMDBMOVIES`

and a custom one i added for people (I assume this won't work as it's not a default list? but it is a TMDB list so maybe)
`ACTIVATEWINDOW(VIDEOS,"PLUGIN://PLUGIN.VIDEO.THEMOVIEDB.HELPER/?INFO=SEARCH&TMDB_TYPE=PERSON&QUERY=`

[kodi.log](https://github.com/SerpentDrago/skin.auramod/files/6178537/kodi.log)

The log should have captured a few searches i done, hopefully will give a clue as to what the issue is.

**Comment by SerpentDrago** [comment]
Yep seems to be broken , the way auramod search history works is it just loads the history from tmdb helper . so if that path changed in a tmdb helper it would break .  

Doesn't matter what search lists are added as long as tmdb is added at least , as it will cause a search to happen in that addon and thous have history . (if the paths didn't change ;0 ) 

i'll add it to the todo list , thanks for the report  , Shouldn't be a hard fix hopefully when i get around to it

**Comment by Goldenfreddy0703** [comment]
Thank you for pointing out this bug, i wasn't sure if that was still working or not and i have not tested it out yet.

**Comment by SerpentDrago** [comment]
I've tracked this issue down to what appears to be a bug in tmdb helper , if search is called outside the addon its not saving history . 

You will see history in auramod search will show if you search inside tmdb helper . but not if you search with auramod . 

Waiting on developer feedback , I reported the bug

**Comment by SerpentDrago** [comment]
THIS is now fixed with latest TMDB helper ! 

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/522247ad215b441c5fb405c2289e2d71f732af92

Update to TMDB helper 4.3.1 or higher , From jurial repo 

![image](https://user-images.githubusercontent.com/21133858/112318266-3e5fc400-8c83-11eb-8cb6-e401ef29a7fc.png)
