### ISSUE TITLE
Continue watching and cast &more

### ISSUE THREAD

**Issue by deyooluv** [SerpentDrago/skin.auramod#111]
The continue watching text for widget with video or tv shows with resume(finish watching) contents are missing after latest updates. Another issue I am experiencing is with the cast and more. When you click next page for recommended or similar movies or TV shows in cast and more don't work.
![Screenshot_20210601-172026_Kodi](https://user-images.githubusercontent.com/73711940/120402088-94458d80-c2fe-11eb-81e7-79dfbf2e8b8c.jpg)

**Comment by SerpentDrago** [comment]
What addon path  is that widget  pointed at , or library path . Need much more details on where your getting these issues / what addon is providing the item / etc . etc.  are you using netflix home style ? what version of AuraMOD are you running ? what version of AuraMOD was it working on ?

**Comment by deyooluv** [comment]
@SerpentDrago I am using version 1.0.17 and Netflix home style. I am pointing it to Seren. I tried Fen, venom and others but still the same. That screenshot with the continue watching was from  version  1. 0.4

**Comment by inb4after** [comment]
Do you have a screenshot of what it looks like currently?

**Comment by inb4after** [comment]
@deyooluv

Try disabling `Skin Settings > Library Views > Show full Spotlight info for Episodes`.

**Comment by deyooluv** [comment]
> @deyooluv
> 
> Try disabling `Skin Settings > Library Views > Show full Spotlight info for Episodes`.

@inb4after that looks good. Thank you
Will you be fixing the next page for movies and tv shows in the cast and more?
The next page for tv shows or movies in the cast and more for similar, director etc don't work

**Comment by inb4after** [comment]
> > @deyooluv
> > 
> > Try disabling `Skin Settings > Library Views > Show full Spotlight info for Episodes`.
> 
> @inb4after that looks good. Thank you
> Will you be fixing the next page for movies and tv shows in the cast and more?
> The next page for tv shows or movies in the cast and more for similar, director etc don't work

Please make a separate issue and attach a video so I can track it.
