### ISSUE TITLE
Error in the ratings within the cast & more section 

### ISSUE THREAD

**Issue by gtkingbuild** [SerpentDrago/skin.auramod#114]
When I enter Cast & more, any movie returns me exactly the same rating as the movie with which I entered the Cast & More section
![IMG_20210604_095312_675](https://user-images.githubusercontent.com/68242121/120767345-6a1ce700-c51b-11eb-972f-d9d6106f12c5.jpg)
![IMG_20210604_095316_974](https://user-images.githubusercontent.com/68242121/120767351-6ab57d80-c51b-11eb-86a0-9b8a08af81dd.jpg)
![IMG_20210604_095320_011](https://user-images.githubusercontent.com/68242121/120767356-6b4e1400-c51b-11eb-9245-8be18e18f2ea.jpg)
![IMG_20210604_095322_706](https://user-images.githubusercontent.com/68242121/120767359-6b4e1400-c51b-11eb-9baa-a23bc3d129a6.jpg)
![IMG_20210604_095324_564](https://user-images.githubusercontent.com/68242121/120767361-6be6aa80-c51b-11eb-8825-b3799d321bcc.jpg)
![IMG_20210604_095328_652](https://user-images.githubusercontent.com/68242121/120767364-6be6aa80-c51b-11eb-8caf-f30dc4391de5.jpg)

**Comment by inb4after** [comment]
As far as I know, there's no option for TMDBHelper service monitor to send ratings of items in a different container. I'll have to ask jurial for some insight about this. This might mean we have to disable ratings completely for this screen, or stick with the basic ratings that Kodi itself can provide.

Are you using the Aura Home widget style? (this question is related to another issue)

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.21

Needs testing, before this issue can be closed.

**Comment by xyzfre** [comment]
I didn’t open this issue but I know it’s a known bug since 18 ,, give me like 10 to 15 minutes and I will test for you

**Comment by inb4after** [comment]
Removed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.22

Reasoning: Major performance issues with Netflix Info, quickly rate limited API usage, unavoidable visual bugs.

**Comment by inb4after** [comment]
Re-added in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.23

Hopefully this update is more stable compared to the initial attempt, thanks again to jurialmunkey for helping me on this.
