### ISSUE TITLE
Latest Update, Aurahome UI broken with small category bar enabled

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#115]
![20210605_154925](https://user-images.githubusercontent.com/76907836/120895692-13480800-c616-11eb-8d0e-5183c7a951ec.jpg)

Kodi.19.1
Nvidia Shield Pro
Auramod 1.0. 19

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.20

Thanks for finding this one, please test the new version and report any further bugs with widget positions since 1.0.19.

**Comment by JFG1000** [comment]
No problem, I'll download and test it now, I'll get back to you

**Comment by JFG1000** [comment]
Tested and all seems fine thankyou, will close post
