### ISSUE TITLE
Low priority Feature Request: (Custom font.xml included)- 

### ISSUE THREAD

**Issue by brviewer** [SerpentDrago/skin.auramod#116]
I use a pretty heavily modified font.xml file for large screen tv couch viewing and wanted to offer it to be added if you think it will be of benefit to others.

[CouchFont.txt](https://github.com/SerpentDrago/skin.auramod/files/6602906/CouchFont.txt)

**Comment by inb4after** [comment]
It can't be added to the skin as there can only be one Font.xml. Instead, users can download and use this font file manually if they need custom/bigger fonts. Thanks for the upload!
