### ISSUE TITLE
Translate location

### ISSUE THREAD

**Issue by wsx79** [SerpentDrago/skin.auramod#118]
I looking for this two word for translate but I can't find in skin.
The only shortcut I found is in IncludeObject.
Can anyone tell me where are thay?
Thanks
![Immagine](https://user-images.githubusercontent.com/68690475/120933929-9d6a9c00-c6fc-11eb-816d-6393cd838570.png)

**Comment by inb4after** [comment]
% Liked: 
https://github.com/SerpentDrago/skin.auramod/blob/5475af908fc20be7bdb68fc50b1768a3342f3cea/1080i/Includes_Labels.xml#L154

% remaining: 
https://github.com/SerpentDrago/skin.auramod/blob/5475af908fc20be7bdb68fc50b1768a3342f3cea/1080i/Includes_Object.xml#L1587

https://github.com/SerpentDrago/skin.auramod/blob/5475af908fc20be7bdb68fc50b1768a3342f3cea/1080i/Includes_Object.xml#L1983

https://github.com/SerpentDrago/skin.auramod/blob/5475af908fc20be7bdb68fc50b1768a3342f3cea/1080i/Includes_WidgetMods.xml#L417

https://github.com/SerpentDrago/skin.auramod/blob/5475af908fc20be7bdb68fc50b1768a3342f3cea/1080i/Includes_WidgetMods.xml#L566

https://github.com/SerpentDrago/skin.auramod/blob/5475af908fc20be7bdb68fc50b1768a3342f3cea/1080i/Includes_WidgetMods.xml#L1219

https://github.com/SerpentDrago/skin.auramod/blob/5475af908fc20be7bdb68fc50b1768a3342f3cea/1080i/Includes_WidgetMods.xml#L1335
