### ISSUE TITLE
Can’t change loading icon

### ISSUE THREAD

**Issue by xyzfre** [SerpentDrago/skin.auramod#12]
When trying to change the loading icon to your own gif when you choose the icon you want it won’t change ,,the splash screen works fine when you pick your own but not the loading icon ,,hope it can be fix this is a GREAT feature of the skin

**Comment by SerpentDrago** [comment]
yes , seems to be broken , I replicated the issue . 

Will look into later , low priority

**Comment by xyzfre** [comment]
So far AuraMod testing branch has been working amazingly well on my end all I need is this little minor fix to complete my build The way I want it ,hopefully it will get sorted soon really appreciate all the hard work that’s been done with these last couple updates to keep AuraMod going hopefully forever LOL

**Comment by SerpentDrago** [comment]
for now i may just change the default loading gif to this one > 

![loading2](https://user-images.githubusercontent.com/21133858/113742758-f011e280-96d0-11eb-8b5d-6c375013ee34.gif)

But its one of the issues i think i can figure out , if i get time

**Comment by xyzfre** [comment]
Thank you for the response ,this one looks GREAT!! I like it you should go for it

**Comment by SerpentDrago** [comment]
This should be happily fixed by installing color box and restarting kodi :) thank the dr for porting it , apparently auramod uses it somehow to set a custom loading gif ! 

https://github.com/drinfernoo/script.colorbox/tree/matrix
