### ISSUE TITLE
Skin Helper Widget Similiar widget label misalignement 

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#120]
![1](https://user-images.githubusercontent.com/17692472/121111196-4ed40500-c7c3-11eb-8c57-247a18f1e6f7.jpg)
![2](https://user-images.githubusercontent.com/17692472/121111206-51365f00-c7c3-11eb-866a-90edd4760365.png)
![3](https://user-images.githubusercontent.com/17692472/121111209-51cef580-c7c3-11eb-90d1-4400e4a9e38e.png)
As you can see it looks like it's aligned to the top rather than the bottom. As well as the font is different. 
![4](https://user-images.githubusercontent.com/17692472/121111217-5398b900-c7c3-11eb-84ef-a2235d0aaf80.png)
Is this something that's controlled by the skin or skin helper widget?

If you try to do it within the widget label it looks like this:
![5](https://user-images.githubusercontent.com/17692472/121111354-8f338300-c7c3-11eb-8321-a038e1e042f6.png)
![6](https://user-images.githubusercontent.com/17692472/121111360-90fd4680-c7c3-11eb-8a05-b3d18bd9b3b5.png)

My guess would be that that means skin helper widget controls it?

**Comment by jojobrogess** [comment]
Oh and what is this menu? I can only get it to activate when I use my mouse and move it to the right side of the screen.
![7](https://user-images.githubusercontent.com/17692472/121118061-0d952280-c7ce-11eb-9061-7b70c397ba3b.png)

It's not my home menu, this is:
![7a](https://user-images.githubusercontent.com/17692472/121118170-40d7b180-c7ce-11eb-8de7-e3fd06f8059f.png)

**Comment by inb4after** [comment]
Which of these three options looks best?

Original, positioned properly: https://i.imgur.com/6qlIzNh.png
Thin bold font: https://i.imgur.com/dx2IvWH.png
Thick bold font, same as widget title: https://i.imgur.com/oZiOKu2.png

That menu is `Skin Settings > Hubs & Spotlights > Enable TV/Movie Submenu on left`, and only works if you are inside a hub. There is a bug with mouse input which means it can be scrolled to on main homescreen even if it is disabled.

**Comment by Goldenfreddy0703** [comment]
Hey I just saw this. I think the original one looks better cause it's not mixed in with the bold text for TV shows.

**Comment by xyzfre** [comment]
I vote for the Thin bold , I think it looks great👍🏼,, A big shout out for keeping up with AuraMod The changes you guys are doing lately are making the skin a lot better and to me it was always The best✊🏼

**Comment by inb4after** [comment]
Decided to go with the thick bold font, to match the widget label, for consistency. Also removed the "to" prefix, which allows you more flexibility in customizing your widget title exactly as you want:

Original layout is still possible: https://i.imgur.com/2GTsABS.png
Setting for above: https://i.imgur.com/ISih32q.png

New widget title, with better grammar than original layout: https://i.imgur.com/h9lsyk4.png
Setting for above: https://i.imgur.com/tpoNSEf.png

Because you watched: https://i.imgur.com/ngVNnjz.png
Setting for above: https://i.imgur.com/y7APspQ.png

**Comment by inb4after** [comment]
Improved in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.30
