### ISSUE TITLE
Bottom of LandscapePanel Widget  is too Close to the bottom of screen 

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#121]
This was suggested to be added as a new Feature Request by inb4after
_Originally posted by @jojobrogess in https://github.com/SerpentDrago/skin.auramod/issues/109#issuecomment-855322784_

When you use 'landscapepanel' as a widget type, the second row is extremely close to the bottom of the screen. (Compare that to 'poster' and you'll see what I mean.)

This is with `Poster`
![Inked2021-06-05 18_33_48-Greenshot_LI](https://user-images.githubusercontent.com/17692472/120909803-b5271f00-c62d-11eb-8e44-157de801ff21.jpg)

`LandscapeSmall`
![Inked2021-06-05 18_33_57-Greenshot_LI](https://user-images.githubusercontent.com/17692472/120909806-c708c200-c62d-11eb-9865-010a9a4e5efe.jpg)

`LandscapePanel`

![Inked2021-06-05 18_34_15-Greenshot_LI](https://user-images.githubusercontent.com/17692472/120909809-ce2fd000-c62d-11eb-898b-0ba7033523cb.jpg)

`LandscapePanel`

![Inked2021-06-05 18_34_10-Greenshot_LI](https://user-images.githubusercontent.com/17692472/120909810-d25bed80-c62d-11eb-8dc4-2c45a53194fc.jpg)

As you can see from the bottom two pictures that the area below the widget is considerably close to the bottom of the screen.

I think adjusting the whole bottom menu upward will definitely cause problems, but maybe resizing the LandscapePanel widget size slightly could work? Although since there are 2 rows, they are already pretty small.

**Comment by inb4after** [comment]
Improved in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.29

I was only able to improve LandscapePanel hub widgets slightly, as moving the widget title up for only LandscapePanel widgets would result in title misalignment when scrolling hub side list.

Moving all hub widgets upwards regardless of aspect, would make the spacing uneven for most of the other widgets.

With that said, homescreen LandscapePanel widgets did allow for more flexibility, and it looks much better after this update.
