### ISSUE TITLE
Crunchyroll addon does not display any show info other than title

### ISSUE THREAD

**Issue by TheFantasticLoki** [SerpentDrago/skin.auramod#122]
I have tried using both normal widget and auto widget but cannot get any info such as plot, rating, release date, etc to display. Side note: Context menu's appear to be broken as well as they do not display the same options from home screen as through direct addon interaction. Using Devhelper shows correct plot, etc when on home screen yet no info actually displayed. See attached screenshots:

No info on Home page:
![image](https://user-images.githubusercontent.com/26889568/121448790-9ee2d100-c955-11eb-8f78-d79234535643.png)

Incorrect Context Menu Options:
![image](https://user-images.githubusercontent.com/26889568/121449108-58da3d00-c956-11eb-9a7a-5f1e14d62dcc.png)

Devhelper Screencap to show proper info being grabbed but not displayed:
![image](https://user-images.githubusercontent.com/26889568/121449229-a060c900-c956-11eb-9067-7a454f832142.png)

Info shows proper through direct addon interaction:
![image](https://user-images.githubusercontent.com/26889568/121449310-c6866900-c956-11eb-9130-fe6b25e0433c.png)

Proper Context Menu Options through Direct Addon Interaction:
![image](https://user-images.githubusercontent.com/26889568/121449358-e1f17400-c956-11eb-928f-52af102103d7.png)

Current Ver of AuraMod: 1.0.18
![image](https://user-images.githubusercontent.com/26889568/121449437-0c433180-c957-11eb-8cab-3aa4671e88d2.png)

Proper Info Showing with other addons like TMDB Helper (No Crunchyroll Player Available for TMDB Helper so not an option):
![image](https://user-images.githubusercontent.com/26889568/121449557-48769200-c957-11eb-9005-cd72cc39fde2.png)

**Comment by TheFantasticLoki** [comment]
Some screencaps of container.listitem.infolabels:
![image](https://user-images.githubusercontent.com/26889568/121453355-482dc500-c95e-11eb-96d5-fef7faba2090.png)

![image](https://user-images.githubusercontent.com/26889568/121453382-5380f080-c95e-11eb-9c01-024ba9e3ed43.png)

**Comment by TheFantasticLoki** [comment]
idrc if yall don't have a definite solution but if anyone could provide just some things for me to try that would be very helpful.

**Comment by Goldenfreddy0703** [comment]
You may wanna update to the latest version of auramod and see if you get the same issue.

**Comment by TheFantasticLoki** [comment]
Issue still persists after updating to latest release from 14 hours ago.

**Comment by TheFantasticLoki** [comment]
Here is my latest log after updating and going to the crunchyroll/anime tab with issue still persisting. This includes lack of info & context menu options though context menu may just need a seperate addon to be developed.
[kodi.log](https://github.com/SerpentDrago/skin.auramod/files/6636350/kodi.log)

**Comment by TheFantasticLoki** [comment]
actually it failed the install but reloaded the skin so I thought it updated properly. Fails to install due to 404 errors on PureRepo1 and others Error posted below


22:55:37.990 T:12688 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
22:55:38.133 T:12688   ERROR: CScriptInvocationManager::ExecuteAsync - Not executing non-existing script script.grab.fanart
22:55:38.133 T:12688 WARNING: CApplication::Initialize - startup.xml taints init process
22:55:38.178 T:12688  NOTICE: initialize done
22:55:38.178 T:12688  NOTICE: Running the application...
22:55:40.951 T:12688  NOTICE: starting upnp client
22:55:40.955 T:14384  NOTICE: ES: Starting UDP Event server on port 9777
22:55:40.955 T:14384  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
22:55:42.481 T:12248   ERROR: CCurlFile::Open failed with code 404 for https://raw.githubusercontent.com/PureRepo1/PureRepo1/master/Zips/addons.xml.md5
22:55:42.481 T:12248   ERROR: XFILE::CFileCache::Open - failed to open source <https://raw.githubusercontent.com/PureRepo1/PureRepo1/master/Zips/addons.xml.md5>
22:55:42.481 T:12248   ERROR: CRepository: failed read 'https://raw.githubusercontent.com/PureRepo1/PureRepo1/master/Zips/addons.xml.md5'
22:55:42.607 T:17112   ERROR: CCurlFile::Open failed with code 404 for http://mahousecm.com/scarecrow/addons.xml.md5
22:55:42.607 T:17112   ERROR: XFILE::CFileCache::Open - failed to open source <http://mahousecm.com/scarecrow/addons.xml.md5>
22:55:42.607 T:17112   ERROR: CRepository: failed read 'http://mahousecm.com/scarecrow/addons.xml.md5'
22:55:42.997 T:12248   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
22:55:42.997 T:12248   ERROR: CCurlFile::Open failed with code 0 for http://ukodi1.pw/_repo/addons.xml.md5
22:55:42.997 T:12248   ERROR: XFILE::CFileCache::Open - failed to open source <http://ukodi1.pw/_repo/addons.xml.md5>
22:55:42.997 T:12248   ERROR: CRepository: failed read 'http://ukodi1.pw/_repo/addons.xml.md5'
22:55:43.130 T:7732   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
22:55:43.130 T:7732   ERROR: CCurlFile::Open failed with code 0 for http://lillywhiteyid.tk/oka/addons/addons.xml.md5
22:55:43.130 T:7732   ERROR: XFILE::CFileCache::Open - failed to open source <http://lillywhiteyid.tk/oka/addons/addons.xml.md5>
22:55:43.130 T:7732   ERROR: CRepository: failed read 'http://lillywhiteyid.tk/oka/addons/addons.xml.md5'
22:55:44.525 T:17112   ERROR: XFILE::CDirectory::GetDirectory - Error getting library%3a%2f%2fvideo%2frecentlyaddedmovies.xml%2f/
22:55:44.525 T:17112   ERROR: Previous line repeats 3 times.
22:55:44.525 T:17112   ERROR: XFILE::CDirectory::GetDirectory - Error getting
22:55:50.160 T:7732   ERROR: Previous line repeats 7 times.
22:55:50.160 T:7732   ERROR: CPythonInvoker(8, C:\Users\astey\AppData\Roaming\Kodi\addons\plugin.video.StarTec\service.py): script didn't stop in 5 seconds - let's kill it

**Comment by inb4after** [comment]
Seems to be an issue with crunchyroll addon sending empty/incorrect ListItem.DBType/Container.ListItem.DBType. 

For example, show and season level has no Container./ListItem.DBType and episode level has `tvshows`+`video` Container./ListItem.DBType. This doesn't follow the conventional system of `tvshow`, `season`, `episode`.

Can you send more screenshots of these InfoLabels when focusing different widgets like Queue and Featured then open a show, then open a season.

We can probably try to work around this, if it doesn't introduce more bugs.

**Comment by TheFantasticLoki** [comment]
Updated to latest release issue still persists will get more screenshots.

**Comment by TheFantasticLoki** [comment]
Crunchyroll Widget Screencaps:

Queue:
![image](https://user-images.githubusercontent.com/26889568/121650317-accc4b00-ca56-11eb-8d24-fd0e3131243f.png)
Featured:
![image](https://user-images.githubusercontent.com/26889568/121650389-c372a200-ca56-11eb-814f-b0ec1ac024b1.png)
Popular:
![image](https://user-images.githubusercontent.com/26889568/121650535-df764380-ca56-11eb-99bd-333209159edf.png)


Netflix Widget Screencaps:

Continue Watching on Movie:
![image](https://user-images.githubusercontent.com/26889568/121650687-092f6a80-ca57-11eb-8262-490a7fd8b197.png)
Continue Watching on TV Show:
![image](https://user-images.githubusercontent.com/26889568/121650744-1e0bfe00-ca57-11eb-99ed-4c28b98589a5.png)


TMDB Helper Widget Screencaps:

Movie Screencap:
![image](https://user-images.githubusercontent.com/26889568/121651301-b5715100-ca57-11eb-95a2-29418396a5f7.png)
TV Show Screencap:
![image](https://user-images.githubusercontent.com/26889568/121651414-d5087980-ca57-11eb-925f-28cffb5b600a.png)


YouTube Screencaps (Has somewhat similar issue):

Sub video:
![image](https://user-images.githubusercontent.com/26889568/121651121-82c75880-ca57-11eb-9990-931f7ef53e69.png)

**Comment by TheFantasticLoki** [comment]
Inside Season Select Screencap:
![image](https://user-images.githubusercontent.com/26889568/121652066-85767d80-ca58-11eb-9d01-a29dce6f3436.png)
Inside Episode Select Screencap:
![image](https://user-images.githubusercontent.com/26889568/121652017-798abb80-ca58-11eb-8ca1-b6f4a36ee535.png)

**Comment by TheFantasticLoki** [comment]
I hope those are the screencaps you were asking for

**Comment by TheFantasticLoki** [comment]
If there is any other info I can provide in the next 10-15 minutes before I go to bed please ask now. I want to give as much info for you so this can get solved fast.

**Comment by inb4after** [comment]
> If there is any other info I can provide in the next 10-15 minutes before I go to bed please ask now. I want to give as much info for you so this can get solved fast.

This is fine, thanks. 

The Container./ListItem.DBType is incorrect, it's either Container.ListItem.DBType or ListItem.DBType, but I only needed to confirm you have the same issue, and I can see this from Container.ListItem.DBType.

**Comment by inb4after** [comment]
I have opened a new issue to their Github, hopefully it will be fixed soon

 https://github.com/MrKrabat/plugin.video.crunchyroll/issues/44

**Comment by TheFantasticLoki** [comment]
Btw it's very likely that he won't fix the issue as the addon had a DMCA takedown a while back so support will likely be lacking tho I hope for the alternative.

**Comment by TheFantasticLoki** [comment]
Fixed the issue for Queue items with [This](https://github.com/MrKrabat/plugin.video.crunchyroll/issues/44#issuecomment-859925586)

**Comment by TheFantasticLoki** [comment]
Not entirely sure how to proceed with fixing it for series or season view. If you could give me some direction I can probably get most of this fixed and attached to a new pull request by end of day.

**Comment by TheFantasticLoki** [comment]
Also switching it to episode avoids not being able to play from queue listing as the extendedinfo page breaks on tvshow but on episode it doesn't show the plot on the home page and only in extendedinfo page. is there a way I can fix this with a simple code adjustment on my end so as to not affect everyones view.

**Comment by TheFantasticLoki** [comment]
Fixed it not showing for series or seasons. Tho rating still doesn't work for them.

**Comment by TheFantasticLoki** [comment]
Also Music section type items show no info or correct context menu's but I think it is missing most needed files outright.

**Comment by TheFantasticLoki** [comment]
Also how can I check keybinds and such? Possibly move the hub sidebar to the other side to prevent conflict with main sidebar when using a mouse?

**Comment by TheFantasticLoki** [comment]
Also because of broken context menus I can't rate music through OSD or files directory. This is all music that is on device not through addon.

**Comment by TheFantasticLoki** [comment]
#123 Might as well while I'm at it. not quite right but it was working when I submitted the pull request now it's not. Still working on this.

**Comment by TheFantasticLoki** [comment]
it's odd cause without my additions it doesn't load pictures at all, but with it shows either the update notice or black screen with both slideshow & Visualization enabled, but with both off it shows pictures fine.

**Comment by inb4after** [comment]
Fixed with https://github.com/MrKrabat/plugin.video.crunchyroll/commit/62196a8fbc14d77e36bf4e87d522414a89825ab0
