### ISSUE TITLE
Skin Helper Service makes kodi crash when you try to close the application

### ISSUE THREAD

**Issue by simon-verbois** [SerpentDrago/skin.auramod#125]
Hey everyone,

I use Auramod since I switched to 19.1, but it seems that the skin helper service crashes kodi when you try to close it via the menu (by default)
Is there a solution ?

Thanks you,
Simon

**Comment by jojobrogess** [comment]
What version is it? 
Auramod version? 

And can you post a video of it happening? So we can better understand this. 

Do the logs say anything?

**Comment by jojobrogess** [comment]
Wait are you referring to shutting down Kodi via the power menu with the "exit" button?

**Comment by Goldenfreddy0703** [comment]
oh hey, i had this happen to me and its defiantly a Skin Helper Service issue cause Skin Helper Service does not cooperate when its been updating or if changes were made and yeah, that bug happens on windows all the time. Best thing i would do is uninstall it and wait for a fix or report this as an issue on Skin Helper Service. I had this bug happen a few months back especially on different skins.

To uninstall it, go to the appdata folder for kodi then go to addons and find script.skin.helper.service and just delete that folder and it should not crash anymore.

**Comment by SerpentDrago** [comment]
This is just something that happens on windows with skin helper service it doesn't shut down properly and your generally going to have to force close kodi , as it will not exit properly . its not a skin issue , its just skin helper service to busy in the background . it won't typically hurt anything though ! : )  give it a little bit then force close it via task manager , all is good . this generally wont' happen on android as much . but even if it does its not a big deal as long as you give it a little bit of time first .

**Comment by Goldenfreddy0703** [comment]
> 
> 
> This is just something that happens on windows with skin helper service it doesn't shut down properly and your generally going to have to force close kodi , as it will not exit properly . its not a skin issue , its just skin helper service to busy in the background . it won't typically hurt anything though ! : ) give it a little bit then force close it via task manager , all is good . this generally wont' happen on android as much . but even if it does its not a big deal as long as you give it a little bit of time first .

Thats odd for me cause when i was testing a clean installation of kodi and i install skin helper service as my number one priority. it just crashed instantly when the addon gets installed.
