### ISSUE TITLE
Season Posters TV Shows

### ISSUE THREAD

**Issue by Martybob20** [SerpentDrago/skin.auramod#13]
As per title season posters will not display on any show in library. Everything else working fine thanks for your work

**Comment by SerpentDrago** [comment]
to confirm you mean from the kodi library ? What views . 


Please give your exact path where its not working and example 

Seems to work for addons , but not library sections
I have replicated it from a library section , Can you confirm working for addons but not actual kodi library ? and only on some views . Seems almost all the views when browsing actual library content are screwed up 

![image](https://user-images.githubusercontent.com/21133858/112192529-68f74180-8bdd-11eb-9a0d-6c515c688602.png)

**Comment by Martybob20** [comment]
Yes i think it is a library issue as you have said rightly they do show up within video addons. Seems to affecting be the showcase view more than any other. There was a similar issue with the official aura skin if thats any help
https://forum.kodi.tv/showthread.php?tid=328558&page=142

**Comment by SerpentDrago** [comment]
> Yes i think it is a library issue as you have said rightly they do show up within video addons. Seems to affecting be the showcase view more than any other. There was a similar issue with the official aura skin if thats any help
> https://forum.kodi.tv/showthread.php?tid=328558&page=142


YES that helps A LOT , Thank you so much , Kcooks github matrix version of auramod is going to help sooooo much .

**Comment by Martybob20** [comment]
Good work mate

**Comment by SerpentDrago** [comment]
Note this also effects widgets pointed to local library stuff.

**Comment by inb4after** [comment]
It should now be fixed. Please test the [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing) to see if this resolves your issues, and doesn't create further issues.

**Comment by inb4after** [comment]
@Martybob20

**Comment by abbaskip** [comment]
> It should now be fixed. Please test the [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing) to see if this resolves your issues, and doesn't create further issues.

Can confirm this works for me now in any poster view for both local library TV Shows and Seasons.

**Comment by SerpentDrago** [comment]
This should be fixed in Latest Matrix version 1.0.4  (now even with testing branch ) 

Closing issue
