### ISSUE TITLE
[BUG]Landscape artwork issue w/ watched episodes

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#14]
Unwatched episodes view types including widgets correctly display landscape artwork.

FYI - I have Kodi set to hide episode thumbs until the episode is watched using the below setting
`Settings >Media Settings > Videos > Show information for unwatched items - 'Episode thumbs' is unselected `

Landscape artwork displayed correctly for unwatched episode.
![Kodi_20210323_190448](https://user-images.githubusercontent.com/54026944/112203704-b76f0500-8c0a-11eb-9f67-8822bcba615a.png)

The issue starts when the episode is watched but there isn't a episode thumb available, instead of continuing to use the landscape artwork until (when or if) an episode thumb is available it displays the episode poster artwork which doesn't fit in landscape.

Poster artwork displayed when episode thumb artwork is unavailable.
![Kodi_20210323_190458](https://user-images.githubusercontent.com/54026944/112203742-bdfd7c80-8c0a-11eb-9bbd-bd2fd553a5d0.png)

If there is an episode thumb available after the episode has been watched there is no issue.

Episode thumb artwork displayed when available.
![Kodi_20210323_190507](https://user-images.githubusercontent.com/54026944/112203828-d9688780-8c0a-11eb-87c5-9aa38e989dd4.png)
 
Kodi: 19.0 Matrix
Seren: 2.0.17+Matrix. 1
Auramod: 1.0.3.3

**Comment by SerpentDrago** [comment]
Ok so the "issue" your saying is that if a episode is watched , AND there is no episode thumb available , then it displays poster artwork stretched  out instead of displaying generic Show Landscape. 

BUT if the episode is both Unwatched And there is no episode thumb , then it correctly displays Show's landscape artwork ? 

BUT all that above only happens if you have hide spoilers enabled ... uggg

Fun stuff , This prob won't be looked at for awhile sorry , i'm already over my head trying to fix the rest of the skin . 

Thanks for the detailed bug report .

**Comment by SerpentDrago** [comment]
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/446

This seems to be the same bug .. what a fucking mess

**Comment by Dealz-416LS** [comment]
> 
> 
> Ok so the "issue" your saying is that if a episode is watched , AND there is no episode thumb available , then it displays poster artwork stretched out instead of displaying generic Show Landscape.
> 
> BUT if the episode is both Unwatched And there is no episode thumb , then it correctly displays Show's landscape artwork ?
> 
> BUT all that above only happens if you have hide spoilers enabled ... uggg
> 
> Fun stuff , This prob won't be looked at for awhile sorry , i'm already over my head trying to fix the rest of the skin .
> 
> Thanks for the detailed bug report .

Yes, watched + no episode thumb available = centre of poster artwork used as landscape artwork. 

Notice, this is how the poster looks (below), you can see in the (2nd screenshot above) that the landscape image is just the centre section of the poster artwork, it's not the poster artwork stretched.
![56fb7d94](https://user-images.githubusercontent.com/54026944/112236183-d5069380-8c37-11eb-9548-d1226150580e.jpg)

If the show's landscape artwork (1st screenshot above) which is already being used when unwatched + no episode thumb, was also used when watched + no episode thumb there wouldn't be an issue.

Yes, unwatched + no episode thumb = correctly displaying show's landscape artwork and yes this is because i have hide spoilers for episode thumbs enabled.

I understand, I just wanted to bring it to your attention so it can hopefully be fixed at some point.

I am not sure that is the same issue because my landscape artwork is working/being used, the skin just isn't using it once an episode is watched w/ no episode thumb, I'll have another look at it.

**Comment by inb4after** [comment]
This should be fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).

Please report any further issues or bugs caused by this update.

**Comment by Dealz-416LS** [comment]
@SerpentDrago @inb4after 

This issue may now be fixed on the [Testing Branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing)

I'll confirm for sure later today.

**Comment by SerpentDrago** [comment]
> @SerpentDrago @inb4after
> 
> This issue may now be fixed on the [Testing Branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing)
> 
> I'll confirm for sure later today.

Nice , yeh seems fixing the few variable switching issues (the artwork posters and widget aspect ) fixed lots of other things . good to hear  !@

**Comment by Dealz-416LS** [comment]
Episodes that are marked as watched with no episode thumbs available are now displaying artwork correctly. 

Before the fix
![Kodi_20210323_190458](https://user-images.githubusercontent.com/54026944/113459916-e5c0c180-940e-11eb-9d79-efcd59308c92.png)

With the fix
![Kodi_20210402_160632](https://user-images.githubusercontent.com/54026944/113459928-ece7cf80-940e-11eb-9241-7d43aa6e94fb.png)

I have noticed nothing broken as a side-effect of this fix. 

Unaired/unwatched items still display artwork correctly with the fix.
![Kodi_20210403_000431](https://user-images.githubusercontent.com/54026944/113460310-34229000-9410-11eb-8c2c-d50533f6b40e.png)

Episodes marked as watched  that do have episode thumbs available are still displayed correctly with the fix.
![Kodi_20210323_190507](https://user-images.githubusercontent.com/54026944/112203828-d9688780-8c0a-11eb-87c5-9aa38e989dd4.png)

Thank you for fixing this!

**Comment by SerpentDrago** [comment]
This is great to hear ! , in next few days i'll start merging all the fix's into Matrix branch , and closeing any related issues !
