### ISSUE TITLE
Translation season and state

### ISSUE THREAD

**Issue by wsx79** [SerpentDrago/skin.auramod#145]
Where is any possibility to Translate this items?

![Immagine](https://user-images.githubusercontent.com/68690475/122670942-b8411400-d1c4-11eb-9c2b-63f36c6608db.jpg)

I think it's lacate here
https://github.com/SerpentDrago/skin.auramod/blob/5475af908fc20be7bdb68fc50b1768a3342f3cea/1080i/Includes_Labels.xml#L742
and
https://github.com/SerpentDrago/skin.auramod/blob/5475af908fc20be7bdb68fc50b1768a3342f3cea/1080i/Includes_Labels.xml#L746

But I think it's take form another location url and we need to add more data per can tranlate it.

Edit.
Season found here
https://github.com/SerpentDrago/skin.auramod/blob/5475af908fc20be7bdb68fc50b1768a3342f3cea/1080i/Includes_Labels.xml#L760

**Comment by wsx79** [comment]
The "seasons"  is done.
For TV Series I try to add a variable like this

Include Object 1032 line
```
   <variable name="Label_Info_NextAired_Status">
        <value condition="!String.IsEmpty(Window(Home).Property(TMDBHelper.ListItem.Status))">$INFO[Window(Home).Property(TMDBHelper.ListItem.Status)]</value>
    </variable>
<variable name="TranslationTMDBStatus">
 <value condition="String.IsEqual(Window(Home).Property(TMDBHelper.ListItem.Status),Ended)">Terminata</value>
```

But I need help for complete. It's in testing

**Comment by inb4after** [comment]
I've added localization for all the missing strings. Skin should be 100% localized now.

As for ListItem.Status (from addon or TMDBHelper) that depends on the language you set in that addon (InfoLabel is set by addon), the skin cannot control this, and adding a variable is not a good workaround for that.

**Comment by inb4after** [comment]
@wsx79 New localization strings added, needs translating in Italian strings.po. It might be the last one!
