### ISSUE TITLE
Request - Categories label 

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#15]
Would it be possible to remove the "categories" label for small widget bar? I believe we spoke about this sometime ago.

**Comment by SerpentDrago** [comment]
screen shot of what your talking about , the skin has a remove categories widget label setting .

**Comment by SerpentDrago** [comment]
Ok so the issue is when you hide "categories" from the categories  widget label via skin settings  , its only hiding it  for med and large and not small . noted
