### ISSUE TITLE
[BUG] RT consensus is missing after localization updates

### ISSUE THREAD

**Issue by inb4after** [SerpentDrago/skin.auramod#155]
![kodi](https://user-images.githubusercontent.com/75323492/122802120-e30e9380-d2bc-11eb-9566-84024be89e03.jpg)

![chrome](https://user-images.githubusercontent.com/75323492/122802241-0d605100-d2bd-11eb-85b7-ae22d465f5ac.png)

**Comment by wsx79** [comment]
It was broken before commit localization update

**Comment by inb4after** [comment]
> 
> 
> It was broken before commit localization update

v1.0.35 works, but v1.0.36 doesn't, it was definitely some localization string that was edited into a condition

**Comment by inb4after** [comment]
Fixed in latest commit
