### ISSUE TITLE
Is this a bug? Trailer OSD mouse movement brings up Cast & More

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#159]
**CAUTION** Audio is loud af, sorry!!

After selecting the trailer button on Netflix homestyle screen, if you move your mouse around prior to selecting `Fullscreen` or `Stop` it looks like the `Cast & More` Window pops up.

I usually use the arrow keys on my keyboard to navigate throughout kodi, but sometimes I forget and use my mouse. 
It seems to work as it should with keyboard navigation.

This happens with movies and tv shows. Example is movie:

https://user-images.githubusercontent.com/17692472/122884770-50d5b200-d2f3-11eb-9d7b-100b503848f7.mp4

**PRIOR** to selecting `Fullscreen` or `Stop`, move your mouse around and `Cast & More` window should pop up.

Moving your mouse around the **outside part** of the screen can cause the window to disappear.

From there if you select `Fullscreen` it brings up the traditional video osd and the `Cast & More` window doesn't come up if you move your mouse around within it.

**Comment by inb4after** [comment]
AuraMOD was never designed for mouse, which is why a lot of bugs need fixing here. Will get to it soon.

Also remind me to hide studio logo while trailer is playing.

**Comment by SerpentDrago** [comment]
Yeh stop using mouse. I'm tempted to re add the code that disables the mouse on skin startup if i keep getting bug reports about mouse usage lol.

Kodi in general is really really not designed for a mouse. And auramod skin definitely is not
