### ISSUE TITLE
LoveFilm View Mode Ratings gets Cutoff at Bottom

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#162]
Movie
![2021-06-22 04_27_07-Greenshot](https://user-images.githubusercontent.com/17692472/122917057-745c2500-d312-11eb-807e-daaa354286a3.png)
TV Show
![2021-06-22 04_28_15-Greenshot](https://user-images.githubusercontent.com/17692472/122917066-7625e880-d312-11eb-911b-364824039366.png)

**Comment by inb4after** [comment]
Fixed in latest commit

**Comment by SerpentDrago** [comment]
someone uses that view ? lol :)
