### ISSUE TITLE
Hide Studio Logo in Trailer OSD

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#165]
Issue was brought up in https://github.com/SerpentDrago/skin.auramod/issues/159#issuecomment-865923668 by @inb4after 
>
> 
> Also remind me to hide studio logo while trailer is playing.

![2021-06-22 15_26_52-Greenshot](https://user-images.githubusercontent.com/17692472/123007664-63d99800-d36e-11eb-8c2a-d21373e4f16b.png)

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.1.4
