### ISSUE TITLE
Netflix Home Style Widget Settings Question

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#166]
Technically I use the `Mixed Netflix Mixed Home Layout`.
Do the `Disable Fixed Focus`, `Enable Widget Info Slide`, `Enable Widget Showcase Overlay`, `Enable Showcase auto-hide` options inside of the Menu's & Widgets editor work when using Netflix Home Style? They seem to not do anything:
Or do I need to use a certain widget style?

![2021-06-22 18_34_21-Greenshot](https://user-images.githubusercontent.com/17692472/123037672-e3ce2500-d3a3-11eb-980a-cfcb6337b961.png)

https://user-images.githubusercontent.com/17692472/123037679-e597e880-d3a3-11eb-9ceb-1cdca06801d7.mp4

https://user-images.githubusercontent.com/17692472/123037684-e6c91580-d3a3-11eb-8f3b-69604dc95f0f.mp4

They seem to work when using `Aura Home Layout`:

https://user-images.githubusercontent.com/17692472/123038952-255fcf80-d3a6-11eb-87cf-ccbf946cdb84.mp4

**Comment by inb4after** [comment]
Yes, these are for Aura Home only.

**Comment by jojobrogess** [comment]
So what _does_ Netflix Mixed Home Layout mix? I thought it mixed Aura and Netflix Home Style.

Is there any way of removing them as options from the Menu's & Widgets editor if you're **not** under Aura Home style?  
Or at least adding a disclaimer, because I would care to guess it probably confuses a lot of people, or at least new comers like me.

**Comment by SerpentDrago** [comment]
I'm tempted to just remove all the weird netflix home styles except netflix home and aurahome honestly . its just to much

**Comment by Nuklear92** [comment]
> I'm tempted to just remove all the weird netflix home styles except netflix home and aurahome honestly . its just to much 

I think that would be a great idea if you ask me and that also take off some weight from the skin itself and perhaps becomes more lighter. Focusing on the Netflix home layout it could get some UI modernization and refinements in some areas I've noticed while using it. Perhaps moving forward in the future this could be an area to revisit by your development, of course that's dependent in which of the two home layouts you're actually more focused on working normally if it's the Aura Home or Netflix Home. Personally, I think most users that use this skin will always go for the Netflix layout as it's very unique and no other skins are heavily invested in that UI as much. 🤔

**Comment by SerpentDrago** [comment]
I actually hate netflix home layout also but i get why some like it , i use Aura Home with netflix showcase and info .  Bingie actually has the best implemented netflix look .
