### ISSUE TITLE
Aura Home Layout bugs out when you have no Submenu's

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#167]
I have no Spotlights or Hubs running.

https://user-images.githubusercontent.com/17692472/123039241-a0c18100-d3a6-11eb-912e-bd09f6565922.mp4

A Cleaner look of the aftermath:
No Submenu's enabled

https://user-images.githubusercontent.com/17692472/123039244-a323db00-d3a6-11eb-9fda-7b6125e07fac.mp4

Widget properties for that top widget:
Skin.helper.widgets recommended movies
 
https://user-images.githubusercontent.com/17692472/123039247-a4550800-d3a6-11eb-8c10-93b51e2fc668.mp4

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.1.0
