### ISSUE TITLE
Skin.AruaMod/extras/weather.py uses xbmc.translatePath 

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#169]
xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.

https://github.com/SerpentDrago/skin.auramod/blob/54b021f51aa77c8f129f3d269fdcf8e1f1a2a3d9/extras/weather.py#L8

I can't believe I just now caught this...

**Comment by inb4after** [comment]
Fixed in latest commit
