### ISSUE TITLE
TMDB Ratings for a lot of TV show episodes show up as 0

### ISSUE THREAD

**Issue by xyzfre** [SerpentDrago/skin.auramod#17]
Been noticing a lot of TV show episodes ONLY the TMDB ratings show up as zero specially with newer episodes but also on older ones as well,, I compared The same episodes on 18.9 and the ratings are there and show up correct ,was wondering what could be causing this issue would really appreciate if you could look into this I know it’s not a major issue but that’s One of AuraMod’s Great looking features and for those who like seeing ratings like me,, thank you for all your hard work SerpentDrago,,Here’s a quick video ,, still working on my build still have to add a lot of icons

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/112388960-53ac1100-8cca-11eb-914c-eae2b9cbfb8f.MOV

**Comment by xyzfre** [comment]
My apologies for the video not the best

https://user-images.githubusercontent.com/49699869/112402500-08eac300-8ce3-11eb-88d9-a5a3b277ca48.MOV

**Comment by SerpentDrago** [comment]
I'll have to confirm this , ratings can come either from meta data handler / skin helper    or tmdb helper 

thanks for the report

**Comment by xyzfre** [comment]
Thank you for keeping up with the skin and the hard work that goes into it✊🏼 Been using it on a daily basis it was the only thing holding me back from updating to 19 so will definitely keep you posted on any other glitches

**Comment by SerpentDrago** [comment]
@xyzfre do you have this issue on the TMDB ratings and artwork  branch ?  (make sure tmdb helper is configured with OMDB api key and you have its service monitor enabled , both in tmdb helper settings and in skin settings

**Comment by inb4after** [comment]
Closing stale issue, reopen if needed.
