### ISSUE TITLE
[BUG] Parent show tagline appears over episode numbering for episode items

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#180]
How it should look:
Poster Media Info view mode

![Inked2021-06-27 23_07_00-Greenshot_LI](https://user-images.githubusercontent.com/17692472/123588982-6ccacf00-d79d-11eb-87e7-33b2ffef80a7.jpg)

This is Landscape showcase:
There is no episode identifier anywhere inside this view mode

![Inked2021-06-27 23_04_49-Greenshot_LI](https://user-images.githubusercontent.com/17692472/123588975-6a687500-d79d-11eb-9544-05d9886bd033.jpg)

A video of the bug in action:

https://user-images.githubusercontent.com/17692472/123588567-cc74aa80-d79c-11eb-9cdd-cda21a578d77.mp4

Panel Showcase view mode:
There is no episode identifier anywhere inside this view mode

![Inked2021-06-27 23_22_14-Greenshot_LI](https://user-images.githubusercontent.com/17692472/123589800-99cbb180-d79e-11eb-82a2-f247d584d5b3.jpg)

Showcase view mode:
There is no episode identifier anywhere inside this view mode

![Inked2021-06-27 23_07_26-Greenshot_LI](https://user-images.githubusercontent.com/17692472/123588985-6d636580-d79d-11eb-97c3-19fe808a036e.jpg)

**Comment by jojobrogess** [comment]
There also looks to be a discrepancy with episode numbering styles:
Both `S1:E1` and `1x01` are being used.

Episode List:
![Inked2021-06-27 23_28_10-Greenshot_LI](https://user-images.githubusercontent.com/17692472/123591044-5d995080-d7a0-11eb-9f9a-5f9570c3636e.jpg)

List:
![Inked2021-06-27 23_28_26-Greenshot_LI](https://user-images.githubusercontent.com/17692472/123591053-60944100-d7a0-11eb-8212-26faf598876e.jpg)

Media Info:
![Inked2021-06-27 23_28_36-Greenshot_LI](https://user-images.githubusercontent.com/17692472/123591068-638f3180-d7a0-11eb-9b9e-e655550a03d1.jpg)

Info List:
![Inked2021-06-27 23_28_49-Greenshot_LI](https://user-images.githubusercontent.com/17692472/123591076-64c05e80-d7a0-11eb-8495-1a0a4c83861e.jpg)

Landscape Wall:

![Inked2021-06-27 23_40_16-Greenshot_LI](https://user-images.githubusercontent.com/17692472/123591738-38f1a880-d7a1-11eb-9368-8ec22c7e9918.jpg)

**Comment by SerpentDrago** [comment]
"There also looks to be a discrepancy with episode numbering styles:
Both S1:E1 and 1x01 are being used."

Nope thats coming from whatever addon your using to display the content . its appending that shit to the listitem.title . most good addons either dont' do this or have a option to remove this .  The skin does NOT do this

**Comment by SerpentDrago** [comment]
Using Seren > 
![image](https://user-images.githubusercontent.com/21133858/123647021-bba45300-d7f5-11eb-9d8f-dffe8d03eaec.png)

![image](https://user-images.githubusercontent.com/21133858/123646632-636d5100-d7f5-11eb-873e-32be7a1b1cc4.png)
![image](https://user-images.githubusercontent.com/21133858/123646737-797b1180-d7f5-11eb-986b-872dd8c9bf2e.png)
![image](https://user-images.githubusercontent.com/21133858/123646800-87c92d80-d7f5-11eb-8490-f6ee4dfe1098.png)

**Comment by SerpentDrago** [comment]
as far as the "its good to be bad" tagline overtop of where the SxxExx should be , that will need to be looked at . 

You need to tell us what addon / from what source your displaying content from . for us to replicate it .   (seren / venom / fen / library data / tmdb helper ? ? )

**Comment by jojobrogess** [comment]
All my video files are real library data files being displayed with default skin widgets, skinhelper widgets, or autowidgets.
But I haven't used autowidgets for Tv Shows yet since I don't have enough to warrant the advanced playlist features.

@SerpentDrago 
> Nope thats coming from whatever addon your using to display the content . its appending that shit to the listitem.title . most good addons either dont' do this or have a option to remove this . The skin does NOT do this


So since I don't point directly to or through an addon, my guess would be this is Themoviedbhelper supplied information? 

I pretty much never use addons directly to search for or display content, since they will display content that I do not have and wouldn't be able to watch. The "deepest" I go is to use the Cast & More section to find related content and then add those items to a trakt list.


************************************************************************************************************************************

Sorry for forgetting to say where they were pointed to. This is pointed to Aurmod Playlist Recently Played TV Shows

![2021-06-28 10_34_15-Greenshot](https://user-images.githubusercontent.com/17692472/123679543-720b3680-d7fc-11eb-9f14-c51d06878644.png)

Netflix Mixed Home Style > auramod widget > information page > episodes >

https://user-images.githubusercontent.com/17692472/123677683-46874c80-d7fa-11eb-9347-0efdc59e1407.mp4

************************************************************************************************************************************
This is pointed to skin helper widgets Recommended TV Shows

![2021-06-28 10_54_39-Greenshot](https://user-images.githubusercontent.com/17692472/123682103-6cfbb680-d7ff-11eb-9dd5-e4bc1d82e92d.png)

Netflix Mixed Home Style > skin helper widget > information page > episodes >

https://user-images.githubusercontent.com/17692472/123682114-708f3d80-d7ff-11eb-84ce-a7a150d0256c.mp4

************************************************************************************************************************************

Uh-oh I broke something...
Things look to be working correctly here:

![2021-06-28 10_35_28-Greenshot](https://user-images.githubusercontent.com/17692472/123680874-075afa80-d7fe-11eb-96e7-ded75e0d8641.png)

Netflix Mixed Home Style > direct smb library widget > information page > episodes >

https://user-images.githubusercontent.com/17692472/123680894-0b871800-d7fe-11eb-80df-33fa037b1527.mp4

But it's broken here:

https://user-images.githubusercontent.com/17692472/123686817-1002ff00-d805-11eb-9e6a-2fd99b59eacb.mp4


Both of those files are located in the same directory, both being display within the same widget on the home page.

**Comment by inb4after** [comment]
Fixed in latest commit

**Comment by SerpentDrago** [comment]
@inb4after what would be causing his library files to have episode numbering appended to list item title? He is using./ browseing though real files? I know auramod doesn't do this to anything i scan into library.

**Comment by SerpentDrago** [comment]
> All my video files are real library data files being displayed with default skin widgets, skinhelper widgets, or autowidgets.
> But I haven't used autowidgets for Tv Shows yet since I don't have enough to warrant the advanced playlist features.
> 
> @SerpentDrago
> 
> > Nope thats coming from whatever addon your using to display the content . its appending that shit to the listitem.title . most good addons either dont' do this or have a option to remove this . The skin does NOT do this
> 
> So since I don't point directly to or through an addon, my guess would be this is Themoviedbhelper supplied information?
> 
> I pretty much never use addons directly to search for or display content, since they will display content that I do not have and wouldn't be able to watch. The "deepest" I go is to use the Cast & More section to find related content and then add those items to a trakt list.
> 
> Sorry for forgetting to say where they were pointed to. This is pointed to Aurmod Playlist Recently Played TV Shows
> 
> ![2021-06-28 10_34_15-Greenshot](https://user-images.githubusercontent.com/17692472/123679543-720b3680-d7fc-11eb-9f14-c51d06878644.png)
> 
> Netflix Mixed Home Style > auramod widget > information page > episodes >
> 
>  bandicam.2021-06-28.10-18-21-802.mp4 
> This is pointed to skin helper widgets Recommended TV Shows
> 
> ![2021-06-28 10_54_39-Greenshot](https://user-images.githubusercontent.com/17692472/123682103-6cfbb680-d7ff-11eb-9dd5-e4bc1d82e92d.png)
> 
> Netflix Mixed Home Style > skin helper widget > information page > episodes >
> 
>  bandicam.2021-06-28.10-55-06-993.mp4 
> Uh-oh I broke something...
> Things look to be working correctly here:
> 
> ![2021-06-28 10_35_28-Greenshot](https://user-images.githubusercontent.com/17692472/123680874-075afa80-d7fe-11eb-96e7-ded75e0d8641.png)
> 
> Netflix Mixed Home Style > direct smb library widget > information page > episodes >
> 
>  bandicam.2021-06-28.10-37-42-654.mp4 
> But it's broken here:
> 
>  bandicam.2021-06-28.11-35-22-060.mp4 
> Both of those files are located in the same directory, both being display within the same widget on the home page.

I have no idea. It's got to be when your scraping the content into library it's adding it. Do the actual filenames have it appended? We need more info on how the files look and your library scraper settings

**Comment by inb4after** [comment]
It's probably the scraper, it's very inconsistent with some shows having `01. Episode Title` label and others having `1x01. Episode Title`.

We can use `ListItem.Title` instead of `ListItem.Label` to solve these issues, but first this will have to be in a separate issue thread.

**Comment by jojobrogess** [comment]
SerpentDrago:
> I have no idea. It's got to be when your scraping the content into library it's adding it. Do the actual filenames have it appended? We need more info on how the files look and your library scraper settings

Yes, all of my video files have been put through filebot, so everything is the same format.

************************************************************************************************************************************

movies:
Using the Universal Movie Scraper.
Example: C:\Movies\Avatar (2009)\Avatar (2009).mp4
![2021-06-30 22_56_05-Greenshot](https://user-images.githubusercontent.com/17692472/124073269-cbd75080-d9f6-11eb-9d66-f5d5388f15ef.png)
![2021-06-30 22_47_52-Greenshot](https://user-images.githubusercontent.com/17692472/124072354-86665380-d9f5-11eb-8612-0cc537862b4a.png)
![2021-06-30 22_48_39-Greenshot](https://user-images.githubusercontent.com/17692472/124072356-86feea00-d9f5-11eb-9b0c-37a6fb69661a.png)
![2021-06-30 22_48_44-Greenshot](https://user-images.githubusercontent.com/17692472/124072358-88301700-d9f5-11eb-9199-407373031db4.png)
![2021-06-30 22_48_47-Greenshot](https://user-images.githubusercontent.com/17692472/124072360-88c8ad80-d9f5-11eb-9767-acf422d1dbb6.png)
![2021-06-30 22_48_50-Greenshot](https://user-images.githubusercontent.com/17692472/124072377-8bc39e00-d9f5-11eb-8f56-a829d30aab6d.png)
![2021-06-30 22_48_53-Greenshot](https://user-images.githubusercontent.com/17692472/124072412-97af6000-d9f5-11eb-9de8-3dfa48a2439a.png)
![2021-06-30 22_49_03-Greenshot](https://user-images.githubusercontent.com/17692472/124072417-98e08d00-d9f5-11eb-82df-14a34d07523d.png)
![2021-06-30 22_49_15-Greenshot](https://user-images.githubusercontent.com/17692472/124072423-9a11ba00-d9f5-11eb-8505-39d658663554.png)


************************************************************************************************************************************


tv shows:
Using the TMDb TV ShowsScraper
Example: C:\TV Shows\Firefly (2002)\Season 1\Firefly S01E01 Serenity.mp4
![2021-06-30 22_31_06-Greenshot](https://user-images.githubusercontent.com/17692472/124071028-9e3cd800-d9f3-11eb-870a-06311543221d.png)
![2021-06-30 22_46_44-Greenshot](https://user-images.githubusercontent.com/17692472/124072572-c4637780-d9f5-11eb-8ada-ad688c5f04c5.png)
![2021-06-30 22_46_49-Greenshot](https://user-images.githubusercontent.com/17692472/124072575-c594a480-d9f5-11eb-8cbb-64d89bb98902.png)
![2021-06-30 22_46_56-Greenshot](https://user-images.githubusercontent.com/17692472/124072578-c62d3b00-d9f5-11eb-8c88-57e9eb107492.png)

************************************************************************************************************************************

  
But it looks like it's been fixed in that commit and without needing a library "deep clean", although I should probably do one:

![2021-06-30 22_43_57-Greenshot](https://user-images.githubusercontent.com/17692472/124071790-c24ce900-d9f4-11eb-9bb1-7c5108d0d9cf.png)

![2021-06-30 22_39_55-Greenshot](https://user-images.githubusercontent.com/17692472/124071803-c7119d00-d9f4-11eb-8ca0-a3079eaa5870.png)

************************************************************************************************************************************

> We can use `ListItem.Title` instead of `ListItem.Label` to solve these issues, but first this will have to be in a separate issue thread.

@inb4after do you still want me to open another issue for this?

**Comment by inb4after** [comment]
@jojobrogess Yes, as it requires further discussion.

**Comment by SerpentDrago** [comment]
you should remove the Prefix for MPAA rating
![image](https://user-images.githubusercontent.com/21133858/124151320-6cae2600-da60-11eb-80d1-fce44b602f6c.png)

**Comment by SerpentDrago** [comment]
you should also enter your fanart key , always try to use your own keys where you can to prevent throttling . and grab as much info as you can . if you can gather enough info built in you can disable the skins doing so via tmdb helper and improve your speed
