### ISSUE TITLE
Error choosing a default widget in Hubs & Spotlight section

### ISSUE THREAD

**Issue by gtkingbuild** [SerpentDrago/skin.auramod#184]
When choosing a default widget within the Hubs & Spotlight section, the text of the widget selection does not appear correctly

https://user-images.githubusercontent.com/68242121/124358199-83e74200-dc1f-11eb-89a5-61fc2b79a40a.mp4

**Comment by inb4after** [comment]
This is not a bug as the label needs to have this variable inside to work properly.

**Comment by SerpentDrago** [comment]
Correct it should also be known this is a Seren only feature , its not going to work with other addons , that specific default widget is exclusive to seren only ! as it uses Seren "similar" feature . If you dont' use Seren addon , just ignore it
