### ISSUE TITLE
[Bug] Subtitles on a specific veiw are showing. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [SerpentDrago/skin.auramod#188]
Hey, i have noticed a bug in your skin that show subtitles in the Netflix View. 
![Auramod Subtitle Glitch](https://user-images.githubusercontent.com/62456796/125138199-331e9000-e0dc-11eb-93dc-9dfb754ec463.PNG)
Steps to reproduce: 
1. If you have Seren, play a movie with subtitles
2. Keep the movie playing and then press the Tab Key
3. When on Seren go to movies > most popular. 
4. Switch viewmode to Poster Showcase. 
5. Notice the bug when subtitles are playing in the front of the veiwmode. 

I hope this helps, if you need more context, i will show inb4after on discord about this soon.

**Comment by SerpentDrago** [comment]
Thanks  for the report . note its Even easier to reproduce , and it has nothing to do with seren . It effects' anything. 

1. Play a video , have subtitles enabled and go to a part with dialog 
2. Use tab or back so video continues playing in background (make sure you have skin settings enabled to allow video in background
3. Use Showcase (poster) / Landscape Showcase / Panel showcase views . you will notice on top of video in background . It also plays the video in the Top right where  fanart or trailers would typically be shown . and fresh subtitles being drawn on top centered with it 

See video below (to get filesize down i had to convert to x265 so you will prob have to download it first and view in a local player. )

https://user-images.githubusercontent.com/21133858/125198669-e1d3e500-e230-11eb-85b2-9a60915c8dc7.mp4

**Comment by Goldenfreddy0703** [comment]
Hey thank you so much for finding this and making it easier to reproduce and even making a video on here. Your the best and I hope to see this bug get fixed someday. Again thank you and greatest skin ever.

**Comment by xyzfre** [comment]
> Thanks for the report . note its Even easier to reproduce , and it has nothing to do with seren . It effects' anything.
> 
> 1. Play a video , have subtitles enabled and go to a part with dialog
> 2. Use tab or back so video continues playing in background (make sure you have skin settings enabled to allow video in background
> 3. Use Showcase (poster) / Landscape Showcase / Panel showcase views . you will notice on top of video in background . It also plays the video in the Top right where  fanart or trailers would typically be shown . and fresh subtitles being drawn on top centered with it
> 
> See video below (to get filesize down i had to convert to x265 so you will prob have to download it first and view in a local player. )
> 
>  bu1.mp4

Never knew about this feature that there’s a setting to enable to allow video in the background ,where in settings do you enable that feature ,, and thank you for this amazing skin and all the work that has gone into it these past few months

**Comment by SerpentDrago** [comment]
![image](https://user-images.githubusercontent.com/21133858/125285762-fbd0fe80-e2e8-11eb-9fd0-bc210580c6da.png)
Skin setting . Every skin has this ability somewhere in its options . at least that i've used

**Comment by inb4after** [comment]
@Goldenfreddy0703

Change Player Settings > Language > Subtitle position on screen > Bottom of video

**Comment by Goldenfreddy0703** [comment]
Hey thank you very much for fixing this and you guys are amazing. Thank you
