### ISSUE TITLE
Question about widget settings

### ISSUE THREAD

**Issue by fairlynew** [SerpentDrago/skin.auramod#189]
Shield pro/Seren latest version/Kodi latest version

A) I have two widgets that I use the "random" setting for, one is a "trending" trakt list, the other is a "popular" trakt list. It seems that this refreshes every 60 seconds or so, so by the time I check info, or watch a trailer, the widgets are completely different. Is there a setting somewhere I'm missing for the refresh rate?

B) Is there any way to have the date up by my clock using aura style home screen with horizontal menu?

**Comment by inb4after** [comment]
Could you add screenshots of this option and where it is located, I'm not familiar with it.

There's no existing option to have the date in time+weather header with horizontal menu. I suspect it was to make space if you have a lot of menu items, but will require further testing and feedback if this can be added as a feature request.
