### ISSUE TITLE
[Bug/Question] Missing Language characters fix?

### ISSUE THREAD

**Issue by TheFantasticLoki** [SerpentDrago/skin.auramod#190]
How can I fix missing characters from other languages like japanese with your skin? I have music imported to kodi but my library features music from all over the world in several languages. Is it possible to use/add a multi language font or something to the skin such as Nato from google?

![image](https://user-images.githubusercontent.com/26889568/126055815-699112e2-5d3e-4d4d-8f84-a38c950793ad.png)
 Should be 
![image](https://user-images.githubusercontent.com/26889568/126055838-d754d0b7-56bd-4bc4-8558-94be659756d6.png)

**Comment by inb4after** [comment]
Change Interface Settings > Skin > Fonts > Arial
