### ISSUE TITLE
[Feature Request] User addable hubs

### ISSUE THREAD

**Issue by TheFantasticLoki** [SerpentDrago/skin.auramod#191]
I would like to be able to make my own hubs as they function like the main menu unlike lists and such. Also hubs are only accessible through widget assignment or with a mouse making them quite under utilized.

Menu Only accessible with mouse: 
![image](https://user-images.githubusercontent.com/26889568/126055938-1b369612-849a-4c1f-a699-36ad96df802d.png)

**Comment by SerpentDrago** [comment]
What do you mean only accessible with a mouse? Mouse should not! Be used in auramod it's unsupported.

You assign either menu item or catagory widgets to open a hub.

You need to clarify. I think your not understanding how it works. 

And there's already plenty of hubs. Use them as you want. You can edit and add / remove anything you want from any hub. You could use a movie hub for shows if wanted. It's just a name and suggestion on content but you can put anything you want.

**Comment by inb4after** [comment]
This is probably a bug, Skin Settings > Hubs & Spotlight > Enable TV/Movie Submenu on left, is not working as it used to on some Skin Settings > Home > Menu layouts, but it is working for "Vertical Full" menu layout.

**Comment by inb4after** [comment]
This functionality can be enabled for homescreen menu items using Skin Settings > Home > Customise Home Menu & Widgets > Highlight the menu item > Enable Menu on Left > Choose Menu > TV/Movie Menu.
