### ISSUE TITLE
Aura home rework latest github update overlaps small category bar with sections at top of screen

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#192]
![20210718_131253](https://user-images.githubusercontent.com/76907836/126066606-732c9683-9483-4258-a541-3b500bf0ee7a.jpg)

Using the latest update, having a small category bar, overlaps the top of the screen, like in the photo provided, please could this be looked into and fixed. Many thanks 

Kodi 19.1
Nvidia Shield Pro
Auramod home layout

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.1.1

**Comment by JFG1000** [comment]
Thanks much appreciated
