### ISSUE TITLE
Can't change Highlight color

### ISSUE THREAD

**Issue by LokyStaz** [SerpentDrago/skin.auramod#193]
I can't change Highlight colors !! (I'm on matrix 19.1 on Linux Opensuse Leap 15.3)
I always get a "colorbox script error" :
`2021-07-19 14:03:18.161 T:25645   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'PIL'
                                                   Traceback (most recent call last):
                                                     File "/home/loky/.kodi/addons/script.colorbox/default.py", line 10, in <module>
                                                       from resources.lib import Utils
                                                     File "/home/loky/.kodi/addons/script.colorbox/resources/lib/Utils.py", line 19, in <module>
                                                       from PIL import Image, ImageOps, ImageEnhance, ImageDraw, ImageStat, ImageFilter, ImageFile
                                                   ModuleNotFoundError: No module named 'PIL'
                                                   -->End of Python script error report<--`

Some people tell me to installlitebox script, so I installed it from Badaas : https://github.com/BADMS/script.litebox but doesn't change anything

**Comment by jojobrogess** [comment]
If you followed the https://github.com/SerpentDrago/skin.auramod/wiki/Install-Instructions
the colorbox script should be in `Marcelveldt's BETA repository` version 3.0.0

Give that one a try and let us know if it still throws errors.

**Comment by LokyStaz** [comment]
Yeah it's working now.... But anyway, after intensive test, I can't use that skin on my Linux computer...
I have issue with the menu... I don't know really how to explain, but it's like the menu keep the focus, so clicking on a movie poster doesn't do anything, and if I use the vertical menu, anytime I just touch the mouse the menu appear and disappear (jitter) and I can't click on poster or other stuff !!

It's crazy that I didn't found any skin that work properly on Linux Computer and all freaking skin are way to big for computer screen !! This one was nice, but yeah with my issue, it's not possible...
The only one that work great but which is ugly is the default estuary skin !!

**Comment by SerpentDrago** [comment]
Auramod doesn't support mouse usage!! Don't use mouse!. Kodi works best without mouse. Use keyboard or remote or controller. Skin is made for basic navigation (left right up down enter back) And most skins are made with the 10 ft gui rule. As they are typically used 10ft distance on a TV

**Comment by LokyStaz** [comment]
ok ok thanks!
too bad I don't have the package for controller on opensuse !!

**Comment by SerpentDrago** [comment]
Just use the keyboard

**Comment by LokyStaz** [comment]
I will try the kore android app too.
Anyway, thanks a lot for your beautiful skin !!
