### ISSUE TITLE
Any guides for this skin?

### ISSUE THREAD

**Issue by wormvortex** [SerpentDrago/skin.auramod#199]
Downloaded this skin the other day and loving it after using Titan Vanilla and previously Hybrid forever. However I'm getting confused as to what half the things are for. Mainly the Hubs. What is the purpose of them? I have widgets showing recently added episodes/new shows etc... is this similar to what the hubs do or are they for something else?

**Comment by inb4after** [comment]
No guides for options as yet, but most settings are trial and error, once you first start using most Kodi skins with this amount of options.

You can think of hubs as hiding everything until it needs to be loaded (after you click it). This speeds up the skin start-up time significantly as it's already pretty heavy. It is also useful for housing larger widgets like categories or genres.

**Comment by SerpentDrago** [comment]
hubs are basically a page of widgets that only load once you trigger the hub to load , you would link a hub to say a category widget or main menu item . then when you click that main menu item or Category widget , it would LOAD the hub and all the widgets set for it
