### ISSUE TITLE
[Bug] Seren Icons option is not working due to Seren 2.0 Realease

### ISSUE THREAD

**Issue by Goldenfreddy0703** [SerpentDrago/skin.auramod#2]
**Describe the bug**
This is not really a big deal but I would love to have the icons again from Auramod just because it suits Seren more with this skin. I love this skin so much and i wanna say thank you so much for making this skin possible with Kodi 19.

Bug is that Seren icons are not showing the Skin icons for Seren.

**To Reproduce**
1. Went to options in skin settings and went to Miscellaneous.
2. Check the Skin icons for Seren.
3. Went to the Seren addon.
4. Noticed that they did not show the Skin icons for Seren.

**Expected behavior**
To see the Skin icons for Seren.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/62456796/110483948-35ce9180-80b8-11eb-8665-51b395ce7cbe.PNG)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Firefox
 - Version: 19 Matrix

**Additional context**
I don't really have any additional context except, Is it ok to send me the seren icons png images? i want to send them to Nixgates incase he uses them for his next release soon.

**Comment by SerpentDrago** [comment]
This was always a hackjob as seren didnt' include icons itself . I'm just trying to do a bit to help make this skin work in kodi 19 . and was not the Developer of the skin Org.  If you find the fix and make a pr i'll gladly accept it . other then that your best course of action is to get icons included in seren by default . 

Any images / art auramod uses can be found in its various folders and textures files . Nothing was made unique to this skin and just came from other skins and resources .

**Comment by Goldenfreddy0703** [comment]
I did try my best to find the icons in the various folders and textures files but i could not find them sadly. If you do know where they are, it would be great to know the folder path so i can copy them and give them to Nixgates.

**Comment by SerpentDrago** [comment]
They should all be in /media/exuary/

https://github.com/SerpentDrago/skin.auramod/tree/Matrix/media/exuary

as shown starting on this line  https://github.com/SerpentDrago/skin.auramod/blob/060a3fa05179250610dc1c6719d835b2bc99d1bf/1080i/Includes_Images.xml#L8

**Comment by Goldenfreddy0703** [comment]
Hey thank you so much and this will help alot.

**Comment by SerpentDrago** [comment]
no problem i may .. may if i have time go though and fix the paths its pointing to (paths were changed  in seren 2.0 its why auramod doesn't set the icons ) 

but really seren should just include icons / images by default . its very .. bad for the skin to have to do this . 

It was requested so many times when i was helping test seren , me and sky (dev of auramod ) just added them to the skin lol .

**Comment by Goldenfreddy0703** [comment]
Hey thank you very much and your the best, this skin is the best skin i have ever encountered and i see alot of potential for this skin for my raspberry devices and other devices as well. Sure its heavy but this is the best skin ever and i hope this skin will live on in the future. Seren should have icons and i don't why its never been added in the first place. Again, thank you very much and your the best.

**Comment by Goldenfreddy0703** [comment]
Hey so my future request on seren got rejected sadly cause drinfernoo did not understand what i meant but he did say that the paths were invalid for Auramod so if you can find the right paths for seren then there is a possible chance that the icons for seren could work again. If he responds again, i will be sure to inform you.
