### ISSUE TITLE
Can't install addon from any repository

### ISSUE THREAD

**Issue by wsx79** [SerpentDrago/skin.auramod#20]
I don't have any possiblity to install addon from repository.
If I change skin I'm able to install it.
I use Skin on Android Tv device (Nvidia Shield) language Italian.

If I click in the addon to install I haven't any action.
If I click on option (in context menu) and Information also I haven't any action.

**Comment by SerpentDrago** [comment]
are you sure your using the latest version , this was fixedi think in , latest version from matrix branch #19 

Could you be more clear on your issue

**Comment by wsx79** [comment]
> 
> 
> are you sure your using the latest version , this was fixedi think in , latest version from matrix branch #19
> 
> Could you be more clear on your issue

Yes I intalled yesterday latest versione from here.
I can made you a video If can help

**Comment by inb4after** [comment]
> > 
> > 
> > are you sure your using the latest version , this was fixedi think in , latest version from matrix branch #19
> > 
> > Could you be more clear on your issue
> 
> Yes I intalled yesterday latest versione from here.
> I can made you a video If can help

Yes, please upload a video of the issue.

**Comment by wsx79** [comment]
I close the issue.
I try to reset skin and the button is now here.
Thanks for the support.
