### ISSUE TITLE
Looks like issue #26 is back for me, plus more

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#200]
This is acting similar to the first issue I submitted to this repo: https://github.com/SerpentDrago/skin.auramod/issues/26#issue-844345841

I click on `Episodes` inside of a Tv Show's information page and it seemingly sends me to it's season directory.

Tv shows > Recommended Tv Shows > Select Tv show > Episodes > Looks like it goes to the season directory.
**Video is of widget at the top of the menu.** 

https://user-images.githubusercontent.com/17692472/127085939-dfcbdd65-cd8f-44d0-a063-e17b0c03c800.mp4

Widget is pointing to: 

![2021-07-26 19_15_57-Greenshot](https://user-images.githubusercontent.com/17692472/127084574-82593d15-304c-447c-aa44-8df0949562f6.png)

Bugs out on all of my other TV show widgets as well.

As well as after pressing backspace and backing out of that screen it returns to a UI that is "broken" or out of alignment.
I can get it to reset if I press the left arrow key to show the navigation menu. Then it seems to fix itself.
**Video is of widget at the top of the menu.** 
Same Widget as above: Recommended Tv Shows

https://user-images.githubusercontent.com/17692472/127085987-436502d5-0437-4793-ad55-51f51da4a398.mp4

**Video is of widget at the bottom of the menu.**

https://user-images.githubusercontent.com/17692472/127086500-52da30df-5ca7-4949-87f2-0821a2441e6f.mp4

Widget is pointing to:
![2021-07-26 19_16_07-Greenshot](https://user-images.githubusercontent.com/17692472/127086862-ca9798a0-e483-447d-927c-c3bf90b814e6.png)

As always, all my files are real video files being host over a local SMB connection.

**Comment by inb4after** [comment]
I don't see where else the Episodes button should/can go to.

I've been trying to reproduce the misaligned Netflix Home widget bug for a very long time and cannot reproduce. Does it happen if you have more than two main-menu items? (i.e. Search, TV shows, Movies, Add-ons, Settings, Power is the default setup).

It looks like the second bug is not related to the first, and I don't think the first is a bug.

**Comment by SerpentDrago** [comment]
> I click on `Episodes` inside of a Tv Show's information page and it seemingly sends me to it's season directory.
> 
> Tv shows > Recommended Tv Shows > Select Tv show > Episodes > Looks like it goes to the season directory.


umm  where else do you expect it to navigate to .. you clicked a SHOW (not a episode or a season)  and then episodes ..... how did you expect it to work ? be magic and pull up the current season your watching ? hows the skin supposed to know that info ..

**Comment by jojobrogess** [comment]
I figured this one out. I'll post pictures on what was going on and close this tonight.

**Comment by jojobrogess** [comment]
For some reason I must have changed this setting or it got changed somehow:
(Settings>Media Settings>Videos>Flatten TV Shows Seasons)
If it's set to **never**, after selecting **Episodes** you'll be sent to the season directory

![2021-12-12 21_43_06-Greenshot](https://user-images.githubusercontent.com/17692472/145758767-61b65d03-0b2e-439f-b4f4-5b25e4ef9d70.png)
![2021-12-12 21_40_04-Greenshot](https://user-images.githubusercontent.com/17692472/145758517-b446deb5-e4c2-4ff0-83d1-346c9076309f.png)

***********************************************************************************************************************************

BUT if it's set to **Always**, after selecting **Episodes** it will bring you to a directory containing all episodes with either the next up or in-progress episode selected 

![2021-10-11 16_01_40-Greenshot](https://user-images.githubusercontent.com/17692472/145758365-3856fd3c-72c1-4ead-aacc-a496800c4bc1.png)
![2021-12-12 21_40_39-Greenshot](https://user-images.githubusercontent.com/17692472/145758525-d20ef0cd-68a4-484b-8c50-7cf60fc1f8b6.png)
