### ISSUE TITLE
The date and time on Home Screen overlaps category widgets

### ISSUE THREAD

**Issue by xyzfre** [SerpentDrago/skin.auramod#201]
Using Aura Home layout The day month and year overlap  category widgets ,on lates version 1.1.1 ,Nvidia Shield ,K19.1
![1DAB6915-4186-4861-B95C-749796B68F24](https://user-images.githubusercontent.com/49699869/127582269-e365d60e-4ed5-40ae-beff-77c8de024fec.jpeg)

**Comment by xyzfre** [comment]
Before version 1.0.36
![C4BA0968-B869-4B0A-971A-BF6871548352](https://user-images.githubusercontent.com/49699869/127638351-db635e7e-b37e-4c70-b06f-03a313691dd2.jpeg)

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.1.2
