### ISSUE TITLE
How to update???

### ISSUE THREAD

**Issue by wormvortex** [SerpentDrago/skin.auramod#203]
Following the instructions in the Wiki it installs v1.0.32 however on here it says the latest version is  v1.1.1. How do I upgrade to this via kodi?

**Comment by Goldenfreddy0703** [comment]
Which device are you using kodi on?

**Comment by wormvortex** [comment]
a Pi4 running LibreELEC

**Comment by Goldenfreddy0703** [comment]
oh nice, you need to ssh or use winscp into the filemanager and put the skin in the addons folder. 
1. Download the zip file:https://github.com/SerpentDrago/skin.auramod/archive/refs/heads/Matrix.zip
2. Extract it
3. put it into .kodi\addons

**Comment by wormvortex** [comment]
I did wonder if it needed to be manually done. Will try this method later. 

Thanks.

**Comment by SerpentDrago** [comment]
> oh nice, you need to ssh or use winscp into the filemanager and put the skin in the addons folder.
> 
> 1. Download the zip file:https://github.com/SerpentDrago/skin.auramod/archive/refs/heads/Matrix.zip
> 2. Extract it
> 3. put it into .kodi\addons

Never install this way  , just download zip  transfer to the kodi device , and install from zip in kodi and point to the local zip . direct extracting the the addon folder doesn't properly update Kodi's db with the version / updated deps / etc . it could cause all kinds of issues. 

ALWAYS let kodi install addons don't manually extract or else its not going to install right .

**Comment by SerpentDrago** [comment]
> Following the instructions in the Wiki it installs v1.0.32 however on here it says the latest version is v1.1.1. How do I upgrade to this via kodi?

yes the latest version released on the kodi repo for general public use is that . this is in development and the repo is not always up to date with github development version , i will update soon enough

**Comment by Goldenfreddy0703** [comment]
Whoops 😅 sorry I forgot about that method too.

**Comment by wormvortex** [comment]
Is there a reason in progress TV shows is the only widget that seems to work on the new versions? Even when I pick things like recently added tv shows they don't appear as widgets on the main screen? Worked fine in v1.0.32

**Comment by wormvortex** [comment]
Did anyone have an answer for this?

**Comment by Goldenfreddy0703** [comment]
I'm not sure tbh, you may want to wait for @SerpentDrago answer for that cause I completely forgot sadly.
