### ISSUE TITLE
Media not loading

### ISSUE THREAD

**Issue by 10213921412** [SerpentDrago/skin.auramod#205]
Followed pre and post install instructions but I can't seem to make it actually display my media. It launches to a black screen with the menu on top. Looked around in the settings menus but couldn't find an option to resolve it so I must have missed something obvious which wasn't in the instructions. Kodi's default skin loads the media fine. Any ideas?

**Comment by SerpentDrago** [comment]
what device ? screenshots ? is your media local and in kodi library ? what other skins have you used on that install before , sometimes old skins cause issues with shared menus , you would need to go into Skin Shortcuts settings and disable sharing of menus. 

Lots of things could cause this "issue"

**Comment by jojobrogess** [comment]
Kinda sounds like the skins install initialization didn't work correctly, or you didn't set up widgets to display your content. Pics and device info as well as kodi version & auramod version would help out a lot.

You can configure menus and widgets here:
Settings>Menu & Widgets  

...or if you're feeling adventurous:
 Settings>Interface>Skin> -Configure Skin>Home>Customize Home Menu & Widgets

**Comment by SerpentDrago** [comment]
Stale issue. closing
