### ISSUE TITLE
Cannot satisfy dependency

### ISSUE THREAD

**Issue by fairlynew** [SerpentDrago/skin.auramod#209]
Current everything.
Had to fresh install my build.
Now I cannot install repository.auramod-1.1.1.zip.
Error:Failed to install add-on from zip file.
The dependency on xbmc.python version 2.26.0
could not be satisfied.

I used the serpentdrago install guide.

**Comment by SerpentDrago** [comment]
what version of kodi are you on , this version is only for kodi 19 , matrix , and the repo is not even called repository auramod 1.1.1 its called  repository.auramod.aio . 

You should read the wiki on this github > https://github.com/SerpentDrago/skin.auramod/wiki

stop using old guides that are dated , use the guide (wiki) built into this github page

**Comment by fairlynew** [comment]
That was the info I needed, thank you
