### ISSUE TITLE
How to show episode thumbnails 

### ISSUE THREAD

**Issue by wormvortex** [SerpentDrago/skin.auramod#210]
How do I set it so when I'm scrolling through episodes of a show it will show a thumbnail of that episode rather than just the show generic thumbnail like mine currently does?

**Comment by SerpentDrago** [comment]
Please follow the post install instructions https://github.com/SerpentDrago/skin.auramod/wiki  , also plug in any Fanart api keys you have into whatever addon yoru using . 

if your in Episode view , viewing a list of episodes , thumbnails should appear (little mini screenshots of that episode) It depends on if the addon provides this .  

what addon ?

**Comment by wormvortex** [comment]
No add ons. It was my own media. Turns out it was caused by having an enable fan art box ticked in settings. Unticked that and now all the episodes have thumbnails.

**Comment by SerpentDrago** [comment]
yeh was going to go to that next , by default that is NOT enabled , so messing around you must have enabled it thinking it would help. Glad you got it figured out :)
