### ISSUE TITLE
Setting Widget

### ISSUE THREAD

**Issue by sftech13** [SerpentDrago/skin.auramod#211]
I'm looking for the file I can edit for personal use to change some of the setting shortcuts to installed addons. 

Can someone help me with which file  I need to edit?

https://ibb.co/rfPwVnt

**Comment by SerpentDrago** [comment]
https://github.com/SerpentDrago/skin.auramod/blob/c1e6bc1879085cf442aa98dbea8727f411b81e8a/1080i/Includes_Object.xml#L8446
