### ISSUE TITLE
New updates?

### ISSUE THREAD

**Issue by djdirty60** [SerpentDrago/skin.auramod#218]
Good day, 
Are there any new updates coming for this skin? 

thanks in advance

**Comment by Goldenfreddy0703** [comment]
Hey there new updates may not be coming to this skin unless @SerpentDrago has the motivation to work in his skin. I did update pull requests tho if you would like to check that out.

**Comment by SerpentDrago** [comment]
No it's no longer being updated I no longer use Kodi. I have no issues merging clean pull requests though

**Comment by Goldenfreddy0703** [comment]
hey @SerpentDrago thank you for merging my pull requests, your the best. Thank you and sorry to hear that you no longer use kodi.
