### ISSUE TITLE
[BUG]Episode Thumbs no longer hidden w/ Kodi Setting 19.3

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#219]
Episode thumbs are no longer hidden on Kodi 19.3

`Show information for unwatched items` 

Episode plot = Working
Episode thumb = Not working

This issue must have something to do with this change in 19.3

> We've fixed a bug that affected thumbnails for watched episodes when hiding episode spoilers.

As you can see below, Episode Thumbs are being displayed in 19.3 for unwatched episodes, when they were hidden in 19.1

19.1
![Kodi_20211209_171040](https://user-images.githubusercontent.com/54026944/145450634-d4f11ac1-cabc-4f45-afff-5ec37c06aaa3.png)

19.3
![Kodi_20211209_173626](https://user-images.githubusercontent.com/54026944/145450721-13f6d1bc-786f-45fc-904d-b4b0dd038eed.png)

19.1
![Kodi_20211209_171323](https://user-images.githubusercontent.com/54026944/145450772-3de05677-6263-4e0b-9b80-08d0872c5a78.png)

19.3
![Kodi_20211209_171848](https://user-images.githubusercontent.com/54026944/145450781-3a1f6431-b7b6-4c1d-9b89-642b05bba690.png)

19.1
![Kodi_20211209_171401](https://user-images.githubusercontent.com/54026944/145450826-eaaf6cd2-c3cb-40dc-97ba-0ee7a91fe7a1.png)

19.3
![Kodi_20211209_171915](https://user-images.githubusercontent.com/54026944/145450840-276e3928-fa24-45aa-9ae6-0c4ff25565b4.png)

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.1.3
