### ISSUE TITLE
Just a thankyou 

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#220]
Hi there I would just like to say It's so good to see this skin being worked on again, Auramod has always been my favourite skin so it's massively appreciated the time you take to work on it, thankyou 🙌🏻

**Comment by Dealz-416LS** [comment]
+1

I am also glad this skin is receiving some attention again and also greatly appreciate the time and effort put into fixing and adding features!

**Comment by xyzfre** [comment]
I'm also very THANKFUL ✊🏼👏🏼to see AuraMOD being updated again it's the BEST skin out there been using it for at least 3years now and don't plan on stopping,,Thank you for your AMAZING work

**Comment by inb4after** [comment]
:heart:
