### ISSUE TITLE
Enable Autoscroll to Hub not working

### ISSUE THREAD

**Issue by CdnCaptainKen** [SerpentDrago/skin.auramod#224]
After the last update the down button on my Shield remote won't move the screen down to my TV Aura Hub items. The first thing on my main menu is the TV Aura Hub. It displays a TV Shows spotlight and submenu and below that is a down arrow. Using the remote, I can no longer get to that down arrow or scroll down to my hub. Before the update pushing down below that submenu brought up a second screen with the TV Aura Hub items.

I can still bring up that second screen with the TV Aura Hub items by selecting the TV Aura Hub on the main menu. So that's my workaround but I'm sure autoscroll stopped working after the last update
![20211218_095927](https://user-images.githubusercontent.com/96364597/146664393-986d29f5-4ef9-483c-8c53-2e32d979f174.jpg)
.

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.1.6

**Comment by CdnCaptainKen** [comment]
Thanks! You're awesome!
