### ISSUE TITLE
Navigation error after exiting episodes view

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#226]
Netflix homestyle with auramod playlists as widgets and real library files. 
I have submenu's on, but this error still happens regardless of having them or not.
Recommended TV Shows is the first one on top, Top Rated is second, Similar TV Shows is third, and All tv shows if fourth.

https://user-images.githubusercontent.com/17692472/147534177-65d98d56-131d-4701-ba92-d91eedbcc95d.mp4

After backing out of the episode selection screen the homescreen navigation seems to be off. 
After pressing left the error seems to go away.

**Comment by inb4after** [comment]
Send me a message on Discord.

**Comment by inb4after** [comment]
@jojobrogess Please send me a message on Discord, I would like to try some things to reproduce this issue.

**Comment by jojobrogess** [comment]
I don't use Discord too often so I don't really know how to find you there. DM me the info(or post it here) and I'll add you

**Comment by inb4after** [comment]
@jojobrogess What is your discord username?

**Comment by jojobrogess** [comment]
It's the same as this one

**Comment by inb4after** [comment]
@jojobrogess I need the 4 digit number as part of your username as well.

**Comment by jojobrogess** [comment]
jOjOBROgess#0019

**Comment by inb4after** [comment]
@jojobrogess I have sent you a friend request on Discord, please accept it and we can talk there.

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.1.7

You will need to force skin shortcuts to rebuild your menu in order for this fix to apply to your existing skin setup.

**Comment by xyzfre** [comment]
How do you force skin shortcuts to rebuild would really appreciate your help if you can and thank you for keeping up with these recent updates for AuraMOD Keeping one of the best skins alive I've been using it now for about five years amazing work

**Comment by SerpentDrago** [comment]
> How do you force skin shortcuts to rebuild would really appreciate your help if you can and thank you for keeping up with these recent updates for AuraMOD Keeping one of the best skins alive I've been using it now for about five years amazing work

Just change any Minor thing in menu's/widgets/etc. It will then Force a rebuild

**Comment by jojobrogess** [comment]
@xyzfre This worked for me:
Add `RELOADSKIN()` as a custom widget action. I put mine in the PowerMenu.
![2022-01-12 18_30_48-Greenshot](https://user-images.githubusercontent.com/17692472/149255421-0ddfc4b3-6683-4801-b691-b5775f5de02c.png)

@inb4after THANK YOU and sorry for not responding quicker, the last couple weeks have been intense and I just had surgery on Saturday.

**Comment by inb4after** [comment]
@jojobrogess

By changing the menu (adding a new item) you forced a skin shortcuts rebuild, however you can just navigate to any existing menu item (or any individual widget), press disable then enable it again and the menu will rebuild without needing to add any items.
