### ISSUE TITLE
clearlogo 

### ISSUE THREAD

**Issue by forsajd1** [SerpentDrago/skin.auramod#228]
Hello: Could I add the option to deactivate clearlogo so that it is only in the text of the movie? Skin arctic zephyr reoladet so it has
Well thank you

**Comment by inb4after** [comment]
Could you add some screenshots of which clearlogo locations you would like to be replaced by text?

**Comment by forsajd1** [comment]
https://user-images.githubusercontent.com/79520759/147739008-38cea2f2-7c28-4f7b-b87f-acbffa29e741.mp4



add item somewhere in auramod settings

**Comment by SerpentDrago** [comment]
Thats not auramod , i have no idea what skin your using but thats not auramod . auramod's context menus and top menu doesn't look like that at all . and has NONE of those options via context menu or top menu . it doesn't work like that at all . 

sorry we can't help you with a different skin or mod of the skin , contact the developer of that skin

**Comment by SerpentDrago** [comment]
These videos show auramod , showing both netflix library views and non netflix library views toggled in settings . Disregard the general setup , its just hobbled together for testing . Netflix Library views have clearlogo , and disabled doesn't . also auramod uses a top menu bar for view changes not context menu . 

https://user-images.githubusercontent.com/21133858/147767458-dc157580-0a50-4ff0-9dcc-27f21a734d98.mp4


https://user-images.githubusercontent.com/21133858/147767465-a169f2f8-e9cb-4532-8a88-53739111387d.mp4

**Comment by SerpentDrago** [comment]
if you don't want Clear Logo in the Showcase view , then just  uncheck "enable netflix showcase views" in skin settings under library views
