### ISSUE TITLE
Widgets not populating new results from liked lists within an addon

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#229]
This is might be quite confusing but I've recently noticed that homescreen widgets are no longer populating new items from a trakt list like they do within the addon itself, I'm having to clear all addon cache for those new items to appear as widgets

Nvidia Shield Pro
Addon Fen

**Comment by SerpentDrago** [comment]
If you set a Category shortcut or another menu item to the custom action     `UpdateLibrary(video) `

and then click that menu or category shortcut , does it refresh ? does it refresh on restart ?

**Comment by JFG1000** [comment]
I can try this, do you mean create another widget with that custom command?

**Comment by SerpentDrago** [comment]
a Category widget or menu item , you can't set normal widgets to a custom command for one thing

**Comment by JFG1000** [comment]
Right i see, I have a friend that uses Venom and Tmdb and he says his widgets are refreshing fine so I'm guessing it's not a skin issue, I've been advised by Tikipeter to try re create the widget incase something in the code changed with a recent update so will keep testing for now

**Comment by JFG1000** [comment]
Recreating the widgets appears to have fixed the issue so i shall close this.
