### ISSUE TITLE
[BUG]Widgets in My Lists don't load w/ color code in Label

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#24]
[kodi.log](https://github.com/SerpentDrago/skin.auramod/files/6218275/kodi.log)

Widgets for Liked Trakt lists that i have added to My Lists do not load when there is Color code in the Label

Example 
List Title - [COLOR royalblue]creator username[/COLOR]

**Reproduce**
`Settings > My Lists > Configure Movie List (as example) > Choose Widget` add personal or liked trakt list.

`Settings > Menu & Widgets > Configure Submenu > Choose Item for Menu` go to Hubs and choose the List with the Liked trakt list

Go to that Hub and the widget won't load.

NOTE: `Seren > Seren Tools > Open Settings Menu > Interface > List Title Display Style` is set to `ListTitle - Creator `

**Comment by inb4after** [comment]
@Dealz-416LS 

Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).

Please let us know your results, and if any new bugs occur.

**Comment by Dealz-416LS** [comment]
Tested and fixed! Thank you!

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.7
