### ISSUE TITLE
Kodi Crashing A LOT

### ISSUE THREAD

**Issue by adamosborne83** [SerpentDrago/skin.auramod#248]
Hoping someone can help, I'm using firecube, auramod and venom, and keeps crashing all the time, I done a fresh install and everything.

https://paste.kodi.tv/onivuzulul

**Comment by JFG1000** [comment]
If language invoker is turned on in venom settings turn it off as that's mainly the cause for crashes

**Comment by adamosborne83** [comment]
> If language invoker is turned on in venom settings turn it off as that's mainly the cause for crashes

I've been looking at the audio errors, I think k it's something to do with that tbf 

https://imgur.com/a/M5KrKBQ
