### ISSUE TITLE
[BUG]Season Rating stuck and doesn't change

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#25]
Star rating for view types on Seasons are stuck at 5 Star and do not change.

`Context Menu` on any show or Episode item then click`Browse Show `

Note: `Change View mode` to any view that displays the season's rating.

All Seasons will display 5 Star.

**Comment by inb4after** [comment]
@Dealz-416LS 

Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).

Please let us know your results, and if any new bugs occur.

**Comment by Dealz-416LS** [comment]
Tested and Looks good, no longer stuck at 5 Stars.

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.7
