### ISSUE TITLE
Aura style widget clipped

### ISSUE THREAD

**Issue by DWH-WFC** [SerpentDrago/skin.auramod#251]
Hello from Germany
I use your skin as
"Aura Main Menu Style" with "Horizontal Menu" with "Middle Submenu Category Widget"

In the main menu where all widgets can be seen, the edge is cut off at the bottom.

Can you tell me by chance in which file I can find this entry to fix the error?

**Comment by DWH-WFC** [comment]
![Unbenannt](https://user-images.githubusercontent.com/45105289/162931586-2dad823f-b6c6-4c2b-9e6a-511f36dc4123.png)

**Comment by jojobrogess** [comment]
Is that the LAST widget for the menu list?

**Comment by DWH-WFC** [comment]
Yes its the Last Widget

**Comment by ndellicarpini** [comment]
I can confirm this happens to me as well (AuraMod 1.1.7, Kodi 19.4, Windows 10 x64, Aura Main Menu Style, Horizontal Menu, Large Submenu Category Widget) for the last widget. This weirdly doesn't happen with `Genre` style widgets, but all other widget types get cut off at the bottom of the window.

**Comment by davidzx** [comment]
i had a similar issue, just at the top instead of botton, and only when i have cattegories widget turned off. i toggled skin settings>miscellaneous>disable aura home widget gap on and that fixed it for me. maybe the same for your issue?

**Comment by hernandito** [comment]
It happens to me as well. I was about to post this as an issue... 

To correct, I tried editing the below files:
- Constants_Home_Mouse.xml
- Constants_Home_NoMouse.xml

Where I changed the value:
 `<constant name="widget_spacer_bottom">0</constant>` 
from 0 to negative and possible values.

It did **NOT** work. I also tried editing home.xml line 87, where I changed the below value to various positive and negative value.

![image](https://user-images.githubusercontent.com/787317/171009773-8cfee0b6-83a2-4a9c-97e1-3d4bcfb5da7b.png)

It also did **NOT** work.

I imagine it has to be something simple... but I am not that much of an skin expert.

Hopefully someone has an idea.

Thanks.

**Comment by DWH-WFC** [comment]
I found the problem, it is due to the following file and line.
file 1080i/Includes_Widgets.xml
```
     <control type="grouplist" id="330">
       <top>0</top>
       <left>60</left>
       # old line <height>1120</height>
       <height>1080</height> <!-- Affects the widget height in the main menu -->
       <orientation>vertical</orientation>
       <itemgap>0</itemgap>
       <usecontrolcoords>true</usecontrolcoords>
```

Line 176.
I haven't tested whether it has any further influence on the other theme functions because I only use Aura.

**Comment by jojobrogess** [comment]
I'll look into this tonight, if this fix works. I'll submit a PR. 
Thanks @DWH-WFC

**Comment by jojobrogess** [comment]
Alright it looks like changing line 176 in `1080i/Includes_Widgets.xml` from `1120` to `1080` DOES fix the problem. 

Before:
![2022-06-08 18_14_22-Greenshot](https://user-images.githubusercontent.com/17692472/172744133-107d2343-60b9-447c-b588-858401618213.png)

After:
![2022-06-08 18_20_06-Greenshot](https://user-images.githubusercontent.com/17692472/172744141-e7f91649-9708-4ddb-ac7e-8d7f7eb7f914.png)

About to submit PR.
THANK YOU @DWH-WFC !!!

******************************************************************************************************
FYI: if you're wondering why the images aren't loading on my widgets, I chose `video library>movies>genres` and then chose `submenu` as the widget style, to check out this bug.
 
Genre icons will only show up if you set the widget style to `genre`. 
It's either a bug or was designed like that, I can't tell.

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.1.9
