### ISSUE TITLE
Big thank you for still maintaining AM

### ISSUE THREAD

**Issue by xyzfre** [SerpentDrago/skin.auramod#257]
Woke up this morning and saw an update for AuraMOD just wanted to say thank you so much to see an update for AM which on my end is still considered the best skin out there been using it for about five years now and I really can't see myself using a different skin very grateful thanks again

**Comment by inb4after** [comment]
❤️ 

Thanks to @jojobrogess for his contributions a few months ago that were included in the recent update.

I'll still be focusing on new and existing bugs before features, but hopefully we'll get through them.
