### ISSUE TITLE
Force widget refresh

### ISSUE THREAD

**Issue by adamosborne83** [SerpentDrago/skin.auramod#258]
Hey, 
As previously mentioned, still loving that this skin is being maintained, thought it was, that's why I haven't posted here in ages.

Question,
Is there a way to stop widgets refreshing.....

For example, I use library (4000)movies and create widgets from genre..... so I go into action widget, see something I like the sound of.... watch a YouTube trailer to check, then I decide it looks rubbish, but then the whole widget has refreshed..... so I need to start over again....

Sorry does that make sense?

**Comment by inb4after** [comment]
What path is the widget pointing to?

**Comment by adamosborne83** [comment]
> What path is the widget pointing to?

So this is from my local library.
Video library 
Movies
Genre.....

But no matter what I watch, be it through Seren, or local, it causes a hard refresh of all widgets.

**Comment by inb4after** [comment]
Could you send screenshots of the widget settings and a video of it refreshing after watching a trailer?

Are these library items from TMDBHelper or locally stored files or a mix of both?

**Comment by adamosborne83** [comment]
> Could you send screenshots of the widget settings and a video of it refreshing after watching a trailer?
> 
> Are these library items from TMDBHelper or locally stored files or a mix of both?

They are Imported using Tmdbh,

It refreshes all movies on all aspects of library.
https://imgur.com/a/fyTy7Dp

**Comment by adamosborne83** [comment]
> Could you send screenshots of the widget settings and a video of it refreshing after watching a trailer?
> 
> Are these library items from TMDBHelper or locally stored files or a mix of both?

https://imgur.com/a/FFx8rcT

**Comment by inb4after** [comment]
> > Could you send screenshots of the widget settings and a video of it refreshing after watching a trailer?
> > Are these library items from TMDBHelper or locally stored files or a mix of both?
> 
> They are Imported using Tmdbh,
> 
> It refreshes all movies on all aspects of library. https://imgur.com/a/fyTy7Dp

I couldn't see the widget refreshing in this video, the list looks the same before and after the trailer is played. 

Are you referring to the ratings and other metadata being refreshed? Or the contents of the list changing?

**Comment by adamosborne83** [comment]
> 

Here we go, got it on video now :-) https://imgur.com/a/Ssx2IGw

**Comment by inb4after** [comment]
> > Could you send screenshots of the widget settings and a video of it refreshing after watching a trailer?
> > Are these library items from TMDBHelper or locally stored files or a mix of both?
> 
> https://imgur.com/a/FFx8rcT

The issue seems to be Kodi itself, when you set the widget sorting to `Random` then it keeps changing. You can set it to `None` to fix this, however the list would become static.

Look into [AutoWidget](https://github.com/drinfernoo/plugin.program.autowidget/) if you want non-static lists and control over when it refreshes.
