### ISSUE TITLE
Seemingly incorrect navigation in tv shows

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#26]
Once I click on a tv show and then click "episodes" it looks like it loads the show directory I clicked on, showing the all the seasons I have, then instantaneously switches to the "all" tv show directory which shows all my tv shows. 
It's quite frustrating.
If I press backspace from there it "goes back" to the show I previously clicked on and shows all the seasons for that show. 
If I don't press backspace and just navigate to the show I clicked on initially, it does everything correctly and navigates to the (most recent watched) episode as it should have in the first place.

Idk what's going on but I think that once I click on episodes it should navigate me to the (most recent watched) episode of any season not the directory of the tv show with all the seasons in it or directory of all tv shows.

**Comment by inb4after** [comment]
Please upload a short video of the issue, it would be a great help.

Also, is this for library items only? Or addons as well?

**Comment by jojobrogess** [comment]
https://imgur.com/yfbWCBw
I only have library items, I don't use addons to stream or whatever just for widgets. And at the moment, this build only has the required addons/modules for this skin to work. it's it's a freshish build.
Sorry if the video is a little quick, imgur only lets you upload 60 seconds. I left in the sound to help out with understanding if I'm pressing enter or backspace. 
 Hope this helps!

**Comment by inb4after** [comment]
It is a known issue since this feature was never working on Leia. It should now be fixed. Please test the [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing) to see if this resolves your issues, and doesn't create further issues.

**Comment by jojobrogess** [comment]
I'm at work right now, when I get off work in a couple hours I'll download it, test it, and let you know. Thanks for helping out

**Comment by jojobrogess** [comment]
Just installed the Testing version, by switching interfaces, then "updating"(installing testing version), and then switching back. 
(I'm explaining how so if I did it incorrectly you can tell me lol.)

Looks like it got worse for me; once I click on "episodes" it just takes me back to the main menu 

Here's the video: 
https://Imgur.com/a/Bm7kzcB

And here's the log file: 
https://paste.Kodi.tv/gubonaqive.Kodi

**Comment by inb4after** [comment]
Found the second bug, it seems that TMDBHelper widgets broke, but library items are working.

**Comment by inb4after** [comment]
@jojobrogess This should now be fixed in latest [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing). You can install inside Kodi using "Install from zip", and there's no need to switch skins.

**Comment by jojobrogess** [comment]
Okay I just installed the latest Testing branch and it looks like the same thing happens. I press "episodes" and it takes me back to the main screen. 

Here's the log for more info: 
https://paste.Kodi.tv/rosibifexo.Kodi

Thanks for taking the time on this one bro

**Comment by inb4after** [comment]
This looks like #31, let's move discussion over there.

Closing this specific issue as it is fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).
