### ISSUE TITLE
I never get Upnext 'still there?" notification.

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#263]
There is already another issue open but that post is about the program not working at all, which it does now.(should probably be closed)
here: https://github.com/SerpentDrago/skin.auramod/issues/22 

I just can't seem to ever get it to display the "Still there?" notification.
Everything else works fine.

Does anyone else get that feature? or is it out for everyone?

**Comment by jojobrogess** [comment]
The files for this are also confusing.

Since NextUp is depreciated(see [here](https://kodi.wiki/view/Add-on:Nextup_Service_Notification)) 
I don't understand why the files inside auramod work, when they are named 

`script-nextup-notification-NextUpInfo.xml`
`script-nextup-notification-PostPlayInfo.xml`
`script-nextup-notification-StillWatchingInfo.xml`

and then this is named `script-upnext-upnext.xml-old`, making it unusable.

************************************************************************************************

Under the Skinner guide for UpNext(see [here](https://github.com/im85288/service.upnext/wiki/Skinners))
It says:
![1112022-07-04 16_20_28-Greenshot](https://user-images.githubusercontent.com/17692472/177224807-7f0e0eb7-4156-4d6c-a941-286a5128092c.png)

So how are the files working? lol
I would assume since the logic behind the xml files is functional, it just doesn't break.
Or the UpNext service is just using it's own, idk what it should look like but here's mine:

![11112022-07-04 16_42_26-Greenshot](https://user-images.githubusercontent.com/17692472/177225842-32fe38c6-8b61-4cbb-ac25-c2dbfcb04eb8.png)
 
And then the addon is just written so that it can incorporate the old addon naming scheme? hmm
But then how do things like work:

Line 21 in `script-nextup-notification-StillWatchingInfo.xml` 
><label>$ADDON[service.nextup.notification 30010]</label>



************************************************************************************************

Regardless, I still can't seem to get the `Still Watching` notification to work naturally.

**Comment by inb4after** [comment]
These files are used to allow skins to use their own design for the UpNext/StillWatching popup. If the files don't exist then it uses the default design set by the addon, which you can see above.

The StillWatching popup not showing up is an addon issue. I saw they only recently added support for [non-library content](https://github.com/im85288/service.upnext/pull/247), so try testing some real files from library and seeing if StillWatching pops up. I am not familiar with using this addon, but we can change the design to match the skin and test if it works as intended.

**Comment by jojobrogess** [comment]
>The StillWatching popup not showing up is an addon issue. I saw they only recently added support for https://github.com/im85288/service.upnext/pull/247, so try testing some real files from library and seeing if StillWatching pops up. I am not familiar with using this addon, but we can change the design to match the skin and test if it works as intended.

I only have real library files on this system, so it must be an addon issue. 
Unless this [issue](https://github.com/SerpentDrago/skin.auramod/issues/237)("faulty logic in watched indicator variables.") is related somehow but I don't know enough about any of that. 

***************************************************************************************

I started messing around with the files already in auramod(`script-upnext-upnext.xml-old`)

I don't know why the close button was set to yellow, but it looks off. 
I would think sometype of red that is already used throughout the skin would work nicer. 

I'm not that creative so idk about placement: top, bottom/left, right. 
Should there be more information: season rating, time is/episode will end at.

![2022-07-09 00_43_06-Greenshot](https://user-images.githubusercontent.com/17692472/178096763-fecc3c2a-1c34-4c43-bb93-ebe65ab6ef8f.png)

![2022-07-09 00_43_09-Greenshot](https://user-images.githubusercontent.com/17692472/178096768-8622cbfd-2dcd-4c2b-bedd-e507ff0e1213.png)

***************************************************************************************

I'll keep messing with it and see what I come up with.

**Comment by jojobrogess** [comment]
I'm kinda getting this a little bit:

https://user-images.githubusercontent.com/17692472/178178832-ffb2d149-1d27-4db7-b6eb-5803b6d78209.mp4

I don't think the rating number/star image is in a good spot, or even necessary. 
I noticed while testing this with Stargate SG-1 that some episode names were long, so I separated the show title and season/episode number from the episode name.
You can't really see the `Current time/End's in` bit, I could put it up top by the continue watching. so it's out of the fanart image.
I just threw a random red in there to test if it looks better than yellow, I think it does.. I'll have to find out how colors are set in the skin and match that, so it's dynamic with other settings(if that's how things are, idk yet lol)
I have to fix the buttons, because they look weird. I'm not understanding `textoffsetx` 


I also think that the bottom left is a weird place for this to be. 
I think the whole window would look better on the top left/right, and a little smaller in overall size. 

*************************************************************************


Anybody have an idea how this should look? 
Or at least suggestions? even opinions?? lol

**Comment by jojobrogess** [comment]
I was able to figure it out, there was a problem with the old NextUp files not working correctly and it bugging out with me messing with the code. I had remove the addon cache and reinstall, and then remove the broken files.
