### ISSUE TITLE
[BUG]No focus highlight w/ ‘Small Category Widget’

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#28]
`Settings > Skin Settings > Widgets > Choose Category Widget Size` There is a bug with `Small Category Widget`

The focus highlight for submenu items is completely missing when using size Small making it difficult to know which submenu item is selected/in focus.

The Home Style being used is 'Netflix Home Layout'

The focus highlight around the submenu item to show that it's in focus doesn't appear when the submenu items aren't hidden. 

https://user-images.githubusercontent.com/54026944/113174852-b5c4c300-9242-11eb-85cb-7cb1e39a633b.mp4

In the preview image on the setting screen there is a focus highlight around the 1st submenu item to show it's selected. 
![Kodi_20210331_160740](https://user-images.githubusercontent.com/54026944/113174931-caa15680-9242-11eb-9636-12aa2dda3472.png)

**Comment by inb4after** [comment]
Please upload a short video of the issue, it would be a great help.

**Comment by Dealz-416LS** [comment]
@inb4after Done.

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.9
