### ISSUE TITLE
Reload Skin - Kodi crashes

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#29]
I've notified since I've been using the latest update, every time i use the reload skin function from the power menu, it causes kodi to crash

**Comment by inb4after** [comment]
I suggest a clean install of Kodi or deleting all your menu files from userdata/addon_data/script.skinshortcuts. A lot of dependancy related code has been fixed and this wil require you to set up your menu from scratch again as installing the new update over old builds of AM has caused code inconsistency. Sorry for the inconvenience. 

Before you do this, make sure you backup this folder and then install the [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing) as this one has all the fixes. This should be the only time you need to set up everything again.

**Comment by JFG1000** [comment]
So completely delete the whole build? Widgets the lot? I don't get what you mean by back up this folder sorry

**Comment by inb4after** [comment]
Which branch are you using currently?

**Comment by JFG1000** [comment]
Master branch but I think the best thing to do is to completely wipe kodi and start again it's just going to take me hours

**Comment by JFG1000** [comment]
I might just delete the skin shortcuts folder as you said above if you think I could just do that?

**Comment by SerpentDrago** [comment]
theres been no major changes to master or matrix branches in awhile , testing is the branch you should be using and testing . 

also Master = Leia 

Matrix branch = Matrix 

Testing = Matrix + lots of fix's 


what are you using auramod on ? matrix or leia ? 


Generally Crashing on reload is caused by some addon you have widgets pointed to  having issues with your system and having reuselanguage invoker enabled , disable reuselanguage invoker in those addons and try again .

**Comment by SerpentDrago** [comment]
@inb4after Talked to him a bit directly its ONLY happening on skin reload and NOT ever on startup or when widgets are loading / after editing menus / etc .. ONLY if you do a skin reload .. so its something happening and worth keeping a eye on for now skin reload can just be done by restarting kodi . and we will see if we or others have this issue also

**Comment by xyzfre** [comment]
> I suggest a clean install of Kodi or deleting all your menu files from userdata/addon_data/script.skinshortcuts. A lot of dependancy related code has been fixed and this wil require you to set up your menu from scratch again as installing the new update over old builds of AM has caused code inconsistency. Sorry for the inconvenience.
> 
> Before you do this, make sure you backup this folder and then install the [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing) as this one has all the fixes. This should be the only time you need to set up everything again.

I did a complete fresh install about four days ago to K19 and created a brand new build of AuraMod using the latest matrix branch didn’t realize there was a testing branch do I also need to completely start over to use the testing branch or can I just zip the file over the matrix branch ,, hope that makes sense,, my install was brand new I did not update from 18 to 19 I made sure I deleted everything from 18

**Comment by SerpentDrago** [comment]
Just install testing branch zip

**Comment by inb4after** [comment]
> > I suggest a clean install of Kodi or deleting all your menu files from userdata/addon_data/script.skinshortcuts. A lot of dependancy related code has been fixed and this wil require you to set up your menu from scratch again as installing the new update over old builds of AM has caused code inconsistency. Sorry for the inconvenience.
> > 
> > Before you do this, make sure you backup this folder and then install the [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing) as this one has all the fixes. This should be the only time you need to set up everything again.
> 
> I did a complete fresh install about four days ago to K19 and created a brand new build of AuraMod using the latest matrix branch didn’t realize there was a testing branch do I also need to completely start over to use the testing branch or can I just zip the file over the matrix branch ,, hope that makes sense , my install was brand new I did not update from 18 to 19 I made sure I deleted everything from 18

@xyzfre Use the download button on the [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing) page. You can install inside Kodi using "Install from zip", and there's no need to switch skins.

**Comment by JFG1000** [comment]
UPDATE : after starting fresh and re creating my build I can confirm no more crashes and it runs smoothly, closing issue.

**Comment by JFG1000** [comment]
@UPDATE this is now crashing again on every skin reload, what i can't work out though is why it's been running fine for a couple of days and now it's all of a sudden not
