### ISSUE TITLE
[BUG] Skin Shortcuts widgetPath is not defined

### ISSUE THREAD

**Issue by inb4after** [SerpentDrago/skin.auramod#292]
> Please help. When I now start up Kodi, I get the message "Skin Shortcut: Unable to build Menu".
> 
> The UI is blank and I can't get navigate to any widget, menu item, folder, or settings page.
> 
> I have been using Auramod for years without issue. Then right when the skin gets update (which I am very excited for!) it stops working.
> 
> What can I do to fix this, or even simply go back the default Estuary skin? I also hope I haven't lost ay of my skin customisations

Original comment: https://www.reddit.com/r/Addons4Kodi/comments/1fcwlly/comment/lml8b9m/

Log: https://paste.kodi.tv/ajotugapof.kodi

**Comment by derrgoo** [comment]
You need to read wiki how to install correctly. If not this happens.

**Comment by inb4after** [comment]
> You need to read wiki how to install correctly. If not this happens.

I thought this at first, but it was an old Matrix install that automatically updated to v2.0.0, and is now failing to build the menu. 

I'm waiting on some more information from the user to further diagnose the issue.

**Comment by derrgoo** [comment]
This happened to me until I read wiki and followed your procedure and then worked.

**Comment by inb4after** [comment]
> This happened to me until I read wiki and followed your procedure and then worked.

Which version of Kodi are you on, and could you tell me your script.skinshortcuts version?

**Comment by derrgoo** [comment]
I don't remember because I wiped everything and started over after the black screen. When this happened I tried to do it manually load it from your repo. I got it to work but I encountered that black screen. After that I found you posted directions on the announcement on git hub and followed that and wiki to the line and all worked. It seemed to me it was just the loading dependencies in order before downloading the skin.

**Comment by basKT-case** [comment]
OP here. Thanks again for looking into this issue.

As requested, below is the additional info you wanted to see. Hope I'm doing this right:

...\userdata\addon_data\script.skinshortcuts folder: https://mega.nz/file/top3wKBY#W5_8wcesl3X9jcfYzn3juYR4SNmn_XMSif4Lyw53iRQ

...\addons\skin.auramod\1080i\script-skinshortcuts-includes.xml file: https://paste.kodi.tv/mevawamuyo.kodi
_This isn't present in my current version, so this was from my old backup_

...\addons\skin.auramod\shortcuts\template.xml file: https://paste.kodi.tv/deviqaqere.kodi

**Comment by inb4after** [comment]
@basKT-case Actually, for the two .xml files, could you upload those as well, instead of the paste? It doesn't seem to be displaying properly on the paste.

**Comment by basKT-case** [comment]
Here you go:
https://mega.nz/file/Mso0HT5Y#ZpmKwZ-DtOdub8KEmMFq_YBGxDsR9KPHt3J9SRyh0PU

**Comment by inb4after** [comment]
@basKT-case 

Thanks for your help on this. I have found the cause of the issue and working on a fix.

You can fix this issue yourself by going to Settings Page > Search Lists > Configure Search Lists (or Skin Settings > Hubs & Spotlight > Configure Search Lists) and making sure that none of the items are disabled (either enable all of them or delete the disabled ones entirely).

If you're unable to access the settings page, you need to navigate to `...\userdata\addon_data\script.skinshortcuts` and delete the `searchmenus.DATA.xml` file.

The cause was an unexpected side-effect of some changes I made to get MyLists working again, but I think I know how to prevent it from happening even if you disable any search widgets.

**Comment by inb4after** [comment]
@basKT-case 

The fix should now be live, but due to the nature of the bug I had to backport the changes to all versions of AuraMOD.

Could you now re-install the skin and test if you can no longer cause the bug by disabling a widget item in the Search Lists configuration?

If you still have the issue after re-installing, it's possible that Kodi has installed the skin from the local package cache instead of the repository where the updated .zips are. 

To fix this, navigate to `...\addons\packages` and delete `skin.auramod.zip` before trying to install again.

**Comment by basKT-case** [comment]
It's working again! All is back to normal now. Thank you for looking into a fix for this issue! 

I can also confirm that I can no longer cause the bug by disabling a widget item in the Search Lists.

**Comment by inb4after** [comment]
> It's working again! All is back to normal now. Thank you for looking into a fix for this issue! 
> 
> I can also confirm that I can no longer cause the bug by disabling a widget item in the Search Lists.

Great to hear, thanks again for your time and sorry for any inconvenience.
