### ISSUE TITLE
[BUG]Skin not functioning correctly with Kodi Setting to hide episode thumbs.

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#296]
I have Kodi set to hide episode thumbs until the episode is watched using the below setting
`Settings >Media Settings > Videos > Show information for unwatched items - 'Episode thumbs' is unchecked`

However when `Skin Settings > Widgets > Widget Overlays > 'Use TV Show Fanart for Episodes' is unchecked`

Every Widget will display the episode thumb (where available) for both Watched and Unwatched, when the setting is checked every widget will display the Fanart for both watched and unwatched as per the setting.

So in either case the Kodi setting checked or unchecked it's not functioning correctly with the above mentioned Kodi setting.

Skin Setting - Checked: Seal Team episode in below screenshot is watched but doesn't display the episode thumb. Two episodes above are unwatched and are correctly hidden.
![Kodi_20240913_102956](https://github.com/user-attachments/assets/06f29575-e5ef-465f-b605-0a22faf55761)

Skin Setting - Unchecked: Seal Team episode in below screenshot is watched and does show the episode thumb. Two episodes above are unwatched and are also showing the episode thumb but should be hidden.
![Kodi_20240913_112027](https://github.com/user-attachments/assets/4acc4f13-c8df-4f37-8066-0a5e467de160)

Kodi 21.1
Seren 3.0.0
AuraMOD 2.0.4

**Comment by inb4after** [comment]
The fix should now be live, but due to the nature of the bug I had to backport the changes to all versions of AuraMOD.

Could you now re-install the skin from `Addons > My add-ons > All > AuraMOD > Versions > Select latest version from repository` and test if the issue still occurs.

If you still have the issue after re-installing, it's possible that Kodi has installed the skin from the local package cache instead of the repository where the updated .zips are.

To fix this, navigate to `...\addons\packages` and delete `skin.auramod.zip` before trying to install again.

**Comment by Dealz-416LS** [comment]
> The fix should now be live, but due to the nature of the bug I had to backport the changes to all versions of AuraMOD.
> 
> Could you now re-install the skin from `Addons > My add-ons > All > AuraMOD > Versions > Select latest version from repository` and test if the issue still occurs.
> 
> If you still have the issue after re-installing, it's possible that Kodi has installed the skin from the local package cache instead of the repository where the updated .zips are.
> 
> To fix this, navigate to `...\addons\packages` and delete `skin.auramod.zip` before trying to install again.

Deleted the skin.auramod.zip > Reinstalled Auramod > Checked that the issue is fixed in the same location as the screenshots above > We good! watched shows display the episode thumb, unwatched shows display the fanart! 

Thank you!
