### ISSUE TITLE
[BUG]Double playback progress indicators.

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#298]
On this screen, "Recent Episodes" It is displaying two playback indicators.

1. Red progress bar bottom and 2. Pie top right corner.

The indicator in the top right corner of the widget (Pie) should be the 'unwatched count'.

![Kodi_20240914_040151](https://github.com/user-attachments/assets/72b658aa-97d8-4b8c-b950-ba3e041bc037)

Kodi 21.1
Seren 3.0.0 (Fork Patch)
AuraMOD 2.0.4

**Comment by inb4after** [comment]
This is intended behavior to have both the partially watched indicator and the progress bar.
