### ISSUE TITLE
[Feature request] Costume Spotliights 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [SerpentDrago/skin.auramod#3]
**Is your feature request related to a problem? Please describe.**
One Feature Request i would like to have is costume Spotliights where you can choose your own addon content. 

**Describe the solution you'd like**
Well I would like to have my own addon spotlights on auramod. 
For Example: Youtube Spotlight, Twitch Spotlight, Soundcloud Spotlight

**Describe alternatives you've considered**
I can't really think of any alternatives at the moment except modifying its spotlight code for NextAired TV or Live TV Spotlights by changing them to my own addon path. 

**Additional context**
![Capture](https://user-images.githubusercontent.com/62456796/110496987-0d4c9480-80c4-11eb-9374-d464f5d011c3.PNG)
Adding More Spotlight Widgets would be the best so i can add Youtube or twitch or Soundloud or Spotify stuff on this skin.

**Comment by SerpentDrago** [comment]
Sorry , at this time i'm not doing any feature requests . I'm doing work  limited To Matrix bug fix's only  . I really no longer use kodi much and just am trying to do a bit to help make this skin work on matrix . 

If you can make a PR with the code changes needed to add additional spotlights  I'll gladly accept it , thanks

**Comment by Goldenfreddy0703** [comment]
Thank you
