### ISSUE TITLE
[Seren Fork] Not able to organize trakt tv shows watchlist  and trakt movie watchlist

### ISSUE THREAD

**Issue by derrgoo** [SerpentDrago/skin.auramod#302]
When changing the way the list shows trying to select 'Date Collected" which should show most recent collected in the list. Currently, it always reverts back to last item first. I have shown two pictures from seren and POV for example. 

![image](https://github.com/user-attachments/assets/8876ac39-3eb2-48fa-87da-9add3a8b05dc)

![image](https://github.com/user-attachments/assets/5fba841a-24fb-4f3b-8a2f-7dcb774c764c)

**Comment by derrgoo** [comment]
I came up with a fix that doesn't need to involve the add on! Goto trakt account and edit your lists how you need it to filter. It seems Seren uses this as the default vs all other addons doing within the add on. But this works! 

You can close or add. Thank you!

**Comment by inb4after** [comment]
As it seems to be addon related, report it here (if no one else has already done so):

https://github.com/nixgates/plugin.video.seren/issues
