### ISSUE TITLE
Seren fork trakt tv show watchlist down

### ISSUE THREAD

**Issue by derrgoo** [SerpentDrago/skin.auramod#303]
Seems trakt watchlist has gone down. It will only show 3 tv series when I have 50. Tried to reauthorize trakt several times and days.

**Comment by inb4after** [comment]
As it seems to be addon related, report it here (if no one else has already done so):

https://github.com/nixgates/plugin.video.seren/issues

There hasn't been any changes to Seren, maybe it is a temporary Trakt issue?
