### ISSUE TITLE
LandscapeWide Widget style missing seson/ep red badge

### ISSUE THREAD

**Issue by Ghostwithoutashell** [SerpentDrago/skin.auramod#304]
any additional screenshots can be provided. 

![image](https://github.com/user-attachments/assets/833491c0-5534-493b-8259-ce52869432f3)
 
**Expectation**
![image](https://github.com/user-attachments/assets/eeb00612-24b2-4334-ac21-a243b1bc1b59)

**Comment by inb4after** [comment]
Could you check Skin Settings > Widgets > Display text labels on landscape widget?

**Comment by Ghostwithoutashell** [comment]
so with that enabled it has the plane text

![image](https://github.com/user-attachments/assets/ca5774bd-30ea-4b8f-bc53-2067af0cec33)

**Comment by inb4after** [comment]
This is the new style, it was changed for better clarity and consistency.

**Comment by Ghostwithoutashell** [comment]
ah got it, find it not flowing as well especially with the ClearLogos.

**Comment by inb4after** [comment]
What addon are you using and which artwork source is being used for the clearlogo? It seems overly large.

**Comment by Ghostwithoutashell** [comment]
using Fen/Fenlight/POV and i am using the default artwork source, is there a way to check the clearlogo artwork source?

**Comment by Ghostwithoutashell** [comment]
I have another issue, not sure if i should open as a separate issue or not. 

1. no more "more" option at the end of the widget
![image](https://github.com/user-attachments/assets/16dc05d8-b0b0-41b6-9fbe-cc5242667d7d)

2. for some reason when i go to the search ie first option and go into widgets if i go up to the showcase widget it wont go back down into other widgets. i dont know how to show this exactly in a screenshot.

**Comment by inb4after** [comment]
> I have another issue, not sure if i should open as a separate issue or not. 
> 
> 1. no more "more" option at the end of the widget
> ![image](https://github.com/user-attachments/assets/16dc05d8-b0b0-41b6-9fbe-cc5242667d7d)
> 
> 2. for some reason when i go to the search ie first option and go into widgets if i go up to the showcase widget it wont go back down into other widgets. i dont know how to show this exactly in a screenshot. 

Please open separate issues for each of these, so we can investigate them as well. 

You can make a video for the second one to show this better, if possible.

**Comment by inb4after** [comment]
> using Fen/Fenlight/POV and i am using the default artwork source, is there a way to check the clearlogo artwork source?

I'm not sure about this addon, if it doesn't make reference to any settings for artwork then it's most likely not possible. 

Some addons use Fanart.TV and you need an API key to unlock the option to use their artwork. 

I think AuraMOD was initially made to work best with Fanart.TV artwork (especially clearlogo sizing), but personally I prefer a mix of TMDb artwork with Fanart.TV clearlogos using Seren, and this works well in the skin.

**Comment by Ghostwithoutashell** [comment]
it does have an option for fanart tv but i cannot see anything specifically pertaining to Clearlogos

![image](https://github.com/user-attachments/assets/7fe294e7-fff7-407b-8c2c-98668feac951)

**Comment by inb4after** [comment]
> it does have an option for fanart tv but i cannot see anything specifically pertaining to Clearlogos
> 
> ![image](https://github.com/user-attachments/assets/7fe294e7-fff7-407b-8c2c-98668feac951)
> 

Try enabling it and clearing the Fen cache/artwork cache if it has an option in the settings to do this.

**Comment by Ghostwithoutashell** [comment]
after settings modified per guidance. 

![image](https://github.com/user-attachments/assets/1895278c-e906-497d-b2cb-7b27ef8a2ed8)

**Comment by inb4after** [comment]
To me this looks better as the clearlogo is now level with the text label, as well as more reasonable sizing.

However, it is your personal preference to which artwork meta provider you prefer.
