### ISSUE TITLE
"rated"  prefix on any MPAA Ratings , All throughout skin 

### ISSUE THREAD

**Issue by SerpentDrago** [SerpentDrago/skin.auramod#32]
Netflix Info
![image](https://user-images.githubusercontent.com/21133858/113353025-17506480-930b-11eb-88a5-b7d301056df4.png)

Poster with showcase overlay 
![image](https://user-images.githubusercontent.com/21133858/113353095-2c2cf800-930b-11eb-8393-945305405874.png)

and many more . somehow the prefix needs to be removed

**Comment by inb4after** [comment]
AFAIK the "Rated" prefix comes from TMDBHelper. 

It should be able to be changed in the existing TMDBHelper setting, but it has no effect (probably a bug).

**Comment by SerpentDrago** [comment]
![image](https://user-images.githubusercontent.com/21133858/119348033-572c2c00-bc6a-11eb-9730-6fb3c5969b8b.png)
![image](https://user-images.githubusercontent.com/21133858/119348192-83e04380-bc6a-11eb-9565-72f2308fed19.png)


Fix's it for me , and if your using library items , change the settings in the scraper used. 

I dont' consider this a skin bug now , its the provider/ addon /s craper doing it and most all have settings . if your addon doesn't then get dev to add it :)
