### ISSUE TITLE
No episode art work. 

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#34]
![20210405_202056](https://user-images.githubusercontent.com/76907836/113616154-a8e20e00-964c-11eb-90b5-d73aa850e770.jpg)

Can anyone else please confirm if this is a skin issue or not? But currently I'm getting no episode art work, before there would be a caption from an episode.

**Comment by SerpentDrago** [comment]
Seems to be a issue with the addon / addons your using . appears on my setup fine using seren and kodi 19 matrix branch of this skin .  And to be clear i've never pulled up that season / show before in this install so its fresh metadata pulled from the source site .  Also works in tmdb helper , and tmdb helper made library items . 

Also fyi  episode artwork is called "episode thumbs"  which is a still frame from that episode . 

Seren > 
![image](https://user-images.githubusercontent.com/21133858/113619409-efbd0d00-9626-11eb-837d-7cdb23909ba3.png)
TMDB HELPER > 
![image](https://user-images.githubusercontent.com/21133858/113619550-1e3ae800-9627-11eb-80c5-881ec35b475f.png)
TMDB Helper created library item > 
![image](https://user-images.githubusercontent.com/21133858/113619829-77a31700-9627-11eb-818c-25713bcdf4a0.png)


You should confirm if you get them with the above addons . only API keys i'm using are Fanart

**Comment by Dealz-416LS** [comment]
@JFG1000 Those episodes look unwatched, can you confirm if you have `Episode thumb` hidden when unwatched in Kodi Settings

`Settings > Media Settings > Videos > Show information for unwatched item` 

I have no issues with Episode Thumbs
![Kodi_20210405_203416](https://user-images.githubusercontent.com/54026944/113619074-6de1d980-9650-11eb-89c2-ff35ee52868f.png)

I do have a question thou, on the Left side how do you have Rated and Episode Runtime to display mine doesn't show/disappears

**Comment by JFG1000** [comment]
@SerpentDrago I've tested and I'm not getting it with any addons, just looked at tmdb helper

**Comment by SerpentDrago** [comment]
If you have no issue with episode thumbs then what issue are you talking about . also obviously episode thumbs are not going to show if you have episode thumbs disabled for unwatched episodes

**Comment by Dealz-416LS** [comment]
@SerpentDrago 

Quick Question do you know why I'm missing the TV-MA rating and Episode runtime in the top left? 

rating doesn't display at all, The runtime displays for a second then disappears.

**Comment by SerpentDrago** [comment]
> @SerpentDrago
> 
> Quick Question do you know why I'm missing the TV-MA rating and Episode runtime in the top left?

what addon are you using ?

**Comment by Dealz-416LS** [comment]
> 
> 
> > @SerpentDrago
> > Quick Question do you know why I'm missing the TV-MA rating and Episode runtime in the top left?
> 
> what addon are you using ?

Seren

**Comment by SerpentDrago** [comment]
Rating comes from OMDB api key entered into both meta data dep and tmdb helper . no idea what the other issue with runtime yor having

**Comment by Dealz-416LS** [comment]
> 
> 
> Rating comes from OMDB api key entered into both meta data dep and tmdb helper . no idea what the other issue with runtime yor having

Hmm I have OMDB api key entered into both metadatautils and tmdb helper. I'll double check. I assume your having the runtime issue also as it's missing in your screenshot.

**Comment by JFG1000** [comment]
![20210405_214416](https://user-images.githubusercontent.com/76907836/113625055-50b10900-9658-11eb-8f12-cda08bc9cd7f.jpg)

I can confirm it's the TESTING branch that was giving me the issue, I have installed the MATRIX branch and it's back working

**Comment by SerpentDrago** [comment]
> > Rating comes from OMDB api key entered into both meta data dep and tmdb helper . no idea what the other issue with runtime yor having
> 
> Hmm I have OMDB api key entered into both metadatautils and tmdb helper. I'll double check. I assume your having the runtime issue also as it's missing in your screenshot.

The addon in question needs to fetch that info . some addons do , some don't. or its bugged no idea haha
