### ISSUE TITLE
[Not really a BUG] "ListItem.Studio" data injection from Seren

### ISSUE THREAD

**Issue by JacopoV** [SerpentDrago/skin.auramod#35]
Hi,

sorry to bother you all, but i don't know how to contact you to have some support or help ( i m really trying to fix myself).
Could someone take a look in here please ? 
Im trying to figure out how the variable "ListItem.Studio" is not populated (if at all) differently in Seren. Maybe you can give write a comment in there :
https://github.com/nixgates/plugin.video.seren/issues/595
@SerpentDrago

Apologies for coming forward in this way. 
If it's too much to ask, feel free to close this ticket on the fly.

Cheers and really, many many thanks

**Comment by SerpentDrago** [comment]
I don't really follow development anymore , and busy trying to fix bugs for kodi 19 version of auramod (matrix branch of this github )

but it appears its prob a seren bug . 

you can better see whats populated by listitems using dev helper > https://github.com/rmrector/webinterface.devhelper

Good luck !

**Comment by JacopoV** [comment]
Thanks, i will look into @SerpentDrago ! Take care!

**Comment by JacopoV** [comment]
@SerpentDrago I debugged everything possible. It's indeed a problem in Seren. Thanks a lot for pointing me to the tool. That's amazing to iron out these things. 
I've updated the ticker on Seren's end if you're curious :) 
Cheers
