### ISSUE TITLE
IMDB Top 250 Not work

### ISSUE THREAD

**Issue by wsx79** [SerpentDrago/skin.auramod#38]
The tag IMDB TOP 250 not see in netflix spotlight
I configure all API in skin setting but no luck.
I also try to delete simplecache in 
\userdata\addon_data\script.module.simplecache

To replicate.
Select a film include in IMDB TOP 20 (I use Indy and the last crusade) wait for rating. Top 250 not view.

![20210410_180455](https://user-images.githubusercontent.com/68690475/114276651-df8e9e80-9a27-11eb-9f19-d1a089072768.jpg)

**Comment by adamosborne83** [comment]
Have you enabled it in
Settings
Skin settings
Library views
Enable/disable ratings
Imdb250 (tick)

**Comment by wsx79** [comment]
> 
> 
> Have you enabled it in
> Settings
> Skin settings
> Library views
> Enable/disable ratings
> Imdb250 (tick)

yes but not work

**Comment by SerpentDrago** [comment]
netflix spotlight ? you mean  a home style type ? which one there is 4 main styles .

This would be at the top after focusing on a main menu widget in a netflix  home style right ?

**Comment by wsx79** [comment]
> 
> 
> netflix spotlight ? you mean a home style type ? which one there is 4 main styles .
> 
> This would be at the top after focusing on a main menu widget in a netflix home style right ?

![3](https://user-images.githubusercontent.com/68690475/115139783-3271e280-a034-11eb-832b-03593e556c9c.jpg)
![2](https://user-images.githubusercontent.com/68690475/115139791-3d2c7780-a034-11eb-9fee-2c6ff13e2389.jpg)
![1](https://user-images.githubusercontent.com/68690475/115139794-43225880-a034-11eb-9ea2-8918bd1f51bb.jpg)
![5](https://user-images.githubusercontent.com/68690475/115139798-461d4900-a034-11eb-88bd-f150f6710d66.jpg)
![4](https://user-images.githubusercontent.com/68690475/115139803-4a496680-a034-11eb-8800-a7f86dd599a5.jpg)


As you can see in some movies top250 are see but in other not.
Also metacritic

![115139316-83340c00-a031-11eb-9860-d19dc0bd1cc4](https://user-images.githubusercontent.com/68690475/115139820-69e08f00-a034-11eb-95a6-e0ae259e5fb3.jpg)
![115139317-84fdcf80-a031-11eb-8422-99b1c462e6b4](https://user-images.githubusercontent.com/68690475/115139822-6c42e900-a034-11eb-95fb-381d3e4f60e4.jpg)
![115139320-862efc80-a031-11eb-946d-525ceaa0ac0b](https://user-images.githubusercontent.com/68690475/115139825-6d741600-a034-11eb-975f-4527b2732de8.jpg)
![115139313-8202df00-a031-11eb-8bc6-2dfd79bc3b23](https://user-images.githubusercontent.com/68690475/115139827-6ea54300-a034-11eb-856a-da873e59ff99.jpg)

**Comment by Goldenfreddy0703** [comment]
I'm sorry,I don't really understand, can you show us how it looked like in kodi 18 and compare it with kodi 19?

**Comment by wsx79** [comment]
> 
> 
> I'm sorry,I don't really understand, can you show us how it looked like in kodi 18 and compare it with kodi 19?

I made a few debug.
If metadata from movies are take from skin.helper service, the skin show all rating Like Metacritic and Top250 but If I disable skin.heper, Metacritic and Top250 are not show because all metadata for rating are take from TMDBHelper.

Try to disable skinhelperservice and see what rating are show (in some show like Indy metacritic and top 250 are miss)
After try to renable it and the metacritic and top 250 are show.

I think there is a conflict beetween Tmdb helper and skinhelper.
I look more for it. I think all metadata rating have to take by Tmdbhelper like skin horizon that wokr very well in rating.

**Comment by SerpentDrago** [comment]
So from Netflix Showcase library view inside kodi's  movie library .. lol not home screen at all .  Home style has no effect on library views .

Yes ratings for some things are from skin helper service + metadata module utils . 

for best skin experience please enable both tmdb helper service lookups and skin helper service lookups. and enter api keys for fanart / tmdb / omdb into both .

I'm failing to see the issue , TMDB helper has ability to get some ratings and Metadata utils with skinhelper service lookups is able to get others . this is just how it works. This has always been how it works . its why you should enable both.

it could prob all be reworked to ONLY use tmdb helper for lookups , but not at this time and is extremely low priority and would be a feature request.

**Comment by wsx79** [comment]
> 
> 
> So from Netflix Showcase library view inside kodi's movie library .. lol not home screen at all . Home style has no effect on library views .
> 
> Yes ratings for some things are from skin helper service + metadata module utils .
> 
> for best skin experience please enable both tmdb helper service lookups and skin helper service lookups. and enter api keys for fanart / tmdb / omdb into both .
> 
> I'm failing to see the issue , TMDB helper has ability to get some ratings and Metadata utils with skinhelper service lookups is able to get others . this is just how it works. This has always been how it works . its why you should enable both.
> 
> it could prob all be reworked to ONLY use tmdb helper for lookups , but not at this time and is extremely low priority and would be a feature request.


I push my commit for migrate all to tmdbhelper (not all beacuse tvdb rating are not show by tmdbhelper).
It need to test.

Metacritic now working well and also IMDB Top 250 but I can't be able to have the postion in rating.
Give a look

**Comment by SerpentDrago** [comment]
can you explain "  can't be able to have the position in rating"  thats barely English to me lol

**Comment by SerpentDrago** [comment]
@wsx79 I'll accept your PR , if you make it cleaner with just the changes on where ratings are pulled

**Comment by wsx79** [comment]
The commit #44 fix it

Wait for pull

**Comment by SerpentDrago** [comment]
Thanks wsx79 , merged into branch  https://github.com/SerpentDrago/skin.auramod/tree/Matrix-Ratings-from-Only-TMDB-Helper

for testing and final touches , if you have anything more to add that relate to this issue , feel free to make pr's to that branch .

We will need old skin helper related skin settings removed and any remains as far as ratings goes if there is any left . 

I'm all for removing as much reliance on skin helper as we can and ratings is a great start . Sky wanted to do this before he left anyways 

Great work ! 

This issue will be closed after final testing and things are complete

**Comment by SerpentDrago** [comment]
so far so good , cleared simple cache and everything and pulling up ratings with only tmdb helper service running . both on real library items and addon content . 

one slight issue , and it may have occurred before .. can't remember 

![image](https://user-images.githubusercontent.com/21133858/115560380-86720680-a282-11eb-837c-d536caa66c0b.png)

![image](https://user-images.githubusercontent.com/21133858/115560420-91c53200-a282-11eb-83ab-4fbde9361d23.png)



We need to fix icons and code to properly display icons for RT audience score  . 

When i unpack the textures the icons are clearly there for both Color and Monochrome sets. some visibility condition is fucked for the rottentomatoes_usermeter. To much was removed / altered . 

lines 3909 , 3918 ,in includes_object.xml controls the icons visibility 

back burner stuff but just saw it 

@wsx79 , do you have the same issue ?

**Comment by Dealz-416LS** [comment]
@SerpentDrago

Same issue, the icon for RT Audience Score is also missing for me as well.

Quick question I was wondering are all the ratings supposed to display in "Netflix Home Layout" because I only ever get 2 (TMDB and Red Star), sometimes 3 with (TVDB) for shows also noticed that the studio logo doesn't show either but it's shown in the preview image in Skin Settings > Home Style.

**Comment by SerpentDrago** [comment]
shows don't typically have lots of ratings . i wouldn't test with those . and i'm not trying to troubleshoot all the skins issues at once . .

sticking to just visability issues for MOVIES , in AuraShowcase widget and showcase views

also any of the netflix home styles are really not well tested and buggy , both me and sky in the last year of this skins active developement didn't give 2 shits about anything but aurahome layout lol . so theres prob tons of  bugs in those  weird netflix home styles

**Comment by Dealz-416LS** [comment]
I see but even for Movies the Netflix Home Layout only displays 2 ratings TMDB and Red Star, I am able to get all other ratings to display for both Shows & Movies for a few seconds but then they disappear.

> one slight issue , and it may have occurred before .. can't remember

Anyway I reverted back and to confirm it didn't occur before the RT Audience Score Icon is displayed in Showcase Views.

**Comment by SerpentDrago** [comment]
Ok so its a issue with this patch , yeh i think the Visibility condition got fucked . 

as far as your netflix home layout . that will have to be another issue

**Comment by SerpentDrago** [comment]
Should be fixed now , thanks to dr .  it needed a Bracket on the end of the condition . it was deleted by accident 

I'm closing this now , if there's any more issues  with this branch please open a new issue

**Comment by SerpentDrago** [comment]
![image](https://user-images.githubusercontent.com/21133858/115577758-ac9fa280-a292-11eb-8734-3e7a8a07222d.png)
![image](https://user-images.githubusercontent.com/21133858/115578054-ef617a80-a292-11eb-8b41-34436a258856.png)
