### ISSUE TITLE
SETTINGS the START Style and MENU Style buttons. Can it be unified into one?

### ISSUE THREAD

**Issue by tvban** [SerpentDrago/skin.auramod#39]
Hello, in SETTINGS the START Style and MENU Style buttons. Can it be unified into one? It's to have only one, and to be able to use the other for something else, if possible, I think it would be better. have only one, so that you can place other things. Can you create it?
![MENU](https://user-images.githubusercontent.com/66959249/114690465-034b3080-9d17-11eb-9030-1fecd42888d6.png)

**Comment by SerpentDrago** [comment]
menu style and home style are different things . you can use one home style with multiple different main menu styles . 

no its fine how it is
