### ISSUE TITLE
[Bug] No Buttens are displayed when you look on information on an addon

### ISSUE THREAD

**Issue by Goldenfreddy0703** [SerpentDrago/skin.auramod#4]
**Describe the bug**
No buttons are displayed when you look on information on an addon

**To Reproduce**
1. Go to addons in your settings category.
2. Find an addon and click on it or long press addon and click information
3. Look on the top of your screen when clicking an addon
4. See error of no Buttons displayed

**Expected behavior**
See Buttons displayed

**Screenshots**
![No Icons](https://user-images.githubusercontent.com/62456796/110534268-dc348a00-80ec-11eb-8324-f851b57912c3.PNG)
![Kosk Mode Disabled](https://user-images.githubusercontent.com/62456796/110534290-e3f42e80-80ec-11eb-8e78-66fd945d418e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version Kodi 19 Matrix

**Additional context**
Kiosk Mode was disabled when looking at this error.

**Comment by SerpentDrago** [comment]
Fixed in latest Matrix branch 

Thanks for the Detailed bug report

**Comment by Goldenfreddy0703** [comment]
Hey anytime, thank you for replying back on this.
