### ISSUE TITLE
[Feature request] LibreELEC Menu in settings. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [SerpentDrago/skin.auramod#40]
Ok i know this sounds kinda dumb but you know how you have that one missing space in the corner on the settings menu, Well i filled that space up with a box named LibreELEC cause i think it would go great with Auramod when you are using LibreELEC on it. 

This is a photoshop idea i had so i basically filled that space up. 
![Libreelec](https://user-images.githubusercontent.com/62456796/114788104-e6325400-9d4e-11eb-8a00-3de2328e7e78.PNG)
I was wondering if we could add that to the settings sense its easier to navigate and i thought it would be cool. Its totally fine if you wanna leave it as it is tho.

**Comment by SerpentDrago** [comment]
Sorry dont' have or use LibreELEC . and that button would only work on LibreELEC . on top of that something would have to be done to NOT show it if your not running LibreELEC . 

So yeh .. not going to happen . Nice suggestion though

**Comment by Goldenfreddy0703** [comment]
Hehe totally fine, thank you tho 😊
