### ISSUE TITLE
Play button missing for strm files for Movie and Shows

### ISSUE THREAD

**Issue by itinerantmarshmallow** [SerpentDrago/skin.auramod#41]
Might be unique to myself, let me know what log files are useful.

Device: Nvidia Shield
Kodi Version: 19.0
AuraMOD: 1.0.3.4

Issue Description:
The play button / option is missing from Library content on the "Information" screen. Applies to both shows and movies. 
![Kodi_20210415_224431](https://user-images.githubusercontent.com/47308913/114942718-db55ed00-9e3c-11eb-8c4e-fc2263ce3b7b.png)
![Kodi_20210415_224452](https://user-images.githubusercontent.com/47308913/114942719-dbee8380-9e3c-11eb-8159-ad7fdff049f5.png)
![Kodi_20210415_224515](https://user-images.githubusercontent.com/47308913/114942721-dc871a00-9e3c-11eb-967f-e83f7db076df.png)

**Steps to Replicate:**
**Pre Requisite:** Videos default select action is set to Show Information. 

1. Add only strm files to Kodi Library, no physical media. 
2. Navigate from TV Shows/Movies menu item. (such as Titles -> select movie / show -> Information Screen
3. Confirm if Play button is present. 

Workaround:
Default action set to Play. 

Let me know any other info required.

**Comment by SerpentDrago** [comment]
JUST FYI , that screen is called "netflix info" 

so the issue is , your play button is missing for both Movies and Episodes in netflix info for strm library items ?

**Comment by SerpentDrago** [comment]
Ok , on Matrix branch , i've replicated issue .. 

added to the list

**Comment by itinerantmarshmallow** [comment]
Yeah I knew this was a previous issue.

I realise an issue like this can be down to fixing another display issue (physical media) so when a test is needed let me know. I'd suggest we close issue when it works for:

Movie Helper strm only
Physcial Media only
Mix of both


And completely unrelated I've seen other people mentioning for other jurial skins replacing extended info with embuary info. Not sure if that's worthwhile however. Can dig it out if needed for discussion (on a new Git Issue).

**Comment by inb4after** [comment]
@itinerantmarshmallow 

Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).

Please let us know your results, and if any new bugs occur.

**Comment by itinerantmarshmallow** [comment]
> @itinerantmarshmallow
> 
> Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).
> 
> Please let us know your results, and if any new bugs occur.

Downloading now. Will update to close this specific issue but need to set myself up for physical media tests if you need those.

**Comment by itinerantmarshmallow** [comment]
Tested both in add on content and in library strm files. 

Seems to be working fine. I'll close and open any other issues in a separate one (still need to test real library files).
