### ISSUE TITLE
Failed to install a dependency

### ISSUE THREAD

**Issue by pinn73** [SerpentDrago/skin.auramod#43]
Hi,

As above, error when trying to install.

**Comment by itinerantmarshmallow** [comment]
You would really need to provide SerpentDrago more information.

To start include the device details, Kodi Version details etc. 

Next what dependency, should be possible to see this in Kodi logs, especially if you install Kodi Log Viewer and Uploaded

These are easily installable from default Kodi repo. 

I can tell you skin installs, when following instructions, with no issue on Kodi 19.0 on Android nvidia Shield and my gut is this is user error.

**Comment by pinn73** [comment]
Thanks. Actually got it worked by changing required xbmc.gui version to 5.15.0.
Now to get clear art and tv show posters working....

**Comment by itinerantmarshmallow** [comment]
You can close issue most likely then if it suits you.

You sure you didn't download the Leia version? The addon XML for Matrix clearly has the correct version:

` <requires>
        <import addon="xbmc.gui" version="5.15.0"/>
        `

https://github.com/SerpentDrago/skin.auramod/blob/Matrix/addon.xml

**Comment by SerpentDrago** [comment]
> Thanks. Actually got it worked by changing required xbmc.gui version to 5.15.0.
> Now to get clear art and tv show posters working....

you clearly are not using the matrix version , from the matrix branch of this github .  https://github.com/SerpentDrago/skin.auramod/blob/97104901bb1953f6c1241e0e228fe27554295cfa/addon.xml#L4

as you can see. 

PLEASE if using on matrix , download and use the matrix branch . Just changing that line is but the tip of the iceburg on changes to matrix version .

**Comment by pinn73** [comment]
As I said in OP, I couldn't get your fork to even install so it's not that version's xbmx.gui I changed, but my existing one after updating the dependencies from here.

**Comment by SerpentDrago** [comment]
Matrix branch installs fine if you follow instructions and install the deps , IN ORDER . I've tested this as has others . 

Understand this github "fork" has multiple branches . it defaults to matrix though 

I have no idea why you had issues . unless you didn't follow the instructions

**Comment by pinn73** [comment]
I uninstalled and reinstalled and yes, it did work as you said - thanks.
Two issues though. No thumbnails are being generated for TV despite me having the option checked. Also, the auto hide widgets doesn't seem to work on home screen.

Thanks for all your work on this. It's much appreciated

> Matrix branch installs fine if you follow instructions and install the deps , IN ORDER . I've tested this as has others .
> 
> Understand this github "fork" has multiple branches . it defaults to matrix though
> 
> I have no idea why you had issues . unless you didn't follow the instructions

**Comment by SerpentDrago** [comment]
> I uninstalled and reinstalled and yes, it did work as you said - thanks.
> Two issues though. No thumbnails are being generated for TV despite me having the option checked. Also, the auto hide widgets doesn't seem to work on home screen.
> 
> Thanks for all your work on this. It's much appreciated
> 
> > Matrix branch installs fine if you follow instructions and install the deps , IN ORDER . I've tested this as has others .
> > Understand this github "fork" has multiple branches . it defaults to matrix though
> > I have no idea why you had issues . unless you didn't follow the instructions

Please open new issue if you are having problems notice a bug

But be far far far more detailed and provide screenshots
