### ISSUE TITLE
Error in CAST ans SIMILAR MOVIES

### ISSUE THREAD

**Issue by wsx79** [SerpentDrago/skin.auramod#55]
When I try to see Cast and Similar movie in Info the icon disappair and not work.
I made a small video for replicate.

In kodi log I see this error
2021-04-24 11:45:25.130 T:13847   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=similar&type=movie&imdb_id=348
2021-04-24 11:45:43.845 T:13860   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=cast&type=movie&imdb_id=348

It seem that It cant find the correct info using TMDb

https://user-images.githubusercontent.com/68690475/115955624-0359e600-a4f8-11eb-9247-9b7f56a20e7c.mp4

**Comment by wsx79** [comment]
I think error is in DialogVideoInfo-Icludes.xml

LINE 1897
<include condition="!Skin.HasSetting(VideoInfo.Disable) + !Skin.HasSetting(VideoInfo.CastList)" content="Widget_TMDB">
          <param name="id" value="53001" />
          <param name="onleft" value="8999" />
          <param name="onup" value="8999" />
          <param name="target" value="videos" />
          <param name="sortby" value="" />
          <param name="sortorder" value="" />
          <param name="onclick" value="SetProperty(BaseWindow,InfoDialog,Home)" />
          <param name="onclick2" value="RunScript(plugin.video.themoviedb.helper,add_query=$INFO[Container(53001).ListItem.Label],type=person,call_id=1137,prevent_del,delay=0.35)" />
          <param name="content" value="plugin://plugin.video.themoviedb.helper/?info=cast&amp;$VAR[Info_Param_Type]&amp;$VAR[Info_Param_IMDB_or_QUERY]" />
          <param name="widgetContent" value="plugin://plugin.video.themoviedb.helper/?info=cast&amp;$VAR[Info_Param_Type]&amp;$VAR[Info_Param_IMDB_or_QUERY]" />
          <param name="postercondition" value="true" />
          <param name="controltype" value="panel" />
          <param name="orientation" value="vertical" />
          <param name="height" value="880" />
          <param name="width" value="1800" />
          <param name="label" value="Cast" />
          <param name="visible" value="String.IsEqual(Container(8999).ListItem.Label,Cast) + !String.IsEmpty(ListItem.Label)" />

Seem that Tmdb take bad Param_IMDB and can't fine Movies.
I try but I can't bo able to fix

**Comment by SerpentDrago** [comment]
Thanks for the report

**Comment by SerpentDrago** [comment]
What provided this title you went to info on . Local media ? 

![image](https://user-images.githubusercontent.com/21133858/115981420-954a0900-a561-11eb-8b27-757aa5f77025.png)

its working fine for me on this and other titles from a tmdb helper item  or seren item

**Comment by SerpentDrago** [comment]
Ok so if i pull up a title from tmdb helper library item , i get missing sections , that i do get if i instead directly pull up information for that title inside tmdb helper .. or seren . 

so its something to do with library items , both real and fake .

**Comment by wsx79** [comment]
Hey @SerpentDrago 
How Can I can have Debug information (like dialogvideoinfo.xml or id 8999 or movie) in my skin.
It give me a very help for debugging it.

**Comment by SerpentDrago** [comment]
Customize your power menu  (or you could customize some category widgets or main menu item action either way ) 

Set these as custom actions 

![image](https://user-images.githubusercontent.com/21133858/115996259-905e7700-a5ac-11eb-9cd5-116c1d59bdf0.png)
![image](https://user-images.githubusercontent.com/21133858/115996263-96ecee80-a5ac-11eb-8ddf-1185203c8119.png)


One is Kodi's skin debug , and another is a skin specific skin debug . Both are usefull .

also there is this https://github.com/rmrector/webinterface.devhelper  which allows you to list , list.item variables and all kinds of  stuff outside kodi LIVE from a running kodi instance either local or over network. its invaluable 

![image](https://user-images.githubusercontent.com/21133858/115996429-3ca05d80-a5ad-11eb-90a2-88e8a98093f9.png)

**Comment by SerpentDrago** [comment]
@wsx79 

Looks like we traced the issue to the built in Kodi library Scraper , its setting the IMDB id to the TMDB id which causes failure . 

Quick solution till the scraper is fixed . Edit your library source and change the scraper used to the NON python one . 


https://user-images.githubusercontent.com/21133858/116891176-66383500-abfc-11eb-80fc-dfc4caa86b8f.mp4

**Comment by SerpentDrago** [comment]
we are currently working on reporting the issue and implementing a fix to the metadata.themoviedb.org.python scraper

**Comment by inb4after** [comment]
@wsx79

Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing), so you don't have to change the scraper. 

Apparently the new python scraper is better for artwork so I've done this hotfix (AuraMOD was partly at fault).

The python scraper itself has a major bug with sending TMDB ID into ListItem.IMDBNumber InfoLabel. When the scraper addon gets fixed, AuraMOD will automatically switch to using ListItem.IMDBNumber for lookups, but for now it will use a title and year query instead.

Please let us know your results, and if any new bugs occur.

**Comment by wsx79** [comment]
> 
> 
> @wsx79
> 
> Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing), so you don't have to change the scraper.
> 
> Apparently the new python scraper is better for artwork so I've done this hotfix (AuraMOD was partly at fault).
> 
> The python scraper itself has a major bug with sending TMDB ID into ListItem.IMDBNumber InfoLabel. When the scraper addon gets fixed, AuraMOD will automatically switch to using ListItem.IMDBNumber for lookups, but for now it will use a title and year query instead.
> 
> Please let us know your results, and if any new bugs occur.

Working like a charm.
Now all it's ok.
Can you push in Matrix TMDB branch?

**Comment by inb4after** [comment]
> 
> 
> > @wsx79
> > Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing), so you don't have to change the scraper.
> > Apparently the new python scraper is better for artwork so I've done this hotfix (AuraMOD was partly at fault).
> > The python scraper itself has a major bug with sending TMDB ID into ListItem.IMDBNumber InfoLabel. When the scraper addon gets fixed, AuraMOD will automatically switch to using ListItem.IMDBNumber for lookups, but for now it will use a title and year query instead.
> > Please let us know your results, and if any new bugs occur.
> 
> Working like a charm.
> Now all it's ok.
> Can you push in Matrix TMDB branch?

Once it is safe to merge to main Matrix branch we will merge also to TMDB Ratings branch. At the moment there are other major issues to focus on fixing first, before considering merging everything together.

**Comment by SerpentDrago** [comment]
@wsx79 This fix was reworked and made cleaner , Can you please retest thae latest Testing branch and make sure all is still good ? (understand testing branch does not have the tmdb helper ratings rework , as thats going to take time to make sure is perfect )

**Comment by wsx79** [comment]
> 
> 
> @wsx79 This fix was reworked and made cleaner , Can you please retest thae latest Testing branch and make sure all is still good ? (understand testing branch does not have the tmdb helper ratings rework , as thats going to take time to make sure is perfect )

I merged all new fix and tested.
It work well (only slightly slow in similar and raccomanded).

I found also a bug.
I have translate anything but some parts are not translate. I think it need a new debug in string.po

**Comment by SerpentDrago** [comment]
any translation issues please open a new thread . Some parts of the skin have not been properly localized so strings.po files can be used , they will need to be found and pointed out in detail so it can be localized . but please keep it in its own issue :)

glad to hear testing is doing well , you will notice we have a combined branch for testing with all the fix's currently in the pipline .

RatingsPlusTesting branch .

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.5
