### ISSUE TITLE
[Bug] Search Results are not in the default veiw when you hover over them.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [SerpentDrago/skin.auramod#6]
**Describe the bug**
I don't really think this is a bug but when i search for something, Every poster that i hover to goes to landscape view and i looked in the skin settings but i could not find the fix for it.

**To Reproduce**
1. Go to settings and go to Search list.
2. In Search list find an addon that you would like to add to your search.
3. Try searching something in the search bar and get result
4. Hover over the posters and see the error that they are in landscape view. 

**Expected behavior**
See the search results in poster view.

**Screenshots** 
![Veiw](https://user-images.githubusercontent.com/62456796/111539434-4334ed00-8744-11eb-8a33-02a6457b2205.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version Kodi 19 Matrix

**Additional context**
I don't know why they are in landscape view but i hope this is an error or bug and hope this can be fixed in the future.

**Comment by SerpentDrago** [comment]
Edit your search lists and 
Change the "widget style " and any other option  for that search widget to what you would like , just like any other widget

![image](https://user-images.githubusercontent.com/21133858/111547993-66659980-8750-11eb-8990-d92750786c1b.png)

**Comment by Goldenfreddy0703** [comment]
ok so i did try that but when you hover over that poster it changes to landscape mode. 
![kodi 18 auramod](https://user-images.githubusercontent.com/62456796/111549141-15ef3b80-8752-11eb-8717-b2d6164b2b71.PNG)
Here is what it was originally when we were on Kodi 18 back then. 
![Veiw](https://user-images.githubusercontent.com/62456796/111549281-49ca6100-8752-11eb-896b-f40270360d41.PNG)
Kodi 19 Auramod search result looks different.

**Comment by Goldenfreddy0703** [comment]
[edit] Im really sorry i should have shown you this image with multiple results, not one. 
![Kodi 19](https://user-images.githubusercontent.com/62456796/111549588-d117d480-8752-11eb-9bf3-ba9d94909248.PNG)
This is what i mean.

**Comment by SerpentDrago** [comment]
seems its not just making them landscape on Focus  , its also making them  massive ..

I have no idea whats going on , yes just tested it i'm getting same behavior ... hummmm

**Comment by SerpentDrago** [comment]
For now you can switch it to Poster Details .. at at least will keep the poster artwork (with other stuff ) 

I have 0 idea whats causing this wacky bug , and its causing some widget types to not even work at all . and causing shit to be massively zoomed in 

Have you noticed anything like this in any other part of the skin ? or just search results (again i dont' actively use kodi much anymore )

**Comment by Goldenfreddy0703** [comment]
Mostly just in search results and that's about it

**Comment by SerpentDrago** [comment]
Mostly ?

**Comment by xyzfre** [comment]
> For now you can switch it to Poster Details .. at at least will keep the poster artwork (with other stuff )
> 
> I have 0 idea whats causing this wacky bug , and its causing some widget types to not even work at all . and causing shit to be massively zoomed in
> 
> Have you noticed anything like this in any other part of the skin ? or just search results (again i dont' actively use kodi much anymore )

My apologies for commenting on this issue but it has to do with widgets if you use on the home screen widgets landscape view with showcase overlay enabled when scrolling the fix focus doesn’t work and when you scroll to the end you cannot see The See More

**Comment by xyzfre** [comment]
And lots of respect for your work bro AuraMod is the best skin I have ever tried been using it for 2years really appreciate you looking into these small bugs

**Comment by xyzfre** [comment]
that’s using Home Layout Style,,Aura  Home Layout with vertical icons

**Comment by Goldenfreddy0703** [comment]
sorry this happens in the search results for me and thats about it

**Comment by SerpentDrago** [comment]
> > For now you can switch it to Poster Details .. at at least will keep the poster artwork (with other stuff )
> > I have 0 idea whats causing this wacky bug , and its causing some widget types to not even work at all . and causing shit to be massively zoomed in
> > Have you noticed anything like this in any other part of the skin ? or just search results (again i dont' actively use kodi much anymore )
> 
> My apologies for commenting on this issue but it has to do with widgets if you use on the home screen widgets landscape view with showcase overlay enabled when scrolling the fix focus doesn’t work and when you scroll to the end you cannot see The See More

This is a completely different bug , i'm aware of but need someone to post a DETAILED issue for if it is only a matrix 19 bug .  (Fixed focus bug )  Please be detailed and i'll add it to a todo if there is a issue posted


The issue that happening here in this thread is related to the Search Results ONLY , and has nothing to do with fixed focus and normal widgets

**Comment by SerpentDrago** [comment]
@xyzfre  Could you make a Issue post , descriptive , with the fixed widget / non fixed widget bug issue your having . that way i have it on record as something to look into .. eventually lol .

**Comment by Dealz-416LS** [comment]
> Mostly ? 

Also happening in Hubs and My Lists.

Poster is set for widgets but switches to Landscape on focus.

**Comment by SerpentDrago** [comment]
> > Mostly ?
> 
> Also happening in Hubs and My Lists.
> 
> Poster is set for widgets but switches to Landscape on focus.

ohh just fucking great ! 

This is going to be a tough one guys. I'll put it at the top of the list

**Comment by Dealz-416LS** [comment]
Sorry to be the bearer of more bad news but i have additional details as i didn't see it mentioned.

Doesn't just happen to `Poster` style.

`SqaureLabel` is set for widget (tmdb people) but the first item is landscape and also switches to landscape on focus.

![Kodi_20210321_230519](https://user-images.githubusercontent.com/54026944/111924060-6f30d500-8a9a-11eb-9391-27b120587b14.png)

Despite the small bugs here and there overall I think this is the best skin I've ever used! I appreciate the time and effort you put into it!

**Comment by SerpentDrago** [comment]
Yeh i'm aware , same bug it pritty much effects most any widget style . 

i'll have to call in help to fix this , once i at least narrow down where all the stuff is for it .. 

Again . if i get the motivation to work on it .

**Comment by inb4after** [comment]
Tested each widgetAspect and some attempted fixes, but the issue seems to be with overlapping conditional statements rather than the widgetAspect itself. I've compiled a list of the working stuff and the bugs, which might help those who can take a closer look at the widgetAspect stuff. But at the moment it looks like a rewrite is needed as I can't find any obvious cause (I'm not very good at skins!)

  
### Search:

- [ ] Poster = **not working**, actually LandscapePoster
- [x] Square = **working**
- [ ] Landscape = **not working**, actually Landscape with currently selected LandscapeSmall (not a real widgetAspect)
- [ ] LandscapeWide = **not working**, actually Landscape
- [x] LandscapePoster = **working**
- [x] LandscapeSmall = **working**
- [ ] LandscapePanel = **not working**, actually Poster with currently selected LandscapeSmall (not a real widgetAspect)
- [x] LandscapeDetails = **working**
- [ ] PosterDetails = **not working**, actually Poster with currently selected LandscapeSmall (not a real widgetAspect)
- [x] WidgetLive = **working**
- [x] Logo = **working**
- [x] Genre = **working**
- [ ] Submenu = **not working**, actually Poster with currently selected LandscapeSmall (not a real widgetAspect)
- [ ] SquareLabel = **not working**, actually Poster with currently selected LandscapeSmall (not a real widgetAspect)

### Widgets:

- [x] Poster = **working**
- [x] Square = **working**
- [x] Landscape = **working**
- [ ] LandscapeWide = **working** (but has permanent text info labels)
- [ ] LandscapePoster = **working** (but is actually LandscapeWide and has permanent text info labels)
- [x] LandscapeSmall = **working**
- [x] LandscapePanel = **working**
- [ ] LandscapeDetails = **not working**, actually Poster with currently selected LandscapeSmall (not a real widgetAspect)
- [ ] PosterDetails = **not working**, actually Poster with currently selected LandscapeSmall (not a real widgetAspect)
- [x] WidgetLive = **working**
- [x] Logo = **working**
- [x] Genre = **working**
- [x] Submenu = **working**
- [ ] SquareLabel = **not working**, actually Poster with currently selected LandscapeSmall (not a real widgetAspect)

**Comment by SerpentDrago** [comment]
Fantastic research man ! , did you test on a normal home screen widget or from a hub / my list / search hub ?? 

reports i've gotten seem to indicate it only happens on hubs / my lists and not on the home screen direct from a menu section widgets

**Comment by inb4after** [comment]
> Fantastic research man ! , did you test on a normal home screen widget or from a hub / my list / search hub ?? 
> 
> reports i've gotten seem to indicate it only happens on hubs / my lists and not on the home screen direct from a menu section widgets

It did happen on a normal homescreen widget. I haven't tested hubs or my lists. Maybe have an idea why it could be like this, need to test more and I'll get back to you.

I am testing using Netflix Home Layout, which could be different to other layouts. Perhaps some widgetAspect are supposed to be disabled using this home layout, but the skin shows them anyway? That would make more sense for the Widget bugs.

I also think some bugs are carried from Leia as well. This may be one of them, I will double check on there as well, but Search widgetAspect was definitely working on Leia, for Landscape at least.

BTW check Discord whenever you're available, I am more active over there.

**Comment by SerpentDrago** [comment]
Roger will do

**Comment by Goldenfreddy0703** [comment]
Hey @inb4after ,sorry for bothering you but i just wanted to say that you did fantastic research on the View menu, Search fields, and the Widgets. Im really impressed that you got all these working. If its ok, do you think you can take a look at Arctic Horizon Skin thats from jurialmunkey? I think people needed help on some of the views layouts and widgets and getting it converted to python 3 and i think you would be the right person to ask. 

https://github.com/jurialmunkey/skin.arctic.horizon

**Comment by SerpentDrago** [comment]
> Hey @inb4after ,sorry for bothering you but i just wanted to say that you did fantastic research on the View menu, Search fields, and the Widgets. Im really impressed that you got all these working. If its ok, do you think you can take a look at Arctic Horizon Skin thats from jurialmunkey? I think people needed help on some of the views layouts and widgets and getting it converted to python 3 and i think you would be the right person to ask.
> 
> https://github.com/jurialmunkey/skin.arctic.horizon

Jurial is already a expert in skinning and his skin , I highly doubt he needs any help . if theres a issue with AH , Jurial will fix it . he even has a official matrix version and a matrix repo .
