### ISSUE TITLE
TV thumbnails replaced by fanart

### ISSUE THREAD

**Issue by pinn73** [SerpentDrago/skin.auramod#61]
Kodi v19 on OSMC. I have checked the setting in library/videos to show thumbnails but these have been replaced by fanart. Deleting thumbnail db and folder have not resolved this. See here: https://photos.app.goo.gl/hx9TTCaDk91Ccyd98

**Comment by SerpentDrago** [comment]
You have some settings wrong or something .  Also whatever addon your using , or library content has to actually have the "episode thumbnails" 

Its working here  In both Seren and TMDB helper 

![image](https://user-images.githubusercontent.com/21133858/116407751-16bec700-a800-11eb-9672-f62f574e2833.png)

make sure "extra fanart"  is OFF 
![image](https://user-images.githubusercontent.com/21133858/116406844-1c67dd00-a7ff-11eb-8125-b9d792a16187.png)

make sure "use tv show fanart for episodes" is  OFF
![image](https://user-images.githubusercontent.com/21133858/116406948-373a5180-a7ff-11eb-8f6b-0d6ee9fc69e4.png)
make sure you set this to show all information on unwatched items 
![image](https://user-images.githubusercontent.com/21133858/116408245-9187e200-a800-11eb-907c-5b00c5573f39.png)


Works fine for me , "Landscape Showcase" view , while viewing episode content type   (just fyi , thats really not a good view for episodes , the actual episodes view is best for that )  Showcase views tend to work best for Movies and maybe Seasons content type . But whatever each their own :? lol 

as seen here > 

![image](https://user-images.githubusercontent.com/21133858/116408445-cc8a1580-a800-11eb-8834-d4c5a5890137.png)

**Comment by pinn73** [comment]
Brilliant! Chalk another up to user error :)
I had enable the confusingly titled 'show TV fanart ' enabled. All good now.
Tried episode view but think showcase poster looks better imo

**Comment by SerpentDrago** [comment]
Great to hear , yes Show fanart is the SHOWS  fanart .  Episode Thumbnails is what your want , which are default .

**Comment by SerpentDrago** [comment]
Honestly "show tv fanart" should prob be changed to "Replace 'Episode Thumbnails' with  'Show' fanart" 

its a feature to avoid spoilers . but its now built into kodi though the "show information for unwatched items" feature . 

Anyways . have a good one
