### ISSUE TITLE
Home widgets not auto-hiding

### ISSUE THREAD

**Issue by pinn73** [SerpentDrago/skin.auramod#62]
On  previous iterations of aura mod with home style set to aura mod, if not focused on category widgets, they would auto hide.  I think I had accomplished this using 'enable side menu' auto hide. However, this feature appears to do nothing now - see here https://photos.app.goo.gl/KU3Xo4uvgwBdv38D9

What I would like is on the movie icon on home screen, to press left and be shown the sub-menu.

Hopefully this makes sense!

**Comment by SerpentDrago** [comment]
aura home style has NEVER been made to hide category widgets . thats a feature of the netflix styles by default . also there is 0 reason to link to external pictures on github you can paste the picture directly in comments  just fyi , i dont' really care just letting you know :) 

as far as you want submenu on left  action on main menu item ...  as far as i know thats never been a thing . submenu in auramod IS the catagory widgets .

**Comment by pinn73** [comment]
Right, well given my past success, I'll take your word for it! :)

Let me explain what I would like and if you could kindly help.
I just want a simple 3 icon menu on the home: movies/tv/settings and for both movies and tv to have a widget with shortcuts on to common commands. I also would like slideshow for TV and movies (which I currently have working) and a single image for settings. I did try the various home views but couldn't get it quite how I wanted. :(

Cheers for heads up re inserting images

**Comment by SerpentDrago** [comment]
setup menu to icon only , restore stock settings menu as one of them . edit or make the other 2 movies and Shows(orTV) . 

Set up a TV and Movie  Widget spotlight in the settings panel 

Turn on Movie spotlight in your movie menu 
Turn on TV spotlight in your tv menu 

setup category widgets in tv and movie menus to what you want (they act as normal shortcuts , and will appear below the spotlight widgets ) 

Pritty typical standard Aura home style setup , and is what i use actually .  I also link the catagory widgets to Aura style hubs . that way loading is quick on first start / home . as  no widgets besides the 2 spotlight widgets load till i click a catagory widget , that then loads up all the widgets in that Hub . you can also just set them to point to various addon sections .

**Comment by SerpentDrago** [comment]
Exactly what are you having a issue with . Sounds like you want a typical aura home style setup with spotlight widgets + category widgets (shortcut buttons ) .

**Comment by pinn73** [comment]
Not sure about the spotlight as that seems to be a more netflix style carousel, which I don't want on home screen. For me home screen should just be those shortcuts, plus backgrounds using random fan art for movies/tv. This is actually, what I have, bar the ability to click right/ show hidden sub-menu

**Comment by SerpentDrago** [comment]
you made it sound like you wanted spotlights . ok then no spotlights 

you just add category widgets (which will be at the top) set them to either small *icon only * , med , large 
Then add normal widgets .. 

ez 

I still dont' get what your talking about with hidden submenu , submenu's  in auramod are the  Category widget . unlike other skins that have a menu off the main menu .

**Comment by SerpentDrago** [comment]
You can always set a few category widget or main menu action  to open a "my list" "dialog"  that has a bunch of shortcuts also . then when you click that main menu or category widget it will popup with a nice dialog with all those shortcuts added to that "my list"

**Comment by SerpentDrago** [comment]
https://user-images.githubusercontent.com/21133858/116463382-a2544a00-a838-11eb-8550-542e198d7707.mp4

Showing how i linked a cat widget to a dialog "list"  Don't mind the label / name of the category widget . i'm always testing bugs and shit so things are named fucking weird , doesnt' matter what you put in a "movie" list either .. it can be anything doesn't have to be a movie 

play around :)

If you have any more questions feel free to open a issue , screenshots are always welcome to better explain :)
