### ISSUE TITLE
Looking at RecentTvShows.xsp and noticed how it was behaving.

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#65]
Idk if this is a bug or if this is how it's supposed to function but from what it looks like in `\extras\playlists\RecentTvShows.xsp`,  it will list your last viewed tv shows ordered by last played but and then it will also list all of the other tv shows that haven't been watched after it in backwards alphabet z-a order. 
Here's a photo:(I'm using this viewmode so you can see the watched dates)
![Untitled](https://user-images.githubusercontent.com/17692472/116802341-e2c8f780-aac6-11eb-855a-26811d514aa2.png)
You, Westworld, Weeds, and so on, haven't been watched on my device yet since my last system refresh.

This is \extras\playlists\RecentTvShows.xsp:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="tvshows">
    <name>Recently Watched TV Shows</name>
    <match>all</match>
    <order direction="descending">lastplayed</order>
</smartplaylist>
```

This is my fix:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="tvshows">
    <name>Watched TV Shows</name>
    <match>all</match>
    <rule field="numwatched" operator="greaterthan">
        <value>0</value>
    </rule>
    <order direction="descending">lastplayed</order>
</smartplaylist>
```
As you can see I just added a rule. This will now only show Tv Shows that you've watched, in last played order. 
Here's a photo:
![Untitled2](https://user-images.githubusercontent.com/17692472/116802705-dd20e100-aac9-11eb-84cd-3d3cf0c7520d.png)

It's nowhere near a HUGE bug or even a like feature change request, cuz you can make your own playlist like I did to do this. But I just thought I'd share in case that wasn't the intent  function of this playlist.

**Comment by SerpentDrago** [comment]
The intended function should be for it to list the Recently Watched shows , In descending order. 

Its doing that right ? by default without mods . 

Your issue is that it also lists unwatched shows after it lists the watched ones . and you would like it to just filter those out , as they prob dont' belong in a playlist called "recently watched"

I support this change 100 percent . 

Would you want it to list just shows that are recently played or just recently watched "marked watched" 

or should there be 2 playlists   Recently Played  and Recently Watched

**Comment by SerpentDrago** [comment]
I think something like 

    <rule field="lastplayed" operator="inthelast">
        <value>28 Days</value>

would be better ? can you test if that works for Shows . I dont' really have a library of files to test .

**Comment by itinerantmarshmallow** [comment]
I would have said you can assume anything marked watched _should_ be included as recently played but then people will have issues with Trakt syncs and the likes maybe. 

Personally I only see a need for Recently Played. 

Taken a guess that you can sort and filter using the below:
LastPlayed 

`
<rule field="lastplayed" operator="greaterthan">
<value>02-01-1970</value>
</rule>
<order direction="descending">lastplayed</order>`

Needs a test though.

**Comment by jojobrogess** [comment]
@SerpentDrago 
> Its doing that right ? by default without mods .

Yes, and then some. 

> Your issue is that it also lists unwatched shows after it lists the watched ones . and you would like it to just filter those out , as they prob dont' belong in a playlist called "recently watched"

This is correct. I don't think it was the intent especially considering it's name.

>Would you want it to list just shows that are recently played or just recently watched "marked watched"
>or should there be 2 playlists Recently Played and Recently Watched

After sitting on this for a little bit and trying to figure out what would work best:
I think the name `RecentTvShows.xsp` should be changed to `RecentlyWatchedTvShows.xsp`, to be made more clear.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="tvshows">
    <name>Recently Watched TV Shows</name>
    <match>one</match>
    <rule field="lastplayed" operator="inthelast">
        <value>30 Days</value>
    </rule>
    <rule field="playcount" operator="is">
        <value>1</value>
    </rule>
    <rule field="playcount" operator="greaterthan">
        <value>1</value>
    </rule>
    <order direction="descending">lastplayed</order>
</smartplaylist>
```

And then I think there should be a new playlist added called `InProgressTVShows.xsp`, which lists items by tv shows instead of episodes like `InProgressEpisodes.xsp` does.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="tvshows">
    <name>In Progress TV Shows</name>
    <match>one</match>
    <rule field="inprogress" operator="true" />
    <order direction="descending">lastplayed</order>
</smartplaylist>
```

**ALSO**, it looks like `\extras\playlists\InProgressEpisodes.xsp` has a typo:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="Episodes">
    <name>In Progress Movies</name>
    <match>all</match>
    <rule field="inprogress" operator="true" />
    <order direction="descending">lastplayed</order>
</smartplaylist>
```
The name should be `In Progress Episodes` not movies.



You do whatever you feel like would work best for the intended functionality of the playlists but the original `\extras\playlists\RecentTvShows.xsp` is broken because it just lists all Tv shows by recently watched, rather than list only shows that have been watched recently, so that's gotta be fixed regardless imo.

**Comment by SerpentDrago** [comment]
Fork this github , make the changes/add the files and make a PR , i'll accept , sounds like you got a nice handle on whats going on and your logic seems sound to me ! 

![image](https://user-images.githubusercontent.com/21133858/117859430-fb6ea580-b25c-11eb-9177-d62ae794acc4.png)

**Comment by jojobrogess** [comment]
_Originally posted by @jojobrogess in https://github.com/SerpentDrago/skin.auramod/issues/117#issuecomment-861036466_

Looks like these don't work:

***********************************************************************************************************************************
- Recently Aired Episodes - Rule: airdate inthelast 14 days - Order: airdate Descending

- Recently Aired TV Shows - Rule: premiered inthelast 14 days - Order: premiered Descending

- Recently Released Movies - Rule: premiered inthelast 14 days - Order: premiered Descending
***********************************************************************************************************************************

Ordering by premiered is not possible, you can only order by `Year` 
and
Using `first aired` in the last 14 days isn't working for Movies/TVShows.
It's just displaying all titles in released year order.
