### ISSUE TITLE
Next up widget (library) not working

### ISSUE THREAD

**Issue by deyooluv** [SerpentDrago/skin.auramod#68]
I am using the skin helper widget for my next up library (.strm) items.
The next episode in the next up widget don't play when I click play.
Please can you also point how I can adjust the viewmode for hub items. I would like to change the landscape showcase view to showcase view. I looked at the XML to edit and I didn't know which of the custom hub XML I have to edit.
Thank you for all the work you do

**Comment by inb4after** [comment]
Need a video of the first bug and screenshots for your question, which area of the skin you would actually like to change viewmode for.

**Comment by wsx79** [comment]
I have the same problem for my tv series in cloud. 
Tv Series in NAS (by Smb) work perfect.

**Comment by deyooluv** [comment]
https://user-images.githubusercontent.com/73711940/117156179-a9201700-ad7a-11eb-8793-f75d426b0795.mp4


@inb4after  here is the video for the next up widget isdue
Thank you

**Comment by deyooluv** [comment]
@inb4after please how do I edit the size of the poster size. I would like more widget items displayed on the screen. Thank you
![Kodi_20210505_082109](https://user-images.githubusercontent.com/73711940/117157316-bdb0df00-ad7b-11eb-93d4-1653c113eebf.png)
![Kodi_20210505_082129](https://user-images.githubusercontent.com/73711940/117157337-c1446600-ad7b-11eb-8958-d698857b4cf5.png)

**Comment by SerpentDrago** [comment]
> @inb4after please how do I edit the size of the poster size. I would like more widget items displayed on the screen. Thank you
> ![Kodi_20210505_082109](https://user-images.githubusercontent.com/73711940/117157316-bdb0df00-ad7b-11eb-93d4-1653c113eebf.png)
> ![Kodi_20210505_082129](https://user-images.githubusercontent.com/73711940/117157337-c1446600-ad7b-11eb-8958-d698857b4cf5.png)

Is that netflix home ? you can't , thats how that style is made to be seen . you can change the aspect a bit i think thats it . if you want more widgets fit into a single page dont' use the netflix style and use aura home .

**Comment by SerpentDrago** [comment]
>  short.kodi.mp4 
> @inb4after here is the video for the next up widget isdue
> Thank you

what happens if instead of going to the info page on click you just play (its a skin setting - default action )

**Comment by inb4after** [comment]
@deyooluv @wsx79 

Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).

Not tested with cloud/non-local items though, so I need your help for this.

I highly recommend switching to using TMDBHelper widgets instead. Skin Helper Widgets are old and the plan is to remove any other dependancies that are pretty much deprecated or don't give the proper info.

Please let us know your results, and if any new bugs occur.

**Comment by inb4after** [comment]
@deyooluv Go to Settings > Preferences row > TV Hubs > TV Genre Hub Items > Change "Widget style" for all the genres to the one you want.

**Comment by deyooluv** [comment]
> @deyooluv @wsx79
> 
> Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).
> 
> Not tested with cloud/non-local items though, so I need your help for this.
> 
> I highly recommend switching to using TMDBHelper widgets instead. Skin Helper Widgets are old and the plan is to remove any other dependancies that are pretty much deprecated or don't give the proper info.
> 
> Please let us know your results, and if any new bugs occur.

@inb4after this fixed the play button for next up widget items however there is a new issue.  The netflix play button is missing for add-on in the information page of both movies and tv shows. One will have to bring the play in the context menu to play movies or TV shows. Themoviedb hellper add-on seems to be the only add-on without the missing play button in both movies and TV shows.
Thank you

**Comment by SerpentDrago** [comment]
netflix info page of what exactly . Real library items ? tmdb helper library items ? addon content ?  from a widget or directly in the addon ? 

you need to be specific so i can replicate

**Comment by deyooluv** [comment]
> netflix info page of what exactly . Real library items ? tmdb helper library items ? addon content ? from a widget or directly in the addon ?
> 
> you need to be specific so i can replicate

the tv shows from next up widget can play now after fix made however there is a new issue that came up after the fix. TV shows and movies from Add-on don't have a play button. The movie helper add-on seems to be on add-on with the play button for both tv shows and movies

**Comment by SerpentDrago** [comment]
What addon ? exactly how to reproduce ?  what show or movie ? also Shows are not going to have a play button its a SHOW , there is nothing to play on a Show item , you need to pull up a episode . 

You need to be Specific on exactly where your going and what your clicking

**Comment by deyooluv** [comment]
> What addon ? exactly how to reproduce ? what show or movie ? also Shows are not going to have a play button its a SHOW , there is nothing to play on a Show item , you need to pull up a episode .
> 
> You need to be Specific on exactly where your going and what your clicking

Sorry for the confusion. When I am talking about show I mean episode. Hopefully this video gives you a better idea

https://user-images.githubusercontent.com/73711940/117325870-5e6fcf00-ae4e-11eb-966a-9113217ca090.mp4

**Comment by SerpentDrago** [comment]
Thank you , replicated it with fen  Episode, This didn't happen in seren or tmdb helper 

![image](https://user-images.githubusercontent.com/21133858/117326878-135eb780-ae60-11eb-99f6-5e678af2b4c4.png)

**Comment by SerpentDrago** [comment]
But FYI , why do you have default action set to info ? it really shouldn't be . You can set skin settings so its the default action for Home screen widgets or hubs . but you prob shouldn't set KODI's default action to info . it just doesn't work that well , say if you clicked clear cache in a addon setting menu , etc etc . 

Theres Skin settings default action , and Kodi settings . Your issue is still a issue , just a little FYI

**Comment by deyooluv** [comment]
> But FYI , why do you have default action set to info ? it really shouldn't be . You can set skin settings so its the default action for Home screen widgets or hubs . but you prob shouldn't set KODI's default action to info . it just doesn't work that well , say if you clicked clear cache in a addon setting menu , etc etc .
> 
> Theres Skin settings default action , and Kodi settings . Your issue is still a issue , just a little FYI

I have always used the default action as show information in any skin I used and I have never had issues. It allows me read the plot better. It also brings a better feel. Thanks for the heads though

**Comment by SerpentDrago** [comment]
JUST FYI , we can replicate the issue , and it relates to the "quick fix " done to playbuttonworkaround branch . fix one thing break another . 

It will be looked at , more info will be posted if needed . for now FYI play button works on matrix branch . but then off course your back to your org issue lol , pick your poison for now . we are taking a break 

Thanks for the report and testing !

**Comment by inb4after** [comment]
@deyooluv @wsx79 

Play button for addons issue was fixed, please use [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing) and also please check if the original issue has returned.

**Comment by SerpentDrago** [comment]
Testing results (testing branch) , 

WIdget > Additional Widgets > Skin helper Service Widgets > Episodes > Next Episodes 
* For Strm library items , Play Works great and triggers tmdb helper player selection when play is clicked , choosing seren smart play player triggers scraping for the correct episode . Fully working fine . 
*  for Real Library items ,Play  Seems to work Great and Episode plays when clicked 

All Tests passed 


Direct browsing TMDB helper Episode Item > info (netflix) > play  
Works ! 

Direct Browsing Seren Episode item > info(netflix) > play 
Works ! 

Direct Browsing Fen Episode Item > info (netflix ) > play
Works ! 


All seems working

**Comment by deyooluv** [comment]
> Testing results (testing branch) ,
> 
> WIdget > Additional Widgets > Skin helper Service Widgets > Episodes > Next Episodes
> 
> * For Strm library items , Play Works great and triggers tmdb helper player selection when play is clicked , choosing seren smart play player triggers scraping for the correct episode . Fully working fine .
> * for Real Library items ,Play  Seems to work Great and Episode plays when clicked
> 
> All Tests passed
> 
> Direct browsing TMDB helper Episode Item > info (netflix) > play
> Works !
> 
> Direct Browsing Seren Episode item > info(netflix) > play
> Works !
> 
> Direct Browsing Fen Episode Item > info (netflix ) > play
> Works !
> 
> All seems working

I can confirm it is working. Thank you

**Comment by SerpentDrago** [comment]
Will be closed when merged to matrix :) but thanks for the testing and feedback !! ;0

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.5
