### ISSUE TITLE
Posters showing icon in "View mode list" and not appearing in "Poster wall".

### ISSUE THREAD

**Issue by Stigmatised** [SerpentDrago/skin.auramod#69]
![Capture3](https://user-images.githubusercontent.com/34610024/117098350-38f2a080-ad3c-11eb-9db6-304af64395bc.PNG)
![Capture](https://user-images.githubusercontent.com/34610024/117098351-38f2a080-ad3c-11eb-9f87-e7a0a8aed48d.PNG)
![Capture2](https://user-images.githubusercontent.com/34610024/117098352-398b3700-ad3c-11eb-8c93-5147c64524d9.PNG)

So I have been running into an issue where when I enter into a TV show that has multiple seasons it either shows no folder for each season (even when there is correct artwork in the directory) or it shows nothing at all.

I've also attached a picture that shows the landscape artwork showing correctly.

This is occuring in TV Shows by the way, not files/tv shows. This also does not reoccur with addons like Seren and shows correctly. Even if I manually update the artwork within kodi it still doesn't show/show correctly. These are my files on my hard drive by the way in case it wasn't clear.

This also only occurs on this skin. I have changed to other skins and it shows correctly.

Any help? Hopefully its a simple fix I am missing. Not sure if a log was necessary but if so let me know.

**Comment by SerpentDrago** [comment]
What version of auramod are you using , and what version of kodi , 

Also are these real Library files or tmdb helper library files ?

**Comment by SerpentDrago** [comment]
Also exactly what are you clicking doing to get to that section ?  cause the only way we can replicate it is if we go files > tvshows which is directly browsing a library source , which is not the proper way to display your tv show library

**Comment by Stigmatised** [comment]
Auramod is version 1.0.3.4 and Kodi is the official release on Windows 10. These are real library files and the way I replicate it is by  scanning files in as TV shows and then selecting TV Shows. I'll get a screenshot later as I'm not at that computer at the moment.

**Comment by SerpentDrago** [comment]
Selecting tv shows , you mean clicking the default menu item called "TV Shows" ?    cause by default that leads to tmdb helper , not the tv show library . 

what is that menu your clicking action set to ?  You need to be much more descriptive , and show us your actual menu actions or category shortcut actions your using to get to that section

**Comment by SerpentDrago** [comment]
You need to point whatever menu item your using to point to  Video library > tv shows > bla bla   not video library > files > bla bla 

Don't directly browse library source files  . you need to browse the actual library

**Comment by Stigmatised** [comment]
Sorry!

Okay so when I scan my video files I can scan them as Movies/Shows etc. Then I have two categories showing above files for each. I've attached a screenshot showing this screen.

Its from this screen that I hit into either Movies or TV shows (both are setup on the main home screen as shortcuts). I've attached two more screenshots showing the customize home menu screen and the shortcuts that are setup and what Kodi refers to them as.
![Capture2](https://user-images.githubusercontent.com/34610024/117218379-02b33080-add1-11eb-812b-aa05ab576afc.PNG)
![Capture3](https://user-images.githubusercontent.com/34610024/117218380-034bc700-add1-11eb-9f84-11ff34efd84f.PNG)


![Capture](https://user-images.githubusercontent.com/34610024/117218226-c1228580-add0-11eb-8723-34e628ef9d84.PNG)

**Comment by inb4after** [comment]
There's a major bug with Kodi itself. The path you're using is a container which says the Container.Content is "episodes" instead of "seasons", even if the season folders and the TV show top folder are named correctly according to https://kodi.wiki/view/Naming_video_files/TV_shows

Use Video library > TV Shows > Titles as the source instead.

**Comment by SerpentDrago** [comment]
![image](https://user-images.githubusercontent.com/21133858/117218763-c7653180-add1-11eb-9b6d-eeeea82b34c1.png)

we need to see that , you showed us the "movie" menu item

**Comment by SerpentDrago** [comment]
Don't ever browse via "files" those are for kodi library sources , you point a menu item to your Library not to the Library files directly :)

**Comment by Stigmatised** [comment]
Sorry thought I attached a screenshot of the TV shows. Here.
![Capture](https://user-images.githubusercontent.com/34610024/117219122-99ccb800-add2-11eb-88e2-f5d9b6ef7282.PNG)
I've included a video too showing everything else.

https://streamable.com/o7ifd7

**Comment by Stigmatised** [comment]
I believe I do have it setup in the way you just mentioned, unless I'm misunderstanding/mistaken.

**Comment by SerpentDrago** [comment]
It does appear you do , i have no idea whats going on , we can't replicate your setup unless we browse from FILES > library source . are you SURE your on latest auramod matrix branch from this repo ?   What meta scraper do you have set for that library source ?  you sure you have the content type set to shows ?

**Comment by SerpentDrago** [comment]
Can you delete your tv shows menu and remake it , making sure after your done it rebuilds the menu

**Comment by Stigmatised** [comment]
Working on it right now!

**Comment by SerpentDrago** [comment]
Also i think your just behind in auramod versions , we fixed this issue a bit back :) 

Sorry i mean inb4after did :)

**Comment by inb4after** [comment]
> 
> 
> Working on it right now!

Our bad. No need to do anything except to update AuraMOD to latest Matrix branch from this repo. You're on 1.0.3.4 and we're on 1.0.4. This issue was fixed in between these versions.

**Comment by Stigmatised** [comment]
Okay well already changed the scraper as I got paranoid and thought the scraper was doing it (had Themoviedb instead of themoviedb tv version but the original was actually correct). Just updated the skin and rescanning now to see if it works.

**Comment by Stigmatised** [comment]
![Capture](https://user-images.githubusercontent.com/34610024/117220606-8ec75700-add5-11eb-8030-1a537e01a1a4.PNG)
Problem solved. Thanks for the help guys. This has been bugging me so much. :D

**Comment by inb4after** [comment]
> 
> 
> Okay well already changed the scraper as I got paranoid and thought the scraper was doing it (had Themoviedb instead of themoviedb tv version but the original was actually correct). Just updated the skin and rescanning now to see if it works.

Either one works, but you should prefer the python one as it's more recent and any issues with it were fixed/worked around in AuraMOD (It's still in Testing branch at the current time, but it will be merged soon)

Glad to hear this specific issue has been resolved!

**Comment by SerpentDrago** [comment]
Yeh def use the TMDB Python  scrapers , they fetch clearart and more meta  (make sure you go into its settings and enter fanart key and tmdb keys ! )
