### ISSUE TITLE
[Bug] Color Cycling & Blur  : Not Working in Matrix

### ISSUE THREAD

**Issue by JacopoV** [SerpentDrago/skin.auramod#7]
Hi,

first thanks for bumping up the version to be usable with Matrix.

I found the Color Cycling depending on the cover art (the best feature for Aura) is not working.
So the variables "highlight" and "highlight2" remain all the time the same.

By any chance that you can pin point me where the problem could it be? Maybe a module or something.

Many thanks!!

**Comment by Goldenfreddy0703** [comment]
Its the colorbox Script cause the dependency was not satisfied and it was python.version 2.25.0

If they update this script to python 3 capable then maybe the Color Cycling will work again. 

Here is the developer of that script but i don't think he will be updating it soon sense it was left abandoned sense 2018.
https://github.com/BADMS/script.colorbox

**Comment by JacopoV** [comment]
Thanks, i kinda suspected that. I haven't coded python in ages but i ll give a try, see if can compile locally with  python 3. 

EDIT : infos here at page 12 : https://forum.kodi.tv/showthread.php?tid=318626&page=12&highlight=script.colorbox

**Comment by SerpentDrago** [comment]
Yes will have to wait on a working matrix version of colorbox

**Comment by JacopoV** [comment]
Yeah it seems like. Try to get my hands on it but it seems hard 😅.

@SerpentDrago you can close the ticket if you want, it's unrelated with your work 😉

**Comment by SerpentDrago** [comment]
i'll keep it open till resolved but thanks

**Comment by JacopoV** [comment]
Cool. If you get your hands on the zip, could you please tag me here? Desperate to have the color cycling back 😉

**Comment by drinfernoo** [comment]
Seems this is also related to "Enable blur" on the "Effects" page in settings.

**Comment by drinfernoo** [comment]
I've made a PR to the official `script.colorbox` repo: https://github.com/BADMS/script.colorbox/pull/4

That should hopefully get merged, and fix color cycling, color matching, and blur for this (and any other) skin.

**Comment by SerpentDrago** [comment]
https://github.com/drinfernoo/script.colorbox/tree/matrix

Please if somone could install and check they have no issues. I'll close this pr and update Readme

Thanks @drinfernoo

**Comment by drinfernoo** [comment]
For what it's worth, I still think that for color matching and/or blur, the TMDbHelper service monitor is probably a better solution in the long run. It doesn't cover color cycling, nor all of the different effects that colorbox does, but would probably cover the most used cases, and reduce the footprint of the skin and related services.

**Comment by SerpentDrago** [comment]
This should be fixed , issue closed
