### ISSUE TITLE
Quick play is broken - Seren only feature 

### ISSUE THREAD

**Issue by SerpentDrago** [SerpentDrago/skin.auramod#71]
Quick play button on Netflix info for SHOWS in Seren is currently not working.

To be clear the quick play feature is only for seren shows as its supposed to trigger a quick resume in seren (seren only feature ) 

Prob a bad path , Low priority

**Comment by SerpentDrago** [comment]
Seren SHOW item > context menu > quick resume  (what the Quick play button should be doing ) 

also errors for me , so this is a combination of Seren issue and auramod issue

**Comment by inb4after** [comment]
@SerpentDrago 

Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).

Please let us know if any further bugs occur.

**Comment by SerpentDrago** [comment]
Test results 

Seren Show item > info > quick play , properly triggers Seren's  Quick resume function . And plays the next unwatched episode or S01E01 if all watched or none watched . 

Tmdb helper is also showing Quick Play and it does trigger Player selection and will send to seren to scrape , but seren  just plays the first episode and season even if your say on the 4th season . Trakt is authed in both seren and tmdb helper , and tmdb helper shows proper watched status for show in question .  I think this is just a Player issue with quick play player for  seren 

I have no idea if and how this could even work , prob needs a special player , tried with both smart play players and normal same S01E01 scrape happens . 

Results does appear its working for seren items , For tmdb helper items it will need to be looked at if even possible . but not really a issue IMHO as this feature was only ever made to work for seren items

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.5

The TMDBHelper line uses Season 1, Episode 1 as a workaround for quick playing. Trakt UpNext lookups (or playlist building like Seren) through TMDBHelper still needs to be looked into.
