### ISSUE TITLE
Movie Ratings issue ie PG, R, PG13

### ISSUE THREAD

**Issue by adamosborne83** [SerpentDrago/skin.auramod#74]
Hi,
Please see the video attached,
But I a nutshell it shows if movies are R rated, PG etc, but if I then go into Spotlight, whatever the rating of that movie is, shows on all others, don't get me wrong Moana is scary.... but don't think R rated scary.....

http://imgur.com/a/6iDsxvm

**Comment by Dealz-416LS** [comment]
Experiencing the same issue.

Currently on the [RatingPlusTesting](https://github.com/SerpentDrago/skin.auramod/tree/RatingsPlusTesting) Branch.

All widget items are displaying the same Rating as the Spotlight item, Example if the Spotlight item is 'TV-MA' then all widget items under that spotlight will also display 'TV-MA' regardless of their actual rating.

Happens with both TV Show and Movie Spotlight.

**Comment by SerpentDrago** [comment]
What home style are you using ? what style spotlight widgets ?  Do you have omdb key entered into tmdb helper ? and have the service monitor for tmdb helper enabled in its settings and in the skin settings ? where are you seeing ratings on a widget item in home ? on the widget bar ? how even are you viewing a spotlight widget at the same time when focused on a normal widget Generally it scrolls down the page you can't see both at the same time .

**Comment by SerpentDrago** [comment]
https://user-images.githubusercontent.com/21133858/117693424-060d3a00-b18c-11eb-9468-3848076f6063.mp4


still dont' have enough info to replicate

**Comment by SerpentDrago** [comment]
Ok you guys are talking about Netflix Home's BUILT in spotlight on the currently focused item , not changing and being "Stuck" with whatever the spotlight widget (independent ) had . 


https://user-images.githubusercontent.com/21133858/117694255-ecb8bd80-b18c-11eb-8b3b-2c2e380b9ee1.mp4


Replicated , In the future Specify the Home style used , as it matters . but yeh figured it out though the video user posted thanks .

**Comment by SerpentDrago** [comment]
This issue also only happens if you have enabled the Spotlight widget on that menu . IMHO you shouldn't be using the spotlight widget when using netflix home style at all . as whats the point ? that style has its own built in Spotlight Showcase on the currently focused item .

**For now simply disable the Spotlight widget for your menus when using netflix home** till this can be looked at . 
As you can see here with spotlight widget disabled for the menus > 


https://user-images.githubusercontent.com/21133858/117694920-b3348200-b18d-11eb-8810-59a66e2db703.mp4



Already spotlight widgets when using netflix home are busted and not displaying fanart / etc and are wonkey and look bad .

**Comment by adamosborne83** [comment]
Hey Serpent, firstly apologies for the shitty description of the issue and great from you for figuring out what I meant and how I did it.

The only reason I have spot light of with next flix is sometimes I just decide what to watch from what spotlight shows me (saves me flicking)

It's nothing major as in regards to the bug, just something I thought I'd mention.

Cheers though

**Comment by SerpentDrago** [comment]
no problem , its def a bug . but spotlight widgets have always been a bit buggy with netflix home style . I can be looked at sometime . Thanks

**Comment by SerpentDrago** [comment]
@adamosborne83 Side note , i noticed your fanart (the background) shows on your Spotlight  (in your video you can see matrix reloaded , it has both clearart working and background (fanart) , what is that widget pointed to ?

**Comment by adamosborne83** [comment]
@SerpentDrago hey fella in reference to your side note about fanart etc, 
Please see below a pic of what I have and a small video, if you want anymore info please let me know.

Thank you for the additional help and heads up fella.


http://imgur.com/a/Fczmhva

http://imgur.com/a/hvt0T8e

**Comment by inb4after** [comment]
@adamosborne83 

The MPAA rating should now be fixed in [Ratings-and-artwork-from-Only-TMDB-Helper](https://github.com/SerpentDrago/skin.auramod/tree/Matrix-Ratings-and-artwork-from-Only-TMDB-Helper) branch.

Please do a quick test by installing this branch, and you can then return to RatingPlusTesting branch which currently has more fixes. Planning on merging it all together soon.

Let us know if it causes any further bugs.

**Comment by adamosborne83** [comment]
@inb4after 
Now this going to be a rookie question.

I'm using the Testing Branch atm on my devices as love that the Cast and More feature is foxes.

Now if I use another branch will it over write the testing branch too

Just you put its fixed in

The MPAA rating should now be fixed in Ratings-and-artwork-from-Only-TMDB-Helper branch


BUT You've said it's fixed it Testing :-)

**Comment by inb4after** [comment]
> 
> 
> @inb4after
> Now this going to be a rookie question.
> 
> I'm using the Testing Branch atm on my devices as love that the Cast and More feature is foxes.
> 
> Now if I use another branch will it over write the testing branch too
> 
> Just you put its fixed in
> 
> The MPAA rating should now be fixed in Ratings-and-artwork-from-Only-TMDB-Helper branch
> 
> BUT You've said it's fixed it Testing :-)

You can safely install any branch over any branch without losing any data, as long as you don't uninstall AuraMOD entirely.

The bugs of the Ratings branch that were fixed in Testing branch will be present, but you can easily fix this by installing Testing branch again after quickly testing the Ratings branch.

**Comment by adamosborne83** [comment]
@inb4after 
Is this fixed in testing branch? Just still happening Mr

**Comment by inb4after** [comment]
> 
> 
> @inb4after
> Is this fixed in testing branch? Just still happening Mr

The fix is only in [Ratings branch](https://github.com/SerpentDrago/skin.auramod/tree/Matrix-Ratings-and-artwork-from-Only-TMDB-Helper) not Testing branch at the moment (as MPAA is technically a rating)

**Comment by SerpentDrago** [comment]
> @SerpentDrago hey fella in reference to your side note about fanart etc,
> Please see below a pic of what I have and a small video, if you want anymore info please let me know.
> 
> Thank you for the additional help and heads up fella.
> 
> http://imgur.com/a/Fczmhva
> 
> http://imgur.com/a/hvt0T8e

ohh yeh i figured it out , seems you have to have this setting enabled for the background to show on that widget in that style > 
![image](https://user-images.githubusercontent.com/21133858/117824260-5512a800-b23c-11eb-8915-078877b06fcd.png)

**Comment by Dealz-416LS** [comment]
> 
> 
> @adamosborne83
> 
> The MPAA rating should now be fixed in [Ratings-and-artwork-from-Only-TMDB-Helper](https://github.com/SerpentDrago/skin.auramod/tree/Matrix-Ratings-and-artwork-from-Only-TMDB-Helper) branch.
> 
> Please do a quick test by installing this branch, and you can then return to RatingPlusTesting branch which currently has more fixes. Planning on merging it all together soon.
> 
> Let us know if it causes any further bugs.

Just confirming on here also that this is fixed, didn't notice any new bug(s) as a result of this fix.

**Comment by adamosborne83** [comment]
> > @SerpentDrago hey fella in reference to your side note about fanart etc,
> > Please see below a pic of what I have and a small video, if you want anymore info please let me know.
> > Thank you for the additional help and heads up fella.
> > http://imgur.com/a/Fczmhva
> > http://imgur.com/a/hvt0T8e
> 
> ohh yeh i figured it out , seems you have to have this setting enabled for the background to show on that widget in that style >
> ![image](https://user-images.githubusercontent.com/21133858/117824260-5512a800-b23c-11eb-8915-078877b06fcd.png)

In reference to my set up mate,is that OK?

Cheers fella 👍
