### ISSUE TITLE
[Bug] Volume Slider when it appears top right has a dark black shader to it..

### ISSUE THREAD

**Issue by Goldenfreddy0703** [SerpentDrago/skin.auramod#8]
**Describe the bug**
I don't really think this is a bug but when i was using your skin, i turned the volume up or down when playing a movie and on the main menu and you see a dark shade that's not supposed to be there.

**To Reproduce**
1. Play a random video on this skin.
2. Mess with the volume buttons using (-) or (+) button. 
3. Notice the dark back shader filling half of the top right of the screen.
4. Try this on the menu too and you can notice it. 

**Expected behavior**
To not have the dark black shade filling up half of the top right corner

**Screenshots** 
![Kodi 19 Volume Bug](https://user-images.githubusercontent.com/62456796/111893436-0c2b3980-89d9-11eb-8bb7-8a04698474e9.PNG)
![Kodi 19 Volume Bug 2](https://user-images.githubusercontent.com/62456796/111893440-0f262a00-89d9-11eb-9922-341e40efbd86.PNG)
These two are the images that have the bugged volume shade that were from kodi 19

![kodi 18 Volume Default](https://user-images.githubusercontent.com/62456796/111893459-32e97000-89d9-11eb-8b1f-067f33f82106.PNG)
![kodi 18 Volume Default 2](https://user-images.githubusercontent.com/62456796/111893460-341a9d00-89d9-11eb-8cfe-c4b7c2864c49.PNG)
These two are the images that do not have the bugged volume shade that were from kodi 18

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version Kodi 19 Matrix

**Additional context**
I did not think this was a bug at first until i compared them side by side.

**Comment by SerpentDrago** [comment]
I've never once in my life seen someone use volume control INSIDE kodi . best to use the volume on your tv or speakers . You should not be changing  volume on the source device (kodi)  . very bad practice

it appears to be  using the shade box i have implemented to make notifications easier to see . 

Ugg this will prob be on the back burner as its not a critical feature most will ever see .. but i may end up tackling it if i decide to work on making notifications prettier .

Its not a kodi 19 issue , its a "issue" that is on my version of auramod in general , as i made mods to how notifications are displayed. had no idea the same stuff was used for volume osd ugggg lol  . I may end up just removing the heavy shade idk . needs a rework for sure

**Comment by Goldenfreddy0703** [comment]
ok thank you and the main reason im using the kodi volume control is cause im using Libreelec on your skin and its working really wall.

**Comment by SerpentDrago** [comment]
Still why would you use volume in kodi ? doesn't your tv have volume ?   Kodi is a player/app  doesn't matter how your running it . you want to control volume on the amplifier not the source (amplifier being a tv speakers  / soundbar / reciever / etc ) 

This doesn't mean this is not a visual issue though , just saying , never noticed the issue cause ... again who the hell uses volume in kodi :) lols .  Amplification 101 , dont' touch input volume , set it once and forget it . control it with end amplifier

**Comment by Goldenfreddy0703** [comment]
I mean the reason why I use the volume for kodi is that you can get more amplification with it and you can use it for other devices like Bluetooth devices and speakers and other stuff.

**Comment by SerpentDrago** [comment]
had a sec This morning  , did a quick fix as this was a easy one lol  , see if its better now on latest version . 1.0.3.3

**Comment by Dealz-416LS** [comment]
@SerpentDrago 

I didn't have an issue with this specifically as I didn't use the Kodi volume control but I tried out 1.0.3.3 to see how it looks and the change looks good to me, It now looks like the last image above.

By chance would it be possible to make the same change to the 'Minimal busy loader" it also has the same large dark area behind it.

![Kodi_20210322_134614](https://user-images.githubusercontent.com/54026944/112000381-db9cea00-8b15-11eb-8f3a-f189fec6424b.png)

**Comment by SerpentDrago** [comment]
I think that's considered a notification I'll look into it

**Comment by Goldenfreddy0703** [comment]
Hey thank you for fixing the volume issue, it looks so much better now and i cannot wait to put this on my raspberry pi. Thank you very much.

**Comment by SerpentDrago** [comment]
> @SerpentDrago
> 
> I didn't have an issue with this specifically as I didn't use the Kodi volume control but I tried out 1.0.3.3 to see how it looks and the change looks good to me, It now looks like the last image above.
> 
> By chance would it be possible to make the same change to the 'Minimal busy loader" it also has the same large dark area behind it.
> 
> ![Kodi_20210322_134614](https://user-images.githubusercontent.com/54026944/112000381-db9cea00-8b15-11eb-8f3a-f189fec6424b.png)

want me to just remove the background shade all together for that one ?  Not like it needs to be read really its just a busy dialog

**Comment by SerpentDrago** [comment]
![image](https://user-images.githubusercontent.com/21133858/112022395-a6d66600-8b08-11eb-9a0e-ea56e9785d9e.png)


Hows that , also will apply to notifications .. i think

**Comment by Dealz-416LS** [comment]
@SerpentDrago Oh, looks good! 🙂

I think it's wide enough to accommodate different notifications when they appear.

**Comment by SerpentDrago** [comment]
> @SerpentDrago Yes please, I do agree it's just the busy dialog there isn't anything to read when it comes up. Thank you!

problem is the same style is used for both and i'd rather keep it that way .. 

anyways change pushed (no version bump )

**Comment by Dealz-416LS** [comment]
> > @SerpentDrago Yes please, I do agree it's just the busy dialog there isn't anything to read when it comes up. Thank you!
> 
> 
> 
> problem is the same style is used for both and i'd rather keep it that way .. 
> 
> 
> 
> anyways change pushed (no version bump ) 

I understand, I didn't see your edit till after but the reduced size of the background shade I think looks completely fine.

Great, I'll try it out now...

**Comment by Dealz-416LS** [comment]
@SerpentDrago Thank you! it looks so much better now.

I think this issue #8 can be closed?
