### ISSUE TITLE
[BUG]Resume progress bar & indicators.

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#80]
Resume progress bar/indicators don't change to match progress of items being watched via Seren.

Indicators
![IMG_0851](https://user-images.githubusercontent.com/54026944/117814993-e560e500-b25c-11eb-80dc-e9fe6a7f1bdd.JPG)
![IMG_0852](https://user-images.githubusercontent.com/54026944/117817996-11ca3080-b260-11eb-9724-57cd27be8d47.JPG)

Resume Progress Bar
![IMG_0850](https://user-images.githubusercontent.com/54026944/117815010-ea259900-b25c-11eb-99fb-81e7aa3c40bc.JPG)

I think @drinfernoo made a change(s) to Seren in 2.0.17 so it correctly calculates and provide progress for Skins that support it but the skin is not displaying progress.

Resume progress bar and indicator do not change regardless of the progress made in the show/movie.

**Comment by SerpentDrago** [comment]
This has been a long long long standing issue . and seren doesn't fill in the info needed for progress bars to work . as if it did , it causes a additonal non working resume context menu item on items (built into kodi) that won't resume . confusing users.

Trust me I wish this could work .. and i'll look into it yet again (this is prob the 4th time i would have asked nix to just give me the damn option ) but yeh . 


If you play local media , you will clearly see it works perfectly fine . 

![image](https://user-images.githubusercontent.com/21133858/117819858-f3e8d580-b237-11eb-9305-100895dd5712.png)


Again this is a Seren issue . 

I will look into if seren could mybee fill out a different variables and skin can just try using that but thats super super hacky way of doing it and would only work for skins specially coded to support it .  I have asked Dr if he did anything concerning this issue .

**Comment by SerpentDrago** [comment]
as far as the indicators . i have no idea what you mean . that indicator shows that there is a resume point .. which there is .. and a check shows its been marked as watched .. exactly whats wrong in your picture ? 

![image](https://user-images.githubusercontent.com/21133858/117820647-b9336d00-b238-11eb-9c05-bda19e7875e3.png)

**Comment by Dealz-416LS** [comment]
Thank you for the explanation, Hopefully you can get the option from Nix this time.

Oh i thought the indicator displayed actual progress and filled out 1/2, 3/4 etc depending on the progress made similar to AH. It's just a static indicator to show in progress regardless of how much progress.

**Comment by drinfernoo** [comment]
@Dealz-416LS It would likely work that way with the proper info filled out (which we established that Seren didn't currently fill). I'm not sure if AuraMOD does have multiple icons for various progress thresholds, but that is the general idea behind that icon in other skins.

**Comment by SerpentDrago** [comment]
Yeh it would be the same as the progress bars . without the info for that , then you couldn't change the indicator used . 

![image](https://user-images.githubusercontent.com/21133858/117823207-36f87800-b23b-11eb-8fb8-e743488b4c0d.png)
![image](https://user-images.githubusercontent.com/21133858/117823883-f51c0180-b23b-11eb-9f5b-3316861b39d4.png)



seems you and dr are right .. haha never noticed that (that's for a local library item , real file )  

seems to work perfectly . its all just a matter of seren filling in that info . 

Welp , blame seren , closing this issue

**Comment by inb4after** [comment]
@SerpentDrago @Dealz-416LS @drinfernoo 

Working for me in Seren 2.0.18+matrix.1, here are some screenshots before I update Seren.

<details>
  <summary>80% remaining</summary>
  
https://i.imgur.com/k6RWaod.jpg
https://i.imgur.com/kB2aieM.jpeg
  
</details>

<details>
  <summary>47% remaining</summary>
  
https://i.imgur.com/9FmEqiZ.jpeg
https://i.imgur.com/2ev7nMk.jpg
  
</details>

<details>
  <summary>27% remaining</summary>
  
https://i.imgur.com/KNhjFKK.jpeg
https://i.imgur.com/CC78eDc.jpg
  
</details>

**Comment by Dealz-416LS** [comment]
@inb4after 

Resume and Indicator working makes sense to me as wouldn't these changes in Seren .17 by @drinfernoo result in it working

> Fix resume progress indicators
> Calculate resumetime at bookmark insert for movies

Doesn't work for me in .19 so maybe something got broken somewhere.

EDIT: 

I guess this explains why it doesn't work on .19

> Temporarily disable totaltime progress indicators as they break our resume on Matrix

**Comment by inb4after** [comment]
As soon as I updated to Seren 2.0.19 I am no longer able to play or resume the item using the Play or Play from beginning button in Netflix Info as it now throws a Seren error and my Seren widget disappeared.

Everything was working perfectly in 2.0.18 including resume points, the only thing that doesn't work is the Kodi built in context menu action to "Play from beginning" or "Reset resume position".

Instead you should go to Trakt manager and reset playback progress in order to play from beginning. It has always worked like this for Seren. However, 2.0.19 is causing some further bugs on my end.

**Comment by drinfernoo** [comment]
That's correct, it was "fixed" in 2.0.18, but introduced a bug with the resume logic, so it was reverted again for 2.0.19.
