### ISSUE TITLE
Translation Strings

### ISSUE THREAD

**Issue by wsx79** [SerpentDrago/skin.auramod#82]
It seems that some translation strings are not perfect locate.
I translate all skin strings in Italian but many parts are in english yet.

It need to debug every line in skin and modify xml for the ID not translate add in string.po
![1](https://user-images.githubusercontent.com/68690475/117841737-924b5a00-b27d-11eb-98b1-69de31a24be7.jpg)
![2](https://user-images.githubusercontent.com/68690475/117841743-937c8700-b27d-11eb-930b-58ff6f2a2e26.jpg)

**Comment by SerpentDrago** [comment]
Yeh all that would have to be gone though and localized , once localized anyone can then make a pr with translations for whatever language they want .  

So in short SkinSettings.xml for sure needs to be gone though i see a BUNCh there not localized

**Comment by SerpentDrago** [comment]
https://kodi.wiki/view/Label_Parsing
https://kodi.wiki/view/Language_support

**Comment by wsx79** [comment]
Push commit #84 #85 for testing translation issue.
Need to be complete

**Comment by SerpentDrago** [comment]
@wsx79 you know once you make a PR from one of your branches , you can simply commit / change stuff to that branch (say patch1 ) and it will auto add it to the existing pr right ? 

Also off course the main language strings.po will need to be updated to (english)

**Comment by SerpentDrago** [comment]
you know you can just commit them to your own fork / branches to test , Then you or me can simply make a pr from that branch on your fork to whatever branch i need to on auramod . 

aka do all your work in a branch / branchs on your fork , and then worry about making a pr to auramod after your done ;0 


Also fyi We just did a major merge into Matrix , version 1.0.5 , it contains all the ratings and testing fix's . Matrix is again the most updated branch

**Comment by SerpentDrago** [comment]
The cleaner and proper way to make prs , is to Fork to your own github account , make a branch from the one your modifying from your fork . then do all your code changes though github desktop + editor like notepad ++ , you then commit and push those changes with github desktop to YOUR branch on your account .  after you done make a single pr from your branch to the correct branch here . 

it will make diff's and code changes much more clean and simple . vs using github web directly editing and letting it make various patch branches .

**Comment by SerpentDrago** [comment]
https://github.com/SerpentDrago/skin.auramod/tree/Localization-Cleanup

created a new branch  Just for this kinda stuff , In the future , please submit any changes to that branch , and if you add localization strings to base code that are new , please add them to the english strings.po file , makes my job a million times easier and i'll gladly accept . any existing "dirty" prs are closed , and will need to be redone , sorry . but we need to do this right and start fresh .
