### ISSUE TITLE
Include_Labels.xml

### ISSUE THREAD

**Issue by wsx79** [SerpentDrago/skin.auramod#87]
In include_labels.xml in testing by change the duration helper if try to change from 
Property(SkinHelper.ListItem.Duration.Hours) in Property(TMDBHelper.ListItem.Duration.Hours) it not work (all changes in duration)

line 1197
<variable name="infoline_duration">

line 1203
<variable name="infoview_duration">

**Comment by inb4after** [comment]
I think TMDBHelper Service Monitor only supports one InfoLabel for duration (in minutes).

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor

It would be Window(Home).Property(TMDbHelper.ListItem.Duration)

At the moment the skin is using the ListItem.Duration built-in InfoLabel as the main duration for most content, which does show as hours and minutes as you can select them using ListItem.Duration(h) or ListItem.Duration(mm).

**Comment by SerpentDrago** [comment]
> In include_labels.xml in testing by change the duration helper if try to change from
> Property(SkinHelper.ListItem.Duration.Hours) in Property(TMDBHelper.ListItem.Duration.Hours) it not work (all changes in duration)
> 
> line 1197
> line 1203

to help you and others in the future , you can reference exact lines , browse that file in this or your github (depending on what your trying to show , either This  auramod or your alterations on your fork  , and click the line number , click the 3 dots , and copy perm link 

![image](https://user-images.githubusercontent.com/21133858/117856314-7766ee80-b259-11eb-9f23-e198dee1f663.png)

https://github.com/SerpentDrago/skin.auramod/blob/002d53bcd883901795dab0ee9c392d50791c0a58/1080i/Includes_Labels.xml#L1197

Then just paste link here and it will directly reference the code :)
