### ISSUE TITLE
No Actor Thumbs  shown on spotlight when using "multi widget" spotlight style

### ISSUE THREAD

**Issue by SerpentDrago** [SerpentDrago/skin.auramod#9]
There is a known issue when pointing a Multi widget style spotlight to tmdb helper item . Something to do with Actor request needing more Parmenter's 

To replicate issue , Simply setup a Spotlight "multi widget " style . Error will display when that spotlight loads . And there will be a lack of Actor Thumbs

Should look like this > 

![image](https://user-images.githubusercontent.com/21133858/111912041-3ebb4d80-8a3e-11eb-9fed-083515be7f87.png)

instead looks like this and you get error on load 

![image](https://user-images.githubusercontent.com/21133858/111912055-5397e100-8a3e-11eb-95c3-cb7441343257.png)

**Comment by gtkingbuild** [comment]
Thank you very much for the information Serpent

**Comment by Dealz-416LS** [comment]
>Something to do with Actor request needing more Parmenter's (tmdb helper update broke existing implementation ) 
> 

@SerpentDrago Is this also the reason why navigating around "Cast & More" is buggy?

If I click on a cast member then try to navigate back I rubber band back to the cast member screen or get stuck in infinite loading or Kodi crashes, similar behaviour with the other categories (Similar, Recommended etc)

**Comment by SerpentDrago** [comment]
Considering the cast & more is all stuff coming from tmdb helper i would not be surprised .

**Comment by SerpentDrago** [comment]
-version 1.0.3.4
Temp removed cast thumbnails from Multi Widget spotlights , till proper fix can be figured out 

Issue will be Left open till it can be properly be resolved

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.14
