### ISSUE TITLE
Backing out of Movie Spotlight Causes Error

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#93]
Backing out of that menu causes a playback issue.
I've never used spotlights before, am I using it wrong? 
In this situation I have it pointed at library movie files(nas) genre's

Clicking on more info never loads.
And after clicking on play you also get an error.

Logs don't show anything. 

https://user-images.githubusercontent.com/17692472/118472675-f034d300-b6bd-11eb-8448-ac40521e966c.mp4

**Comment by SerpentDrago** [comment]
exactly what are you pointing the spotlight at , EXACTLY  , the exact path / options you choose when choosing the widget/action when configuring the spotlight. also what spotlight style do you have it set to ?

**Comment by inb4after** [comment]
It looks like the spotlight is pointed to `Video Library > Movies > Genres > Use as widget` which is incorrect. 
It should be `Video Library > Movies > Genres > Animation`.

Using genres as widget is rare to see, let alone pointing it to video library, as most people use regular lists as widgets such as Seren - Trending or TMDBHelper - Popular or even Seren/TMDBHelper addon genres, which are dynamic lists, while video library widgets are mostly static unless you add to library very often. I can see why it might be useful in your particular setup though!

Look into [AutoWidget](https://github.com/drinfernoo/plugin.program.autowidget) addon, it will further increase customization of widgets in AuraMOD.

**Comment by SerpentDrago** [comment]
Yes. You can point widgets to genre section of library or addon but you shouldn't point a spotlight to it. Why in the world would you? Its not going to show anything but a genre category lol.

Makes perfect sense on a widget though there's even a widget style for it.

**Comment by SerpentDrago** [comment]
Id suggest closing this issue unless there's more. Don't point spotlights to genre selection.  It serves 0 point.  there is no item to display meta info or play . , a more proper use of a section like that is a normal widget . 

which would appear like this > 
![image](https://user-images.githubusercontent.com/21133858/118655786-de375b00-b7b7-11eb-92fc-faa0dcd66b0c.png)
![image](https://user-images.githubusercontent.com/21133858/118655992-16d73480-b7b8-11eb-9f6c-67f036e0918b.png)
![image](https://user-images.githubusercontent.com/21133858/118656061-2a829b00-b7b8-11eb-90d0-d88cb245cfd0.png)
