### ISSUE TITLE
Need some clarifications if possible.

### ISSUE THREAD

**Issue by Nazim1981** [SerpentDrago/skin.auramod#95]
I have selected Spotlight>Movies>Seren>Superheroes
but spotlight not working for Movies or TV shows, only I can see descriptions with Black Screen and even trailer on that section is Blank but I can listen the sound of Movie or TV trailers.
https://i.postimg.cc/SKr7JM3t/image.png
https://i.postimg.cc/DZw05JZD/image.png

2- No Studio Logos in Home & Hub along side with Ratings. No Oscar & Top 250 Icons on Home .
3- Continued watching should show Progress Percentage on Posters .
4-There must be something in skin which causing Seren to Revoke Trakt API  frequently .

**Comment by inb4after** [comment]
1. For spotlight trailer to display, enable `Skin Settings > Home > Enable menu background image`. Alternatively, if you don't want to view/listen to spotlight trailers you can disable it entirely `Skin Settings > Library views > Disable spotlight trailer auto-play`.
2. You will need to enter some API keys to get the full ratings experience. This can be done in `Skin Settings > API settings > Metadatautils/TMDBHelper > API keys` and also don't forget to enter API keys into the addon you're using if applicable.
3. The progress percentage is already displayed on the poster, the circle icon will fill up depending on how much percentage is left. You will also see a red bar above the poster in the showcase info showing exactly how much % is left to watch.
4. The skin cannot cause this. Most likely a Seren issue, or an issue with your Trakt account specifically which should be taken up with Trakt support.

**Comment by Nazim1981** [comment]
> 1. For spotlight trailer to display, enable `Skin Settings > Home > Enable menu background image`. Alternatively, if you don't want to view/listen to spotlight trailers you can disable it entirely `Skin Settings > Library views > Disable spotlight trailer auto-play`.
> 2. You will need to enter some API keys to get the full ratings experience. This can be done in `Skin Settings > API settings > Metadatautils/TMDBHelper > API keys` and also don't forget to enter API keys into the addon you're using if applicable.
> 3. The progress percentage is already displayed on the poster, the circle icon will fill up depending on how much percentage is left. You will also see a red bar above the poster in the showcase info showing exactly how much % is left to watch.
> 4. The skin cannot cause this. Most likely a Seren issue, or an issue with your Trakt account specifically which should be taken up with Trakt support.

Thanks for your reply .
1- Yes  spotlight picture enabled which you suggest . Thanks
It is like that 
https://i.postimg.cc/s2zr7BHd/image.png         (Its dim in Full screen with Up Height widgets)

but I want spotlight picture like that

https://i.postimg.cc/1XFLTsf1/image.png
(Its not dim & when the pointer is on Movies icon left panel , Spotlight picture shows with a low height of widgets so that user can feel the enjoyment of spotlight pictures and when user went to home widget by pressing right and down to reach first widget then should spotlight vanish.  
 
2- All API updated. I was pointing out what was missing . 
see for example below picture it has Top250 Icon & Movie position ,Oscar , Studio Logo in HOME.
https://i.postimg.cc/rFkfNSCp/image.png

3-Movie Progress Refilling Round icon is not clear enough to know how much movie is left to watch , it should be somewhat similar see below picture  (Progress % on Posters )
https://i.postimg.cc/Zq4ZkBSY/image.png

4- You are right its Seren Trakt relationship who are causing to revoke API.

**Comment by inb4after** [comment]
1. Disable both `Skin Settings > Effects > Background overlay` and `Skin Settings > Effects > Background vignette`.
2. Working fine here, see [screenshot](https://i.imgur.com/Li7VQ5m.jpg). Are you using the latest version v1.0.6?
3. See above screenshot, which shows how much percentage is left.

**Comment by xyzfre** [comment]
> > 1. For spotlight trailer to display, enable `Skin Settings > Home > Enable menu background image`. Alternatively, if you don't want to view/listen to spotlight trailers you can disable it entirely `Skin Settings > Library views > Disable spotlight trailer auto-play`.
> > 2. You will need to enter some API keys to get the full ratings experience. This can be done in `Skin Settings > API settings > Metadatautils/TMDBHelper > API keys` and also don't forget to enter API keys into the addon you're using if applicable.
> > 3. The progress percentage is already displayed on the poster, the circle icon will fill up depending on how much percentage is left. You will also see a red bar above the poster in the showcase info showing exactly how much % is left to watch.
> > 4. The skin cannot cause this. Most likely a Seren issue, or an issue with your Trakt account specifically which should be taken up with Trakt support.
> 
> Thanks for your reply .
> 1- Yes spotlight picture enabled which you suggest . Thanks
> It is like that
> https://i.postimg.cc/s2zr7BHd/image.png (Its dim in Full screen with Up Height widgets)
> 
> but I want spotlight picture like that
> 
> https://i.postimg.cc/1XFLTsf1/image.png
> (Its not dim & when the pointer is on Movies icon left panel , Spotlight picture shows with a low height of widgets so that user can feel the enjoyment of spotlight pictures and when user went to home widget by pressing right and down to reach first widget then should spotlight vanish.
> 
> 2- All API updated. I was pointing out what was missing .
> see for example below picture it has Top250 Icon & Movie position ,Oscar , Studio Logo in HOME.
> https://i.postimg.cc/rFkfNSCp/image.png
> 
> 3-Movie Progress Refilling Round icon is not clear enough to know how much movie is left to watch , it should be somewhat similar see below picture (Progress % on Posters )
> https://i.postimg.cc/Zq4ZkBSY/image.png
> 
> 4- You are right its Seren Trakt relationship who are causing to revoke API.

Are these images from AuraMod Skin?

**Comment by Nazim1981** [comment]
> 1. Disable both `Skin Settings > Effects > Background overlay` and `Skin Settings > Effects > Background vignette`.
> 2. Working fine here, see [screenshot](https://i.imgur.com/Li7VQ5m.jpg). Are you using the latest version v1.0.6?
> 3. See above screenshot, which shows how much percentage is left.

1- It worked , Widget posters height went down when click left arrow 2 time on left panel . 
Dim issue solved by disabling transparency 
https://i.postimg.cc/52BGdfbf/image.png

2- Yes you have, may be it took some time to load for fresh install  , which I am checking in hurry.

3-BUT how on earth you are getting that percentage Red bar why I am not ?
https://i.postimg.cc/W3nfD8tC/image.png

Note : one thing I noticed I dont have any space left for Red bar Percentage on that area ? see that above picture 

Also where is the skin refresh button ? and how did you get Green percentage rating 94% Liked instead of star rating ?

**Comment by xyzfre** [comment]
> * Disable both `Skin Settings > Effects > Background overlay` and `Skin Settings > Effects > Background vignette`.
> * Working fine here, see [screenshot](https://i.imgur.com/Li7VQ5m.jpg). Are you using the latest version v1.0.6?
> * See above screenshot, which shows how much percentage is left.

I’m curious as well how are you getting the percentage bar that shows up in red in your screenshot never seen that in AuraMod it looks GREAT

**Comment by SerpentDrago** [comment]
it was a local library item. or from another addon that provides this info . most addons do not , its why you have never seen the bar before

FYI seren can not / is not providing the info to the skin needed to properly display the progress bar . i'm not getting into it but its a known issue in how seren does resuming and it ON PURPOSE doesn't report the info to the label needed for the skin to use , as it can mess up with its internal resume function .

**Comment by SerpentDrago** [comment]
@Nazim1981 3-Movie Progress Refilling Round icon is not clear enough to know how much movie is left to watch , it should be somewhat similar see below picture (Progress % on Posters )
https://i.postimg.cc/Zq4ZkBSY/image.png

Thats not how this skin is designed , it shows either a bar or a round icon

**Comment by Nazim1981** [comment]
> @Nazim1981 3-Movie Progress Refilling Round icon is not clear enough to know how much movie is left to watch , it should be somewhat similar see below picture (Progress % on Posters )
> https://i.postimg.cc/Zq4ZkBSY/image.png
> 
> Thats not how this skin is designed , it shows either a bar or a round icon

Basically we sat a little far from our 65'' TV , and its hard to get from round icon . 
OK 
 how did you get Green percentage rating 94% Liked instead of star rating ? Also where is the skin refresh button ? 
and also why cant we select View type in Category widgets ?
Studio Icon still missing from home screen . See inb4after above picture 
and a  request for polished bright Rating icons (right now its dull).

**Comment by inb4after** [comment]
> 
> 
> > @Nazim1981 3-Movie Progress Refilling Round icon is not clear enough to know how much movie is left to watch , it should be somewhat similar see below picture (Progress % on Posters )
> > https://i.postimg.cc/Zq4ZkBSY/image.png
> > Thats not how this skin is designed , it shows either a bar or a round icon
> 
> Basically we sat a little far from our 65'' TV , and its hard to get from round icon .
> OK
> how did you get Green percentage rating 94% Liked instead of star rating ? Also where is the skin refresh button ?
> and also why cant we select View type in Category widgets ?
> Studio Icon still missing from home screen . See inb4after above picture
> and a request for polished bright Rating icons (right now its dull).

For liked percent: `Skin Settings > Library views > Enable / disable ratings > Disable Star rating > Enable Liked percent`

Skin refresh button is in the power menu by default. Alternatively use the command `ReloadSkin()`, if you want to create a custom menu item/widget.

Category widgets only have 3 viewtypes: `Skin Settings > Widgets > Choose category widget size > Small/Medium/Large`

Studio logos can be enabled in `Skin Settings > Widgets > Select Widgetbar items > Enable Ratings > Enable Studio Logo`, see [screenshot](https://i.imgur.com/xYsmQFL.jpg)

Please open a new issue for each feature request / bug report. At the moment we're focusing on bugfixes before considering new features.

**Comment by Nazim1981** [comment]
> For liked percent: `Skin Settings > Library views > Enable / disable ratings > Disable Star rating > Enable Liked percent`
> 
> Skin refresh button is in the power menu by default. Alternatively use the command `ReloadSkin()`, if you want to create a custom menu item/widget.
> 
> Category widgets only have 3 viewtypes: `Skin Settings > Widgets > Choose category widget size > Small/Medium/Large`
> 
> Studio logos can be enabled in `Skin Settings > Widgets > Select Widgetbar items > Enable Ratings > Enable Studio Logo`, see [screenshot](https://i.imgur.com/xYsmQFL.jpg)
> 
> Please open a new issue for each feature request / bug report. At the moment we're focusing on bugfixes before considering new features.


1- OK finally I got like percentage .
2- Found Skin Load button under Power .
3- I enabled Studio Logo from Widget Bar But still not able to show in Home & Hub , there is slightly something missing which causes not to display Studio logo , although I have enabled Studio Icon- Coloured .
4- Can I set effect of transparency on different hubs differently ? Like I want to disable transparency for Spotlight Netflix Home 
 Layout but I want to keep enable it for Movie Aura Hub . But skin option showing if I disable transparency it will disable for all home & hubs strange?

**Comment by SerpentDrago** [comment]
3.Do you have the studio logo resource pack installed? Not every item will have the meta info to show one either.  

4. No

Honestly it seems. No offence. Your a bit picky with your exact preferences. You may find it better to fork the skin and start learning editing skins xml files. Again we are not really looking to add more features to the skin atm. It has to many as is and the source of most bugs. 


If you really want a feature feel free to make a pr with code changes and we can merge

**Comment by Nazim1981** [comment]
> 3.Do you have the studio logo resource pack installed? Not every item will have the meta info to show one either.
> 
> 1. No
> 
> Honestly it seems. No offence. Your a bit picky with your exact preferences. You may find it better to fork the skin and start learning editing skins xml files. Again we are not really looking to add more features to the skin atm. It has to many as is and the source of most bugs.
> 
> If you really want a feature feel free to make a pr with code changes and we can merge

3- Studio Logos resource pack already installed . I found studio Logo does appearing randomly on TV Shows but totally vanished in Movies section .
https://i.postimg.cc/W1FbPPYt/image.png

No I dont have that kind of knowledge I am related with Travel & Tourism full time. Thanks
Don't close the thread may be I need more things to know.

**Comment by SerpentDrago** [comment]
can you give a example of something that you think should have a studio logo and doesn't ? you got to understand the label / meta info that the skin uses to know what to show is  listitem.Studio , and not all movies / shows have that meta info available . Generally tv shows do , but movies lots of time do NOT .

**Comment by Nazim1981** [comment]
> can you give a example of something that you think should have a studio logo and doesn't ? you got to understand the label / meta info that the skin uses to know what to show is listitem.Studio , and not all movies / shows have that meta info available . Generally tv shows do , but movies lots of time do NOT .

This is my Titan  Bingie Mode (Current) with Seren widgets  .Not a single movie without Studio Logo . Same seren meta info not working for Aura 
https://www.youtube.com/watch?v=c2IRxU8071s

**Comment by SerpentDrago** [comment]
yeh they use skin helper for service lookups  which is a dead addon .. , currently working on why tmdb helper service lookups  is giving bad data for first sudio , and thus failing to find the image in the resource package

**Comment by SerpentDrago** [comment]
WHy did you switch from TBM ?

**Comment by Nazim1981** [comment]
> WHy did you switch from TBM ?

Well TBM not working well recently with Library content causing Kodi to reach CPU 100% Usage .
https://i.postimg.cc/1RLKFbf6/image.png

and I think it caused by Skin Helper Service

otherwise its absolute fine , I have 15000 movies in library , I dont know whenever I try to load widgets in TBM through TMDB integrated library , CPU Blasted . although I did not test Aura for that size of library either .

**Comment by SerpentDrago** [comment]
Auramod is setup so you don't have to use a  library you can directly point widgets at addons. And all its functions work with addons. Unlike most skins that reserve features / only work with library functions 

I see absolutely no reason somone would need 15k movies in library that's insanity. Only reason would be if they are real files. And at that point your much better off using plex

**Comment by Nazim1981** [comment]
> Auramod is setup so you don't have to use a library you can directly point widgets at addons. And all its functions work with addons. Unlike most skins that reserve features / only work with library functions
> 
> I see absolutely no reason somone would need 15k movies in library that's insanity. Only reason would be if they are real files. And at that point your much better off using plex

Yes but Library contents is way faster and the widgets are from local metadata (nfo) artwork with thousand of tags playlists . there is a huge difference between online & local instant loading . 15K is (.strm) format not real media. Huge collection is for choosing whatever we need to play .

**Comment by SerpentDrago** [comment]
i'd instead sync to library shows you are watching and things like that . Movies can be browsed from addons . yes its slower but then you never are dealing with the problems you are having . even jurial will tell you tmdb helper was never designed to sync and keep in sync such a large collection . its why he doesn't even allow syncing your trakt collection directly . 

you do you , but with that large of a fake library .. your only going to have more headaches . is the speed worth that much headache ? i decided a long long time ago it was not . 

Heck i dont' even use kodi daily anymore , i use syncler , and its fast without having to deal with library items . only reason i mess with kodi anymore is cause users like auramod and kodi , and want to use it . i do it for the community . its NOT my daily driver anymore .

**Comment by inb4after** [comment]
@Nazim1981

Studios have been fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).

Please let us know your results, and if any new bugs occur.

**Comment by Nazim1981** [comment]
> @Nazim1981
> 
> Studios have been fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).
> 
> Please let us know your results, and if any new bugs occur.

https://i.postimg.cc/zXzXcHDt/image.png
https://i.postimg.cc/kM6g3PW8/image.png

I Checked , its working fine with two flaws ,
1- Size is too small , dirty icons,  unable to read anything (most of the time)
2- IMDB ratings & Votes gone with this , it may show the ratings who already  cached  but the new imdb ratings not showing except imdb250.

Update : Imdb ratings with votes missing 80% of the time and its randomly show some time but mostly of the time its broken.

**Comment by adamosborne83** [comment]
> > > @Nazim1981 3-Movie Progress Refilling Round icon is not clear enough to know how much movie is left to watch , it should be somewhat similar see below picture (Progress % on Posters )
> > > https://i.postimg.cc/Zq4ZkBSY/image.png
> > > Thats not how this skin is designed , it shows either a bar or a round icon
> > 
> > 
> > Basically we sat a little far from our 65'' TV , and its hard to get from round icon .
> > OK
> > how did you get Green percentage rating 94% Liked instead of star rating ? Also where is the skin refresh button ?
> > and also why cant we select View type in Category widgets ?
> > Studio Icon still missing from home screen . See inb4after above picture
> > and a request for polished bright Rating icons (right now its dull).
> 
> For liked percent: `Skin Settings > Library views > Enable / disable ratings > Disable Star rating > Enable Liked percent`
> 
> Skin refresh button is in the power menu by default. Alternatively use the command `ReloadSkin()`, if you want to create a custom menu item/widget.
> 
> Category widgets only have 3 viewtypes: `Skin Settings > Widgets > Choose category widget size > Small/Medium/Large`
> 
> Studio logos can be enabled in `Skin Settings > Widgets > Select Widgetbar items > Enable Ratings > Enable Studio Logo`, see [screenshot](https://i.imgur.com/xYsmQFL.jpg)
> 
> Please open a new issue for each feature request / bug report. At the moment we're focusing on bugfixes before considering new features.

Out of interest, I do not have 'enabled studio icons' is this something that I'd need to download??? I don't really like it or see the need, just as always slightly curious

**Comment by Nazim1981** [comment]
> Out of interest, I do not have 'enabled studio icons' is this something that I'd need to download??? I don't really like it or see the need, just as always slightly curious

Just search colour in kodi and install studio icon- colour. It will display  then.

**Comment by SerpentDrago** [comment]
Location of where to install Studio icons , both colored and monochrome/white 

https://user-images.githubusercontent.com/21133858/119204489-8755ae00-ba63-11eb-9cbf-489e29c67b96.mp4

**Comment by Nazim1981** [comment]
Can rating icons get more polished ,  clean & bigger ? also can you add fake codec   ULTRA HD 4K tag?
https://i.postimg.cc/qBYw7Nwm/image.png

**Comment by SerpentDrago** [comment]
Eventually the icons will be bigger , to be fair they are already as clean as they can look at only 32px , The are perfectly done just not big enough to properly display them . but yes they will all be getting a go over , this thread is way to long , put specific requests in their own thread please . 

Fake codec tags will NEVER be added , majority of users are using aura mod for non local content where the exact quality of a movie/show is only known after you scrape sources . I'm not adding a fake codec . only info / meta that is actually known and real . 

Feel free to open NEW issues for any bugs or requests , this thread is way to long and all over the place . thanks :)
