### ISSUE TITLE
[Question/Change] Could you change the WonderfulSubs Search Result to Kaito

### ISSUE THREAD

**Issue by Goldenfreddy0703** [SerpentDrago/skin.auramod#96]
Hey, sorry to bother you but I've been testing on your skin a lot and was wondering if you could change DefaultSearch-WonderfulSubs to Kaito sense Kaito is a popular anime addon that was forked from Seren. I could change it from template in shortcuts but when i keep updating Auramod, the template needs to be changed again. 
If you could change it to this on your next update, that would be really great. 

DefaultSearch-WonderfulSubs
```
            <property name="path" tag="property" attribute="name|list" value="DefaultSearch-WonderfulSubs">plugin://plugin.video.wonderfulsubs/search/</property>
            <property name="path2" tag="property" attribute="name|list" value="DefaultSearch-WonderfulSubs">/1</property>
```

DefaultSearch-Kaito
```
            <property name="path" tag="property" attribute="name|list" value="DefaultSearch-WonderfulSubs">plugin://plugin.video.kaito/search/</property>
            <property name="path2" tag="property" attribute="name|list" value="DefaultSearch-WonderfulSubs">/1</property>
```

Here is the github link to Kaito: https://github.com/SwagOtaku/plugin.video.kaito

Its a really great addon and it replaced WonderfulSubs a while ago and WonderfulSubs got shutdown a few months ago.

**Comment by SerpentDrago** [comment]
Sounds good I'll do it when i add venom and fen also.

For now instead of changing the existing search templet just add a new search list item  then it will persist. You add them just like you would a widget. Edit search lists in the skin. No need to modify base files

**Comment by Goldenfreddy0703** [comment]
Ok, thank you very much and your the best.

**Comment by SerpentDrago** [comment]
added to DefaultSearchlistupdate  Branch , please test and report back and it can be merged to Matrix and then eventually repo

**Comment by Goldenfreddy0703** [comment]
Hey thank you so much, sorry Ive been but i will test it out now and see if it works.

**Comment by Goldenfreddy0703** [comment]
Hey, I just tested it and you guy did a great job on this, thank you guys so much and now i don't have to edit the template again when updating. Again, Thank you guys so much and you guys are the best.

**Comment by inb4after** [comment]
Added in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.7
