### ISSUE TITLE
ClearLogo bug with "Episode list" view mode

### ISSUE THREAD

**Issue by inb4after** [SerpentDrago/skin.auramod#97]
- Tested with Seren addon widget (Next Up), `Context menu > Information > Browse season`
- `Skin Settings > Widgets > Enable clearlogos on widgets` is enabled, so these clearlogos should be visible regardless.
- Only affects `Episode list` view mode.

Opening the power menu reveals the clearlogos that are supposed to be visible.

This means these clearlogos are found, but are not visible because of focus.

**Comment by SerpentDrago** [comment]
To clarify , Browse any season of any show , in any addon that supplies clearlogs . switch to "episodes" view style . 

You will notice a lack of clear logos ON the episodes thumbnails / fanart . it should be there , if you press the power menu button (s) on a keyboard , you will see clear logos appear as they should based on that skin setting 

![image](https://user-images.githubusercontent.com/21133858/118988175-f42b5400-b94e-11eb-948d-6f18bf382057.png)
![image](https://user-images.githubusercontent.com/21133858/118988406-289f1000-b94f-11eb-905f-d9afef2754a3.png)

**Comment by inb4after** [comment]
Improved the view, feedback is welcome, here's how it looks so far:

Unfocused: https://i.imgur.com/1hX4XmZ.png
Focused: https://i.imgur.com/VlBPMpy.png
Various: https://i.imgur.com/2dsG6qx.png

**Comment by inb4after** [comment]
Made the progress bar slightly thicker than before and rounded the bottom corners:

Unfocused, compare with above: https://i.imgur.com/vhUKQgO.png
Focused, compare with above: https://i.imgur.com/T3PZVCm.png

Unfocused, large clearlogo: https://i.imgur.com/zzmxO1G.png
Focused, large clearlogo: https://i.imgur.com/veMRTxi.png

I prefer the thinner line, but we can adjust it to find a good middle ground.

**Comment by inb4after** [comment]
Improved in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.15
