### ISSUE TITLE
Use regional ratings instead of US MPAA

### ISSUE THREAD

**Issue by adamosborne83** [SerpentDrago/skin.auramod#99]
This is not an issue or anything, rather, an if you can.

Being from the UK, is there an option to show British rating for films, for example 18,15,12A.... etc etc, as opposed to US ratings 'R' for example.

I am using Seren, Venom and TMDB, 
Cheers as always.

**Comment by inb4after** [comment]
For TMDBHelper you can change the setting `General > Language and Country` to `English (United Kingdom)` and it will show UK ratings for TMDBHelper items, but not other addons. I don't see a similar setting in Seren, but it should be possible to implement a skin setting to prefer the regional TMDBHelper rating setting.

As it's a feature request it will be prioritized lower than bugs at the moment.

**Comment by adamosborne83** [comment]
> For TMDBHelper you can change the setting `General > Language and Country` to `English (United Kingdom)` and it will show UK ratings for TMDBHelper items, but not other addons. I don't see a similar setting in Seren, but it should be possible to implement a skin setting to prefer the regional TMDBHelper rating setting.
> 
> As it's a feature request it will be prioritized lower than bugs at the moment.

It doesn't even work for me in TMDB, its not even an issue tbf,  so can be closed of you want.

**Comment by inb4after** [comment]
> 
> 
> > For TMDBHelper you can change the setting `General > Language and Country` to `English (United Kingdom)` and it will show UK ratings for TMDBHelper items, but not other addons. I don't see a similar setting in Seren, but it should be possible to implement a skin setting to prefer the regional TMDBHelper rating setting.
> > As it's a feature request it will be prioritized lower than bugs at the moment.
> 
> It doesn't even work for me in TMDB, its not even an issue tbf, so can be closed of you want.

Make sure to restart Kodi and that the items you're testing are not added to library.

**Comment by adamosborne83** [comment]
Is this more of an addon suggestion for Seren, or shall I leave it on here?
Do you know if it would be a easy mod for seren?

**Comment by inb4after** [comment]
> Is this more of an addon suggestion for Seren, or shall I leave it on here?
> Do you know if it would be a easy mod for seren?

It would be easier if Seren had control of this, but the skin can also do lookups as a backup.

Not sure if it's easy to add!

**Comment by adamosborne83** [comment]
Thanks for replying 🙂
